### ISSUE TITLE
version-2 branch vs master....

### ISSUE THREAD

**Issue by sirvon** [Shopify/mobile-buy-sdk-android#140]
in version-2 branch
the url being called to access products and collections is 

```java
"api/apps/{appId}/collection_listings.json"
```

but in master it is
```java
"/api/channels/{channel}/collection_publications.json"
```

what does appId stand for in version-2 branch?
Is it still looking for channelId or does it have something to do with "extensions"..?

I get....

```
<-- 404 Not Found https://st-pete-mall.myshopify.com/api/apps/XXXXX/collection_listings.json?page=1&limit=25 (338ms)
```

XXXXX = the channelId

i'm focused on the version-2 branch because i want to use the "RX" way instead of the "callback" way

How do I get the version-2 branch to work?

thanks

**Comment by krisorr** [comment]
Hi,
Great to hear that you are interested in using our new Rx api.
Channel Id is no longer used in the 2.0 sdk.  It is being replaced with the App id, which is related to extensions.
The App Id for the Mobile Channel is 8.  
Please be aware that the version-2 branch is a work in progress and may change somewhat before release.
