### ISSUE TITLE
Update Gradle file used for Sample in Release packages

### ISSUE THREAD

**Issue by krisorr** [Shopify/mobile-buy-sdk-android#149]
We have a build.gradle.packaging that we distribute with our release to allow the building of the Sample application.
This sample gradle file is out of date with our main gradle file.  It is difficult to maintain and keep in sync - we should investigate better ways to distribute the Sample code and associated build files.

**Comment by krisorr** [comment]
Actually, we should just drop distributing our samples in the release at all.
It should just contain the libraries, and javadoc.

If people want samples they can clone github and run them.
This is more in line with what other sdks do, ie. retrofit 
@bgulanowski  what do you think?

**Comment by bgulanowski** [comment]
If I understand what you're saying, I agree. I wouldn't normally include samples apps in an SDK release distribution. The built version isn't much value. Users want to see the code itself.

**Comment by krisorr** [comment]
nope, that is not what I am saying.
We were distributing source in the release zip.  I am suggesting that we do
not do that, and direct users to github for sample code

**Comment by bgulanowski** [comment]
Right. If the source was private, then we would include sample code in the SDK distribution. But for open source, it's redundant.
