### ISSUE TITLE
[Feature Request] Kindly add Search functionality with the Android SDK

### ISSUE THREAD

**Issue by niwinnm** [Shopify/mobile-buy-sdk-android#15]
It would be great if it possible to Search the set of products with a user entered keyword. An additional method in BUYClient class like GetProducts(String keyword, Callback callback){} would really be helpful.

**Comment by niwinnm** [comment]
Any update guys?

**Comment by krisorr** [comment]
Hi, thank you for the feature request.
We do not have plans to implement search at this time.

**Comment by niwinnm** [comment]
@krisorr - Any plans to add this in v2?

**Comment by droidAadi** [comment]
Any plans to add it in v2?

**Comment by krisorr** [comment]
We have added support for getting products by tags, but general search will not be supported in v2.0.0.

**Comment by droidAadi** [comment]
search a product via product name is the basic e-commerce functionality which should have been present from version 1 itself. The same feature is available for website then why can't it be added in the mobile buy sdk?

**Comment by krisorr** [comment]
connected to #287

**Comment by sav007** [comment]
2.x is no longer maintained. New version 3.0 has been released. Closing.
