### ISSUE TITLE
Fix getting productId and collectionId in samples

### ISSUE THREAD

**Issue by krisorr** [Shopify/mobile-buy-sdk-android#176]
We are incorrectly doing null checks on productId and collectionId when we are getting them from the intent as a long which will never be null.

They will never be null, we should only be pulling them out of the intent if they exist there, which will make sure the later null checks are correct.

**Comment by krisorr** [comment]
@sav007 can you take this one?

**Comment by sav007** [comment]
Sure

**Comment by krisorr** [comment]
src/main/java/com/shopify/sample/ui/ProductDetailsBuilder.java
90:    public ProductDetailsBuilder setProductId(String productId) {
91:        productDetailsConfig.setProductId(productId);
125:            throw new IllegalArgumentException("One of productId or product must be provided, and cannot be empty");

src/main/java/com/shopify/sample/ui/ProductDetailsConfig.java
50:    private String productId;
72:        return productId;
99:    public void setProductId(String productId) {
100:        this.productId = productId;
135:        if (productId != null) {
136:            bundle.putString(EXTRA_SHOP_PRODUCT_ID, productId);

src/main/java/com/shopify/sample/ui/ProductDetailsFragment.java
77:    private Long productId;
130:        if (product == null && productId != null) {
131:            fetchProduct(productId);
208:        productId = bundle.getLong(ProductDetailsConfig.EXTRA_SHOP_PRODUCT_ID, -1);
279:    private void fetchProduct(final Long productId) {
280:        buyClient.getProduct(productId, new Callback<Product>() {
290:                    productDetailsListener.onFailure(createErrorBundle(ProductDetailsConstants.ERROR_GET_PRODUCT_FAILED, "Product id not found: " + productId));

**Comment by krisorr** [comment]
risorr@Kriss-MacBook-Pro ~/sandbox/android/mobile-buy-sdk-android/MobileBuy/sample (version-2)*$ ag collectionId
src/main/java/com/shopify/sample/activity/CollectionListActivity.java
174:     * @param collectionId
176:    private void onCollectionClicked(Long collectionId) {
178:        if (collectionId != null) {
179:            intent.putExtra(ProductListActivity.EXTRA_COLLECTION_ID, collectionId);

src/main/java/com/shopify/sample/activity/ProductListActivity.java
56:    private Long collectionId;
73:            collectionId = intent.getLongExtra(EXTRA_COLLECTION_ID, -1);
135:            if (collectionId != null) {
136:                getSampleApplication().getProducts(collectionId, callback);

src/main/java/com/shopify/sample/application/SampleApplication.java
181:    public void getProducts(Long collectionId, Callback<List<Product>> callback) {
183:        buyClient.getProducts(1, collectionId, callback);
krisorr@Kriss-MacBook-Pro ~/sandbox/android/mobile-buy-sdk-android/MobileBuy/sample (version-2)*$ ag productId
src/main/java/com/shopify/sample/ui/ProductDetailsBuilder.java
90:    public ProductDetailsBuilder setProductId(String productId) {
91:        productDetailsConfig.setProductId(productId);
125:            throw new IllegalArgumentException("One of productId or product must be provided, and cannot be empty");

src/main/java/com/shopify/sample/ui/ProductDetailsConfig.java
50:    private String productId;
72:        return productId;
99:    public void setProductId(String productId) {
100:        this.productId = productId;
135:        if (productId != null) {
136:            bundle.putString(EXTRA_SHOP_PRODUCT_ID, productId);

src/main/java/com/shopify/sample/ui/ProductDetailsFragment.java
77:    private Long productId;
130:        if (product == null && productId != null) {
131:            fetchProduct(productId);
208:        productId = bundle.getLong(ProductDetailsConfig.EXTRA_SHOP_PRODUCT_ID, -1);
279:    private void fetchProduct(final Long productId) {
280:        buyClient.getProduct(productId, new Callback<Product>() {
290:                    productDetailsListener.onFailure(createErrorBundle(ProductDetailsConstants.ERROR_GET_PRODUCT_FAILED, "Product id not found: " + productId));
