### ISSUE TITLE
Sample App getting crashed  on Fetching the collections just after the launch.

### ISSUE THREAD

**Issue by adikhullar** [Shopify/mobile-buy-sdk-android#18]
Just installed the sample app. But it is getting crashed every time while fetching the collections on launch on Android.
Getting 403 error from the retrofit.
Kindly update on how to resolve this issue.
Currently I am using following dummy credentials for testing :
SHOP_DOMAIN=myshop.myshopify.com
API_KEY=0123456789abcdefghijklmnopqrstuvwxyz
CHANNEL_ID=2345678

**Comment by krisorr** [comment]
Hi,
Please post your questions related to implementation to https://ecommerce.shopify.com/c/shopify-apis-and-technology, and we will do our best to help you out.
