### ISSUE TITLE
Please make your model objects implements Parcelable

### ISSUE THREAD

**Issue by VikaChebotar** [Shopify/mobile-buy-sdk-android#182]
It would be cool if we can pass Product from one fragment to another without downloading it two times.

**Comment by bgulanowski** [comment]
Pull requests welcome.

**Comment by krisorr** [comment]
Hi,
You do not need to download the Product twice.  You can use GSON to serialize the Product, and pass that in the bundle.
And example of putting the Product into a bundle can be found at https://github.com/Shopify/mobile-buy-sdk-android/blob/master/MobileBuy/buy/src/main/java/com/shopify/buy/ui/ProductDetailsConfig.java#L159
And retrieving it from the bundle can be seen here:
https://github.com/Shopify/mobile-buy-sdk-android/blob/master/MobileBuy/buy/src/main/java/com/shopify/buy/ui/ProductDetailsFragment.java#L213

**Comment by VikaChebotar** [comment]
@krisorr Thank you!

**Comment by krisorr** [comment]
You are welcome.
