### ISSUE TITLE
Can't run the Sample App.

### ISSUE THREAD

**Issue by MaxTa91** [Shopify/mobile-buy-sdk-android#192]
I am Max. 
I am trying to run the sample App but I can't. 
It is always showing the error when opening the App. 

"ssl=0x617b6120 cert_verify_callback x509_store_ctx=0x6198a940 arg=0x0
ssl=0x617b6120 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA"

I think it is the problem about OKHTTP, right?
Please help me to solve this problem.

**Comment by krisorr** [comment]
Hi, if you are still having issues with this please post to our forums. 
https://ecommerce.shopify.com/c/shopify-apis-and-technology
