### ISSUE TITLE
Add GetProducts by collection handle in V2.0

### ISSUE THREAD

**Issue by niwinnm** [Shopify/mobile-buy-sdk-android#198]
It would great if there is an function like `getProductsByCollectionHandle(String collectionHandle, Callback<Products> callback){}` in the SDK to fetch a group of products based on collection handle. It is sort of a must have to implement Deep linking and Apple universal link support inside the mobile app for any Shopify store.

**Comment by krisorr** [comment]
Support added on server side by https://github.com/Shopify/shopify/pull/77637.
Next step is to add support on client side.

**Comment by niwinnm** [comment]
Great. Looking forward to the new SDK release.
