### ISSUE TITLE
Cart function sample

### ISSUE THREAD

**Issue by andrewkusuma** [Shopify/mobile-buy-sdk-android#203]
how to use cart feature for sample, buy more than one product in app. anyone can tell me about it? thanks

**Comment by krisorr** [comment]
Hi,

Please take a look at:
https://github.com/Shopify/mobile-buy-sdk-android/blob/develop/MobileBuy/sample/src/main/java/com/shopify/sample/application/SampleApplication.java#L197

This example adds a single product variant to the Cart, but you can repeat the call to add other variants before you use the Cart to complete the checkout.

We have a forum which is better suited for this kind of question, please see https://ecommerce.shopify.com/c/shopify-apis-and-technology for other helpful information about the SDK.
