### ISSUE TITLE
Setting default address using updateCustomer seems broken

### ISSUE THREAD

**Issue by mat1h** [Shopify/mobile-buy-sdk-android#220]
Setting the `Customer` objects' `defaultAddress` field and calling `updateCustomer` does not change the `defaultAddress`. Is this field ignored for `updateCustomer` ?

**Comment by davidmuzi** [comment]
Looks like a server side issue

**Comment by krisorr** [comment]
The server has been updated.  We need to update the client to use updated server api, and add more tests.

**Comment by krisorr** [comment]
The defaultAddress on Customer is read only.
To set the default Address for a customer, please use the Address endpoint.

Address defaultAddress = new Address();
defaultAddress.setDefault(true);
buyClient.updateAddress(defaultAddress)
