### ISSUE TITLE
what is APP_ID ?? (Release 2.0.0)(Getting Error checked in Debug mode: OnError while emitting onNext value: )

### ISSUE THREAD

**Issue by droidAadi** [Shopify/mobile-buy-sdk-android#230]
Hi ,

Can anyone let me know, what I need to send in APP_ID param inside the sample?
I tried with Channel_Id , but it is not working.
Getting Error (checked in Debug mode): OnError while emitting onNext value: retrofit2.Response.class
Any pointers would be helpful.

**Comment by krisorr** [comment]
Hi,
the APP_ID at this time is 8.  When we officially release, you will be able to find the appropriate app_id in your shops admin, under the Mobile Channel.

**Comment by droidAadi** [comment]
by when can we expect that v2 will go live?

**Comment by droidAadi** [comment]
any update? by when can we expect v2 to go live??

**Comment by droidAadi** [comment]
I would like to go live with my app but due to App Id hardcoding, I can't. So it would be great if you people can let me know when is the expected release date for v2.0.

**Comment by krisorr** [comment]
Hi
