### ISSUE TITLE
Need Search Product functionality in App.

### ISSUE THREAD

**Issue by droidAadi** [Shopify/mobile-buy-sdk-android#231]
Hi,

Is there any API exposed, that can serve the purpose of Search functionality in the app, so that user can search for a particular product in an app?
It would be great, if this feature is implemented.

**Comment by krisorr** [comment]
Hi, 
this issue is being tracked already in https://github.com/Shopify/mobile-buy-sdk-android/issues/15.
I am going to close this issue as a duplicate.
