### ISSUE TITLE
BuyClientError.getRetrofitErrorBody() always returns an empty string

### ISSUE THREAD

**Issue by vincentngo3151991** [Shopify/mobile-buy-sdk-android#249]
**Step to reproduce:**
Any network call that results in BuyClientError

**Expected behavior:**
BuyClientError.getRetrofitErrorBody() returns raw retrofit response error body string.

**Actual behavior:**
BuyClientError.getRetrofitErrorBody() always return "" regardless of the error type.

**Observation:**
The content of errorBody inside RetrofitResponse passes through the constructor contains the correct raw response from the server.
![screen shot 2016-07-29 at 11 49 34 am](https://cloud.githubusercontent.com/assets/12567346/17303772/fbdf4258-57d6-11e6-9eea-aab7e43eb40b.png)

The content of errorBody in RetrofitResponse in BuyClientError is empty.
![screen shot 2016-07-29 at 11 50 37 am](https://cloud.githubusercontent.com/assets/12567346/17303781/0631d8a6-57d7-11e6-9a2b-7112933b11d5.png)

**Cause:**
ResponseBody class is one time stream originates from the server to the client application. Calling ResponseBody.string() in BuyClientError.parseRetrofitErrorResponse(Response retrofitResponse) consumes the response body thus re-read ResponseBody.string() by invoking BuyClientError.getRetrofitErrorBody() method throws Exception. This cause BuyClientError.getRetrofitErrorBody() always return "".

**Comment by krisorr** [comment]
Thank you for the detailed bug report. We will look into it.

Which version/build of the SDK did you see this behaviour on?

**Comment by vincentngo3151991** [comment]
Thank you for the response. This behavior was observed on Mobile Buy SDK v2.0.0. 

Additional libraries:
Retrofit v2.1.0
OkHttp v3.4.1

Thanks
