### ISSUE TITLE
Conflict between Play Services

### ISSUE THREAD

**Issue by krisorr** [Shopify/mobile-buy-sdk-android#255]
The library has a dependency on Play Services 8.40.
Applications using newer versions of Play Services have errors compiling due to conflicts.

Investigate how to work around this.

We have had reports specifically from users with 9.21, but this is likely going to be a general issue going forward.

**Comment by krisorr** [comment]
A quick fix is to exclude the wallet library explicitly, and add the version desired.

compile 'com.google.android.gms:play-services-wallet:9.4.0'
    compile ('com.shopify.mobilebuysdk:buy:2.0.1') {
        exclude group: 'com.google.android.gms', module: 'play-services-wallet'
   }

**Comment by krisorr** [comment]
In the long run, we should split the Play Services dependent Android Pay out into a separate library, or source code.

**Comment by krisorr** [comment]
Waiting on ticket/more information from partner before proceeding.

**Comment by edmundliang** [comment]
When will you be updating to 9.4.1 for play services?

**Comment by krisorr** [comment]
@edmundliang I will be updating to 9.4.0 later this week, as per the latest release on https://developers.google.com/android/guides/setup
