### ISSUE TITLE
Add source to PaymentToken

### ISSUE THREAD

**Issue by krisorr** [Shopify/mobile-buy-sdk-android#257]
The PaymentToken should have a source field.
This will be mobile_sdk for our sdk.
This can be used to help identify the source of Android Pay transactions, and track any issues.

**Comment by krisorr** [comment]
@bgulanowski - this is something that came up in the AndroidPay chat.  We should probably add this for Android Pay and Apple Pay to make it easier to track origin/issue server side.

**Comment by bgulanowski** [comment]
Where does the value get stored server-side? I thought the transaction and payment receipt already included info that the source was a mobile app. Maybe I'm wrong.

**Comment by krisorr** [comment]
This value would get passed through to Cardserver.

**Comment by krisorr** [comment]
@bgulanowski - are you going to add this on iOS for 2.1 release?

**Comment by krisorr** [comment]
@bgulanowski - bump
