### ISSUE TITLE
[Feature Request] Product images in the ProductListActivity within the ListView

### ISSUE THREAD

**Issue by mustie** [Shopify/mobile-buy-sdk-android#26]
Only feature needed to complete the api.

**Comment by krisorr** [comment]
The sample code is provided as an example of how to use the api to complete a checkout, and is not intended to be part of the API.
We will not be adding more UI to the sample at this time.

**Comment by mustie** [comment]
Okay, would you be able to point me in a direction of how I can go about doing this myself?
