### ISSUE TITLE
Products from Collection error

### ISSUE THREAD

**Issue by mat1h** [Shopify/mobile-buy-sdk-android#262]
Class: 
`BuyClient`

Method:
`public void getProducts(int page, String collectionId, final Callback<List<Product>> callback)`

SDK version: 
`1.2.4`

Issue:
Sometimes, the callback returns Error with code `500 Internal Server Error`. Making the same call after a few seconds returns a successful response. This behavior is random.

**Comment by krisorr** [comment]
@mat1h - there were some intermittent issues yesterday with the servers that would cause 500 errors, but the issue has been resolved now.
Are you still seeing issues today?

**Comment by krisorr** [comment]
@mat1h I am going to close this ticket as the underlying server issues have been resolved.  Please feel free to re-open if you are still seeing the problem.
