### ISSUE TITLE
Payment gateway error with Android Pay in test environment

### ISSUE THREAD

**Issue by vincentngo3151991** [Shopify/mobile-buy-sdk-android#264]
**Steps to reproduce:**
Setup sample app with test shop properties, enable Android Pay in test shop
Enable Android Pay with ENVIRONMENT_TEST
Proceed through the checkout flow and confirm the order

**Expected behavior**
Successfully place the order with WalletConstants.ENVIRONMENT_TEST for test shop

**Actual behavior**
The app throw the error:
`{"errors":{"checkout":{"payment_gateway":[{"code":"processing_error","message":"Your payment could not be processed at this time, please try again in a few minutes","options":{"raw_gateway_error":"There was an error processing your payment. Please try again."}}]}}}`

**Comment by krisorr** [comment]
Hi @vincentngo3151991 

There was an issue with the servers a couple of days ago that was causing this particular error, but it has been resolved.
Are you still seeing this error message?

If you are using ENVIRONMENT_TEST, you will be able to complete most of the Checkout process but will not be able to complete the payment.  The token returned from Android Pay for ENVIRONMENT_TEST is not valid for payment, and will be declined when it is sent to the payment gateway for processing.  A "card declined" error would be the expected result.

**Comment by vincentngo3151991** [comment]
Confirmed that we get "card declined" error. 

We are in process of getting the app approved for ENVIRONMENT_PRODUCTION. However, it was declined production access by Google Pay team because they cannot complete the payment. Is there anyway we can complete the checkout with ENVIRONMENT_TEST?

**Comment by krisorr** [comment]
Because of the restrictions on Tokens returned in the FullWallet, there is no way to complete the entire checkout process using ENVIRONMENT_TEST.  I have talked to the team at Google and they will be on the lookout for this and it should not prevent Whitelisting going forward.
