### ISSUE TITLE
[Optimization Request] Simplify build.gradle

### ISSUE THREAD

**Issue by henrytao-me** [Shopify/mobile-buy-sdk-android#266]
It is easier to follow if build.gradle file can be split to smaller files. 
- Jacoco related gradle can be found here: https://github.com/henrytao-me/bootstrap-android-app/blob/master/jacoco.gradle
- Signing configuration can be found here: https://github.com/henrytao-me/bootstrap-android-app/blob/master/app/signing.gradle
- Versioning system based on git commit can be found here: https://github.com/henrytao-me/bootstrap-android-app/blob/master/app/versioning.gradle
- Master config file including bintray can be found here: https://github.com/henrytao-me/bootstrap-android-library/blob/master/config.gradle

Final build.gradle file can look like this https://github.com/henrytao-me/bootstrap-android-library/blob/master/library/build.gradle

Because these are quite big changes, I would love to have your opinions.

**Comment by krisorr** [comment]
Those file are nice and clean.  Our gradle is not quite that big yet, but this could be a nice refactor.

**Comment by sav007** [comment]
2.x is no longer maintained. New version 3.0 has been released. Closing.
