### ISSUE TITLE
BuyClientError does not provide any underlying error

### ISSUE THREAD

**Issue by saurabhPV** [Shopify/mobile-buy-sdk-android#268]
When I try to create user with existing id or password with length less than 5, earlier it used to provide json with both errors through `getErrors()` but now suddenly it has stopped and it does not provide any info about the error.

**Comment by krisorr** [comment]
Hi,
Which version of the SDK are you using?

**Comment by saurabhPV** [comment]
v2 its added as dependancy in Gradle  `compile "com.shopify.mobilebuysdk:buy:2.0.0" `

**Comment by krisorr** [comment]
Please try compile "com.shopify.mobilebuysdk:buy:2.0.1", there was an issue with getErrors() in 2.0.0

**Comment by saurabhPV** [comment]
Thanks @krisorr 
It's  still not working with `getErrors()` but at least `getRetrofitErrorBody().toString()` works!

**Comment by saurabhPV** [comment]
@krisorr Hey its not working with version 2.0.1 either for `loginCustomer`. And unfortunately even `getRetrofitErrorBody().toString()` does not work. 
Right now I have to check it this way
`  if( error.getRetrofitResponse().message() != null && error.getRetrofitResponse().message().equalsIgnoreCase("Unauthorised"))
`
iOS counterpart is very well on this front. Was expecting similar type of error handling in Android :-(

**Comment by krisorr** [comment]
Thanks for the update, I will take a look.

**Comment by krisorr** [comment]
@saurabhPV - can you post the code you are using with getErrors() that is not working?

**Comment by saurabhPV** [comment]
@krisorr  Oh its not a much of a code. Here you go
`private void loginCustomer(String email, String password) {

        final AccountCredentials accountCredentials = new AccountCredentials(email, password);
// buyClient is initialised already 
        buyClient.loginCustomer(accountCredentials, new Callback<Customer>() {
            @Override
            public void success(Customer customer) {
                // save the customer or token for later use
                try {
                    Log.v("CONSOLE", customer.toJsonString());
                    JSONObject job = new JSONObject();
                    job.put("user", customer.toJsonString());
                    job.put("token", buyClient.getCustomerToken().getAccessToken());
                    Log.v("CONSOLE", "Result " + job);
                }catch (Exception ex){
                    Log.v("CONSOLE",ex.getMessage());
                }
            }

            @Override
            public void failure(BuyClientError error) {
                // handle error
                try{
                    if(error.getErrors() != null)
                    {
                        Log.v("CONSOLE","got geterrors");
                    }else{
                        Log.v("CONSOLE", "no  geterrors checking getMessage= " + error.getMessage() + " getRetrofitErrorBody= " + error.getRetrofitErrorBody() + "error string" + error.toString());
                        if(error.getType() == BuyClientError.ERROR_TYPE_NETWORK){

                        }else if(error.getType() == BuyClientError.ERROR_TYPE_UNKNOWN){

                        }
                        else if(error.getType() != BuyClientError.ERROR_TYPE_API) {

                        }else{
                            Log.v("CONSOLE", "got getRetrofitResponse");
                            Log.v("CONSOLE", error.getRetrofitResponse().message());
                            if( error.getRetrofitResponse().message() != null && error.getRetrofitResponse().message().equalsIgnoreCase("Unauthorized"))
                            Log.v("CONSOLE", "Invalid id or password");
                            else {
                            }
                        }
                    }
                }catch (Exception ex){
                    Log.v("CONSOLE",ex.getMessage());
                }
            }
        });
    }`

**Comment by saurabhPV** [comment]
@krisorr  There isn't much of a code, here you go

       private void loginCustomer(String email, String password) {

        final AccountCredentials accountCredentials = new AccountCredentials(email, password);

        buyClient.loginCustomer(accountCredentials, new Callback<Customer>() {

            @Override
            public void success(Customer customer) {
                // save the customer or token for later use
                try {
                    Log.v("CONSOLE", customer.toJsonString());
                    JSONObject job = new JSONObject();
                    job.put("user", customer.toJsonString());
                    job.put("token", buyClient.getCustomerToken().getAccessToken());
                    Log.v("CONSOLE", "Result " + job);
                }catch (Exception ex){
                    Log.v("CONSOLE",ex.getMessage());
                }
            }

            @Override
            public void failure(BuyClientError error) {
                // handle error
                try{
                    if(error.getErrors() != null)
                    {
                        Log.v("CONSOLE","got geterrors");

                    }else{
                        Log.v("CONSOLE", "no  geterrors checking getMessage= " + error.getMessage() + " getRetrofitErrorBody= " + error.getRetrofitErrorBody() + "error string" + error.toString());
                        if(error.getType() == BuyClientError.ERROR_TYPE_NETWORK){

                        }else if(error.getType() == BuyClientError.ERROR_TYPE_UNKNOWN){

                        }
                        else if(error.getType() != BuyClientError.ERROR_TYPE_API) {

                        }else{
                            Log.v("CONSOLE", "got getRetrofitResponse");
                            Log.v("CONSOLE", error.getRetrofitResponse().message());
                            if( error.getRetrofitResponse().message() != null && error.getRetrofitResponse().message().equalsIgnoreCase("Unauthorized")){
                              }
                            else {

                            }
                        }
                    }

                }catch (Exception ex){
                    Log.v("CONSOLE",ex.getMessage());
                }
            }
        });
    }

**Comment by krisorr** [comment]
@saurabhPV for the login it is expected that 401 is the status code, and it is expected that it has no retrofit body.

**Comment by saurabhPV** [comment]
@krisorr Thanks but how do I read 401 status code ? in iOS sdk there is a code property but I could not find its equivalent in Android.

**Comment by krisorr** [comment]
for error.getErrors, you need to specify the path for the error.
ie: error.getErrors("customer", "password)

**Comment by saurabhPV** [comment]
will it work even though `error.getErrors() ` is null. Earlier it used to fetch map (I guess).

**Comment by krisorr** [comment]
error.getType should be ERROR_TYPE_API.
error.getRetrofitResponse().code() can be used to get the exact error code.

**Comment by saurabhPV** [comment]
Yes its giving 401 with ERROR_TYPE_API. Closing issue.
