### ISSUE TITLE
Not able to see product details Page

### ISSUE THREAD

**Issue by pchauhan** [Shopify/mobile-buy-sdk-android#27]
Hello ,

I am able to see all product listing but while clicking on any product getting error like
02-21 20:03:51.407 12293-12293/com.shopify.sample E/SampleActivity: Error: {"errors":{"checkout":{"email":[],"payment_gateway":[{"code":"invalid","message":"is invalid","options":{}}],"line_items":[],"source_name":[],"reservation_time":[]}}}

Thanks
Parag

**Comment by krisorr** [comment]
Hi,
please refer to https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/need-more-payment-gateways-for-mobile-sdk-in-india-309282#comment-311683.
