### ISSUE TITLE
Cart data is lost once app is closed.

### ISSUE THREAD

**Issue by saurabhPV** [Shopify/mobile-buy-sdk-android#271]
If the app is not killed I can add variants to cart but once app is killed it flushes the cart. So new cart variable does not pull any previous data.

**Comment by bgulanowski** [comment]
Carts are transient objects. If an application needs to persist the cart's contents, then it should serialize the cart and store it using whatever approach is appropriate for the app.

It's out of scope for the SDK to persist data locally.
