### ISSUE TITLE
Remove setters for read only properties on Customer

### ISSUE THREAD

**Issue by krisorr** [Shopify/mobile-buy-sdk-android#274]
The Customer model  includes fields that are not provided by the underlying API, because they are meant to be merchant-facing.

These fields are writeable by clients:
```
email: String
acceptsMarketing: BOOL
firstName: String
lastName: String
addresses: Ordered Set
```

These additional fields are read-only:
```
createdAt
identifier
defaultAddress
lastOrderId
lastOrderName
multipassIdentifier
ordersCount
state
taxExempt
totalSpent
updatedAt
verifiedEmail
password is effectively write-only.
```

The following fields will be removed:
```
note
tags
```

**Comment by krisorr** [comment]
connects to #272

**Comment by krisorr** [comment]
@bgulanowski

**Comment by krisorr** [comment]
@mtaher - can email, first name, last name be changed on a customer by doing an update?

**Comment by mtaher** [comment]
Yup, those field (email, first_name and last_name) can be changed by an update.

**Comment by krisorr** [comment]
@mtaher thanks.

What are the rules around password?  I have this "password is effectively write-only" note, and don't remember what it means.

**Comment by mtaher** [comment]
I'm guessing because we never return the password field; you can update it, you can reset it but technically we never return it hence write-only(?).

**Comment by krisorr** [comment]
That makes sense, thanks
