### ISSUE TITLE
[Feature request] Return CartLineItem after calling addVariant

### ISSUE THREAD

**Issue by henrytao-me** [Shopify/mobile-buy-sdk-android#275]
Hi team, 

I think it makes scene to return `CartLineItem` after calling `addVariant` because without it, there is no way to retrieve `CartLineItem` for added `ProductVariant` except iterate through the whole list.

**Comment by henrytao-me** [comment]
My use case is: showing zero quantity in cart list before checkout. 

Basically, in cart list screen before checkout, I have increase and decrease button for every single ProductVariant. It seems like it is tricky to show zero quantity in current API.

**Comment by krisorr** [comment]
Hi Henry,
What is the use case for showing a line item in the Cart with no quantity?  Can you describe when you would want to do that?

**Comment by henrytao-me** [comment]
Hi @krisorr 

Please take a look at below screenshot. I have a list of CartLineItem in Cart screen and two button for increasing and decreasing those items. So, if I decrease to zero and want to keep it available in the RecyclerView, just in case user want to increase it again, how can I do it without wrapping CartLineItem by another data structure? 

![screenshot](https://firebasestorage.googleapis.com/v0/b/android-shopify.appspot.com/o/public%2FScreenshot%20(Aug%2030%2C%202016%2004-28-15).png?alt=media)

**Comment by sav007** [comment]
2.x is no longer maintained. New version 3.0 has been released. Closing.
