### ISSUE TITLE
Expose the sort order field on Collection

### ISSUE THREAD

**Issue by krisorr** [Shopify/mobile-buy-sdk-android#278]
There is an extra field, sort_order which says what the sort order for the collection is.
We need to add it to the model.

**Comment by krisorr** [comment]
@bgulanowski - do you expose this field on iOS?

**Comment by krisorr** [comment]
@sav007 do we still need this?

**Comment by bgulanowski** [comment]
We do not have that field. I don't believe it was in 1.0 so it was not carried over to 2.0. Is it in the response? What is the use case?

**Comment by bhavinwebdesk** [comment]
Hello Guys,
Why this issue is closed?
Is it any work around for it?

My use case is I have to sort Products by new to old.

Thanks,
Bhavin

**Comment by bgulanowski** [comment]
There is no further active development on the 2.0 branch of the Mobile Buy SDK. Version 3.0 may have support for this. @dbart01 can clarify.

**Comment by dbart01** [comment]
Version `3.0` offers a `sortKey` parameter for `shop.collections` and `shop.products`. Keep in mind, however, that `sortKey` doesn't exists on `collection.products` since products contained in a collection can have their own inherent order.

**Comment by bhavinwebdesk** [comment]
@dbart01 so like if collection is sort by Title than **collection.products** inherent order?

**Comment by dbart01** [comment]
That's right. The order of products in a collection set in your shop's Admin will be the same as the order returned by this query:
```graphql
{
  shop {
    collections(first: 20) {
      edges {
        node {
          title
          products(first: 20) { # sorted by the order in Admin
            edges {
              node {
                title
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by dbart01** [comment]
Alternatively, if you'd like an explicit sort order, you can provide it via a `sortKey` parameter, which is available on `shop.products`. For example:
```graphql
{
  shop {
    products(first: 20, sortKey: UPDATED_AT) { # sorted by the last time a product was updated
      edges {
        node {
          title
        }
      }
    }
  }
}
```

**Comment by bhavinwebdesk** [comment]
Thanks @dbart01 for reply,
so is there any possible solution for sort Product of single collection by sortKey?
I mean like by name, price, added.
Can it be enable from admin side or from schema?

Thanks

**Comment by dbart01** [comment]
There is currently no way to that right now. We are, however, investigating the possibility of adding that feature soon.

**Comment by bhavinwebdesk** [comment]
Thanks @dbart01.

should I open new issue for this? so that you can update status there.
or I can wait for announcements.

**Comment by dbart01** [comment]
Please wait for further releases.
