### ISSUE TITLE
[SDK 2.0.0] Get list of products by handles

### ISSUE THREAD

**Issue by mat1h** [Shopify/mobile-buy-sdk-android#280]
There should be a similar method like 

`getProductByHandle(String handle, Callback<Product> callback)`

for multiple handles to get a list of products:

`getProductsByHandles(List<String> handles, Callback<List<Product>> callback)`

**Comment by mat1h** [comment]
Any chance of this being included in the next release?

**Comment by krisorr** [comment]
We do not have plans to include this in the next release at this time.
