### ISSUE TITLE
Strange Issue generating checkout

### ISSUE THREAD

**Issue by rmfleetTS** [Shopify/mobile-buy-sdk-android#281]
I'm developing an application that connects with two Shopify instances (dual currency).  I have a "test" product that has been created with the exact same parameters on each store.  

The code paths for the two stores through the application are the exact same, with the exception of the API keys used to connect.

For this "Test" product, I have disabled the Online Store channel and enabled the Mobile app channel along with the Buy button.

On one store, I can successfully create a cart, add product and checkout, but on the second store, the checkout causes a failure return.

If I enable the "Online store" visibility, the checkout works correctly for both instances.  

I have been communicating with an associate at Shopify and have been directed to post a message here for further investigation after no resolution was found.  The application is using dual Android/iOS SDK's and although I am posting this to the Android SDK, the same error is occurring through the iOS SDK as well.  The application uses a unified interface through Cordova, making the code path exactly the same up to the point of communication with the SDK's.

Below is some debug information collected.  Line 170 in the second debug shows the failure message I receive back from Shopify via client.getErrorBody, where client is an object of BuyClient.  Each time the application attempts to create a checkout, it first clears out any existing reservations through a call to client.removeProductReservationsFromCheckout.  This also appears to fail for the second store.  Line 163 is JSON data built from information in the cart.

Shop 1 (Success)
:155 clear checkout succeeded
:162 retrieved cart
:163 [{"product_id":"8927853127","variant_id":"29617092487","title":"TEST","variant_title":"Small","price":"0.01","quantity":"1"}]
:165 created checkout
:151 clear checkout succeeded
:162 retrieved cart
:163 [{"product_id":"8927853127","variant_id":"29617092487","title":"TEST","variant_title":"Small","price":"0.01","quantity":"1"}]
:165 created checkout

Shop 2 (Failure)
:155 clear checkout failed:
:162 retrieved cart
:163 [{"product_id":"5054378180","variant_id":"20185677508","title":"TEST","variant_title":"Small","price":"0.01","quantity":"1"}]
:169 failed to create checkout
:170 {"errors":{"checkout":{"line_items":[{"variant_id":[{"code":"invalid","message":"is invalid","options":{}}]}],"source_name":[],"reservation_time":[]}}}
:155 clear checkout failed:
:162 retrieved cart
:163 [{"product_id":"5054378180","variant_id":"20185677508","title":"TEST","variant_title":"Small","price":"0.01","quantity":"1"}]
:169 failed to create checkout
:170 {"errors":{"checkout":{"line_items":[{"variant_id":[{"code":"invalid","message":"is invalid","options":{}}]}],"source_name":[],"reservation_time":[]}}}

**Comment by krisorr** [comment]
@rmfleetTS what are the urls for Shop 1, Shop2?

**Comment by rmfleetTS** [comment]
Hi Kris,

Would it be possible to reach you through an e-mail vs disclosing that information on here.

Thanks.

**Comment by krisorr** [comment]
@bgulanowski, @davidmuzi  - the ticket description says this happens on iOS as well.

**Comment by krisorr** [comment]
@rmfleetTS - please have the associate reach out to me with your email address and I will take a look.

**Comment by rmfleetTS** [comment]
@krisorr - Thank you. I've sent a message through.

**Comment by krisorr** [comment]
Does it always fails if "Online Store Visibility" is not turned on?

Can you try upping the quantity available for the variant, or turn on "Allow customers to purchase this product when it's out of stock" and see what the result is?

**Comment by rmfleetTS** [comment]
It does always fails for the one store if it is not enabled.

I have two variants set for the product.  One with a quantity of 2, the other with 9.  Both behave the same.  

Additional tests.

On the failing store:
I just added a third variant with a quantity of 100 for the failing store.  Result: Failed.

I added a variant with a quantity of 1 and "Allow customers to purchase this product when it's out of stock". Result: Failed.

On the store that passes:
I added another variant with a quantity of 1. Result: Passed.

I added a variant with a quantity of 0 and "Allow customers to purchase this product when it's out of stock". Result: Passed.

I added a variant with a quantity of 0. Result: App prevents adding it to the cart. (as expected)

Just to note: the application does also check quantity before it allows the user to add to the cart.

**Comment by krisorr** [comment]
@rmfleetTS thanks for the update

**Comment by krisorr** [comment]
@rmfleetTS - this issue should be resolved now, please give it a try.  There was a tweak that needed to be made server side related to published items on web and mobile.

**Comment by rmfleetTS** [comment]
@krisorr thanks. Yes the fix has been confirmed to work.
