### ISSUE TITLE
AndroidPay Checkout Issue for setting email what we get from Android pay

### ISSUE THREAD

**Issue by Rishabh31User** [Shopify/mobile-buy-sdk-android#284]
Hello ,I am facing issue when i am going to make payment with Android Pay ,we are receiving a consistent error at the final step of payment. All the previous steps have been successfully implemented. 

Can you please check the cause of this on an urgent basis as we have a launch planned for next week. I am pasting the error message below:

{
  "errors": {
    "checkout": {
      "payment_gateway": [
        {
          "code": "processing_error",
          "message": "Your payment could not be processed at this time, please try again in a few minutes",
          "options": {
            "raw_gateway_error": "There was an error processing your payment. Please try again."
          }
        }
      ]
    }
  }
}
![screenshot_2016-09-10-01-35-40](https://cloud.githubusercontent.com/assets/15205021/18483544/20533d22-7a02-11e6-8ff9-6f29d41ef606.png)

**Comment by poweredbyac** [comment]
cc @krisorr This is the situation we were chatting about in Slack :)

**Comment by krisorr** [comment]
@Rishabh31User 
Hi, I have a couple of questions that will help me triage this issue.
1) What environment are you using for Wallet in your app?  is it ENVIRONMENT_TEST, or ENVIRONMENT_PRODUCTION
2) Have you had your App whitelisted by Google for Access to the Production environment?
3) Have you ever seen a different error, or does it consistently give you this error?

would you be able to cut and paste the code snippets where you initialize the MaskedWallet fragment, and where you call our api to complete the Checkout using Android Pay?

Thanks

**Comment by krisorr** [comment]
Here is some extra information to help you along with integrating Android Pay and our Checkout api.

Please refer to the documentation here: https://developers.google.com/android-pay/ which walks through how to set an app up to accept Android Pay.

In particular, please take a look at https://developers.google.com/android-pay/get-started which details what you need to do qualify your apk and publish it on the Play Store with Android Pay.
The Google documentation is quite thorough, and if you have any questions directly related to Android Pay that are not covered there are contact links to reach out to the experts at Google.

This document: https://help.shopify.com/api/sdks/mobile-buy-sdk/android/integration-guide/checkout has information about how to complete a Checkout on Shopify with Android Pay.

**Comment by Rishabh31User** [comment]
1) What environment are you using for Wallet in your app? is it
ENVIRONMENT_TEST, or ENVIRONMENT_PRODUCTION-----WalletConstants.
ENVIRONMENT_PRODUCTION
2) Have you had your App whitelisted by Google for Access to the Production
environment?-----Yes This part is done
3) Have you ever seen a different error, or does it consistently give you
this error?--No every time i am seeing this error only

this is code what i am using for initialising for Andrroid pay----

private void createAndAddWalletFragment() {
    WalletFragmentStyle walletFragmentStyle = new
WalletFragmentStyle().setBuyButtonText(WalletFragmentStyle.BuyButtonText.BUY_WITH).setBuyButtonAppearance(WalletFragmentStyle.BuyButtonAppearance.ANDROID_PAY_DARK).setBuyButtonWidth(1,
350);
    WalletFragmentOptions walletFragmentOptions =
WalletFragmentOptions.newBuilder().setEnvironment(Constants.WALLET_ENVIRONMENT).setFragmentStyle(walletFragmentStyle).setTheme(WalletConstants.THEME_LIGHT).setMode(WalletFragmentMode.BUY_BUTTON).build();
    mWalletFragment = SupportWalletFragment.newInstance(walletFragmentOptions);
    // Now initialize the Wallet Fragment
    Checkout checkout = getSampleApplication().getCheckout();
    WalletFragmentInitParams.Builder startParamsBuilder = null;
    String accountName = getString(R.string.app_name);
    androidPaySelectedAsPaymentMethod();
    if (checkout == null) {
        // Direct integration
        String totalPrice =
secureCheckOutTextOrderTotalPrice.getText().toString().replace("$",
"");
        ItemInfo itemInfo = new ItemInfo("Florists.com", "Florists
cart", Double.parseDouble(totalPrice),
Double.parseDouble(totalShippingCharge), Constants.CURRENCY_CODE_USD,
"Seller Data", R.mipmap.appicon);
        //ItemInfo itemInfo =new ItemInfo("1800Flowers","1800
cart",Double.parseDouble("1"),Double.parseDouble("00"),CURRENCY_CODE_USD,"Seller
Data",R.drawable.ic_app_icon);
        Constants.ITEMS_FOR_SALE = itemInfo;
        MaskedWalletRequest maskedWalletRequest =
WalletUtil.createMaskedWalletRequest(Constants.ITEMS_FOR_SALE,//Constants.ITEMS_FOR_SALE[0],
                getString(R.string.public_key));
        startParamsBuilder =
WalletFragmentInitParams.newBuilder().setMaskedWalletRequest(maskedWalletRequest).setMaskedWalletRequestCode(REQUEST_CODE_MASKED_WALLET).setAccountName(accountName);
    } else {
        MaskedWalletRequest maskedWalletRequest =
AndroidPayHelper.createMaskedWalletRequest(accountName, checkout,
BuildConfig.ANDROID_PAY_PUBLIC_KEY, true);
        startParamsBuilder = WalletFragmentInitParams.newBuilder()
                .setMaskedWalletRequest(maskedWalletRequest)
                .setMaskedWalletRequestCode(REQUEST_CODE_MASKED_WALLET);

    }
    mWalletFragment.initialize(startParamsBuilder.build());
    if (mOnRemovingShippingAddress) {
        mWalletFragment.setEnabled(false);
    }
    // add Wallet fragment to the UI
    getSupportFragmentManager().beginTransaction().replace(R.id.wallet_button_holder,
mWalletFragment).commit();
    // [END params_builder]
    if (checkout != null) {
        disableSubmitButton();
    }
}

**Comment by Rishabh31User** [comment]
And one more thing we are getting encrypted payload from android pay that
means android pay integration is correctly done,but from this encrypted
payload ,we are unable to checkout process.

**Comment by krisorr** [comment]
@Rishabh31User 

Please double check the ANDROID_PAY_PUBLIC_KEY you are using is correct.
You will need to go to your shop admin, and turn Android Pay on, and use the key there.

https://screenshot.click/14-09-09-2144.jpg

As well, please post the code where you request the full wallet, create the PaymentToken from the FullWallet, and complete the checkout.

**Comment by Rishabh31User** [comment]
Yes i was not enable android pay from my shop domain ,after i enable
android pay and use that key inside my code now I am getting different
error message.please look screenshot i attached here,

**Comment by krisorr** [comment]
@Rishabh31User - which screenshot?  did you forget to attach?

**Comment by Rishabh31User** [comment]
as an attachment i added .now can you see that

**Comment by krisorr** [comment]
@Rishabh31User I see from the logs that you are getting a "card declined" error.
This could be caused by several reasons:

1) Your bundle identifier and signing keys do not match the ones that you used while whitelisting with Google
2) Your bank is rejecting the transaction for some reason (cross border restrictions, fraud detection etc.)
3) You are use Production environment for the Masked Wallet Request, but have not set Production on the Google Api Client used to make the FullWallet Request


Here is an example of how to create the api client for the FullWallet request:
``
googleApiClient = new GoogleApiClient.Builder(getActivity())
            .addApi(
                Wallet.API,
                new Wallet.WalletOptions.Builder()
                    .setEnvironment(BuildConfig.ANDROID_PAY_ENVIRONMENT)
                    .setTheme(WalletConstants.THEME_LIGHT)
                    .build()
            )
            .enableAutoManage(getActivity(), this)
            .build();
``

**Comment by krisorr** [comment]
@Rishabh31User - not sure what is wrong with the attachments, they may be getting stripped because you are responding by email - but I do not see it.

**Comment by Rishabh31User** [comment]
I will ask with my manager about why  bank are rejecting my transaction
from payment .

On Sep 15, 2016 1:06 AM, "Kris Orr" <notifications@github.com> wrote:
>
> @Rishabh31User - not sure what is wrong with the attachments, they may be
getting stripped because you are responding by email - but I do not see it.

**Comment by krisorr** [comment]
if you post the code you use for getting the FullWallet, creating the GoogleApiClient, and for calling completeCheckout I would be happy to review it for you.

**Comment by Rishabh31User** [comment]
Now after changed my google api client initialiing code as you sugeested .
i am getting exception like this:-

"{"checkout":{"payment_gateway":[{"code":"processing_error","message":"Your
payment could not be processed at this time, please try again in a few
minutes","options":{"raw_gateway_error":"There was an error processing your
payment. Please try again."}}]}}}"

every time!!!!

**Comment by Rishabh31User** [comment]
Hello,
Please update for this exception wich i am getting from android pay .now these type for exception i am getting . please look screenshot.
![screenshot_2016-09-15-05-00-37](https://cloud.githubusercontent.com/assets/15205021/18558699/ade31d02-7b91-11e6-953e-dcaee4da6ec0.png)
![screenshot_2016-09-15-05-12-42](https://cloud.githubusercontent.com/assets/15205021/18558700/ade63d84-7b91-11e6-85e9-e521d5c80744.png)
![screenshot_2016-09-15-05-15-55](https://cloud.githubusercontent.com/assets/15205021/18558701/ae15662c-7b91-11e6-91be-4133952d5a5f.png)

**Comment by krisorr** [comment]
@Rishabh31User please post the code where you create the PaymentToken, and complete the checkout.

Are these failures from today or yesterday?  That will help me track them down in the log.

**Comment by Rishabh31User** [comment]
![screenshot_2016-09-15-22-47-44](https://cloud.githubusercontent.com/assets/15205021/18559912/0d06f0c4-7b97-11e6-9275-b8612dfc82b0.png)
Today when i tried then this exception occur and amount also deduct from my Card ,because i get notification from Android pay with amount .

here is my code for create payment token and for complete checkout :---

 paymentToken = AndroidPayHelper.getAndroidPaymentToken(fullWallet, BuildConfig.ANDROID_PAY_PUBLIC_KEY);
        buyClient.completeCheckout(paymentToken, checkout.getToken(), wrapCheckoutCallback(callback));

**Comment by krisorr** [comment]
Okay, that is a Stripe error.  Either Stripe or your bank does not like that the zip code you are sending - it does not match what is registered with the card.

Are you using the addresses returned from the Masked Wallet?  Android Pay app does verification with the bank etc. when you add the card to make sure that they are valid.
It may still go through if you have your Stripe settings set to ignore this particular error.

**Comment by Rishabh31User** [comment]
Yes i am using the billing address which Masked wallet return ,and its showing UB56YJ (London)..and my shipping address zipcode is 11514 (US). so is that issue with Card Billing address Zipcode. and how we can reduce this error.please suggest

**Comment by krisorr** [comment]
I would suggest checking with the bank to see what zip code that have
associated with that card.

**Comment by Rishabh31User** [comment]
Thanks Sir ,Now i am able to checkout with android pay 
 big thank you from my side , still need one little help ,when we get FullWallet object from Android pay so can we change the email address in it. because now when i am going to checkout email id is sending whatever we getting from Android Pay(Full Wallet ) object,but i need that email id should be ,user which have login in my app .

**Comment by Rishabh31User** [comment]
Hello Sir. Please suggest what we need to do??

**Comment by krisorr** [comment]
@Rishabh31User - are you referring to the order confirmation email sent by Shopify?

If that is the case, just make sure that the email that you set in your Checkout object is the one from the logged in customer.  
You can set it at any time before you complete the checkout.

```
myCheckout.email = "some email";
buyClient.updateCheckout(checkout, callback);
```

**Comment by krisorr** [comment]
@Rishabh31User - did this fix your issue?
