### ISSUE TITLE
Product options values

### ISSUE THREAD

**Issue by monishagarwal215** [Shopify/mobile-buy-sdk-android#286]
Hi we are adding some variants like color, size and brand.

And each has some values like 

Color: Red, blue green
Brand : Levis, Bennetton
Size : 36, 32,40

We are getting option in product model with values Color, Brand, Size.

But we are not getting values inside these options.

Please confirm how to display all the option values.

**Comment by krisorr** [comment]
Hi,
The OptionValues are stored on each ProductVariant.
To get a list of all the possible OptionValues you will need to iterate the ProductVariants available for your product, and call getOptionValues() on each.
