### ISSUE TITLE
PaymentToken cannot be null

### ISSUE THREAD

**Issue by vincentngo3151991** [Shopify/mobile-buy-sdk-android#288]
**Step to reproduce:**

Add product to shopping cart
Add gift card so that the entire balance is covered by gift card
Complete checkout without putting credit card information

**Expected behavior:**

Checkout completed successfully (worked in v1)

**Actual behavior:**

Get PaymentToken cannot be null error

**Comment by krisorr** [comment]
@vincentngo3151991 - There is a fix for this on a branch that we are targeting for release later this week. 
https://github.com/Shopify/mobile-buy-sdk-android/pull/292

**Comment by krisorr** [comment]
@vincentngo3151991 this should be fixed on the 2.0.2 release which is now available.

If your owing amount is 0, you can create an empty PaymentToken to use when completing the checkout with PaymentToken.createEmptyPaymentToken.
