### ISSUE TITLE
Mobile Buy Crashesh

### ISSUE THREAD

**Issue by ranmale** [Shopify/mobile-buy-sdk-android#289]
how to add shop.propertties file  in mobile buy becz it doesnt contains app folder

this gives me error
Caused by: java.lang.IllegalArgumentException: 
                                                   	Add your shop credentials to a shop.properties file in the main app folder (e.g. 'app/shop.properties'). Include these keys:
                                                   		SHOP_DOMAIN=<myshop>.myshopify.com
                                                   		API_KEY=0123456789abcdefghijklmnopqrstuvw
                                                   You must add 'SHOP_DOMAIN' entry in app/shop.properties, in the form '<myshop>.myshopify.com'

**Comment by henrytao-me** [comment]
Hi @ranmale 

You can try to add `shop.properties` in following directory `<your_module_name>/shop.properties`. Try project view mode in android studio. 

I hope it helps.

**Comment by krisorr** [comment]
Thanks Henry.  
@ranmale I am going to close this ticket, please feel free to re-open if this did not fix your problem.

**Comment by ranmale** [comment]
i have added shop.properties in sample directory but this also doesnt solve my problem

**Comment by henrytao-me** [comment]
I can help to look into your repo if I have permission.

**Comment by ranmale** [comment]
yes

**Comment by henrytao-me** [comment]
If you dont mind, please give me access to your repo. I will take a look. Other possibility is teamviewer. Thanks.

**Comment by ranmale** [comment]
yes why not

**Comment by ranmale** [comment]
give me a time when u onlin

**Comment by henrytao-me** [comment]
I can do it now.

**Comment by ranmale** [comment]
289 237 413 this is my id treamviewer

**Comment by henrytao-me** [comment]
Hi @krisorr 

After looking into issue on @ranmale device, I found that gradle script can not read `shop.properties` file on Windows environment. He needs to hard set all credentials in `build.gradle` file.
