### ISSUE TITLE
Native Payment Options 

### ISSUE THREAD

**Issue by AkashDoshi19** [Shopify/mobile-buy-sdk-android#308]
![device-2016-09-23-190104](https://cloud.githubusercontent.com/assets/11500220/18832047/de703766-8406-11e6-9f85-71e567efb10a.png)

Hello,

We would like to add options like COD or Payment gateways in addition to options highlighted in image shown above.

Is it possible to add these options ?
We could not find any functions or classes in Buy SDK for,
1. Perform COD operation
2. For Payment Gateways ( E.g. PayUMoney)

If they are not present then it will be very good if we have this features in SDK.
Generally People do not want to process payment through webview also it is that not secure.

**Comment by krisorr** [comment]
Thank you for the feature request, we will take a look at adding this in a future release.

**Comment by sav007** [comment]
2.x is no longer maintained. New version 3.0 has been released. Closing.
