### ISSUE TITLE
Product.hasDefaultVariant misses some cases

### ISSUE THREAD

**Issue by krisorr** [Shopify/mobile-buy-sdk-android#310]
hasDefaultVariant currently checks to see if the variant title is "Default Title", but some default variants may have a title of "Default" depending on when they were created.

**Comment by krisorr** [comment]
We should be checking that Variant title and Option value are in:
 final List defaultVariantTitles = Arrays.asList("default", "default title", "title");
        final List defaultOptionValues = Arrays.asList("default title", "default");

**Comment by krisorr** [comment]
The server side code ignores the variant title when checking to see if it is default.

The ruby code on the server does this in Product:
```
 def has_only_default_variant?
    first_option_value = fetch_variants.first.option_values.first

    total_variants == 1 &&
    fetch_options.size == 1 &&
    fetch_options.first.name == Option::DEFAULT_NAME &&
    (first_option_value == Option::DEFAULT_VALUE || first_option_value == Option::DEFAULT_CSV_VALUE)
  end

```
where:
```
DEFAULT_NAME      = "Title"
  DEFAULT_VALUE     = "Default Title"
  DEFAULT_CSV_VALUE = "Default"
```

**Comment by krisorr** [comment]
@bgulanowski - you will need to update this on iOS as well.

**Comment by bgulanowski** [comment]
On iOS, we currently check for "Default Title" on the variant title (which that server code appears not to do), and for "Default" or "Default Title" as the value on the only object in the options (we are instances of `OptionValue`).

Have you ever seen just plain "Title" in the wild? I'm wondering if that's a really old name.

https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Models/Persistent/BUYProduct.m#L124-L125

**Comment by krisorr** [comment]
@bgulanowski - the variant title doesn't actually matter, it is not used to determine if it is a default variant.
Only the option name and value are used.
