### ISSUE TITLE
Error when calling updateCheckout after waiting roughly 10 mins

### ISSUE THREAD

**Issue by henrytao-me** [Shopify/mobile-buy-sdk-android#312]
Hi team, 

I got this error when calling `mBuyClient.updateCheckout(checkout)` after roughly 10 mins. If I call that method again after getting error message, it works again. 

Here is the error with error type is `ERROR_TYPE_API`

``` json
{
  "errors": {
    "checkout": {
      "shipping_rate_id": [{
        "code": "invalid",
        "message": "is invalid",
        "options": {}
      }],
      "shipping_rate": {
        "id": [{
          "code": "invalid",
          "message": "is invalid",
          "options": {}
        }]
      },
      "line_items": []
    }
  }
}
```

Step to reproduce: 
1. Create checkout 
2. Let the app idle in 5 to 10 mins. 
3. Call `mBuyClient.updateCheckout(checkout)` => throw above Exception
4. Call step 3 again => work 

Do you have any idea what is happening? I thought about something related to expired checkout token but it isn't. I double check: checkout token in step 3 and 4 are the same. 

Thanks, 
Henry

**Comment by henrytao-me** [comment]
Here is my current `updateCheckout` method
```java
  private Observable<Checkout> updateCheckout(Checkout checkout) {
    return mBuyClient.updateCheckout(checkout)
        .flatMap(co -> mStorageService.setCheckout(co).map(aVoid -> co));
  }
```

Here is my workaround 
```java
  private Observable<Checkout> updateCheckout(Checkout checkout) {
    return mBuyClient.updateCheckout(checkout)
        .onErrorResumeNext(throwable -> mBuyClient.updateCheckout(checkout))
        .flatMap(co -> mStorageService.setCheckout(co).map(aVoid -> co));
  }
```

**Comment by henrytao-me** [comment]
My assumption is that: 
- In the first update request: the token is expired, server-side return error back to client and renew that token at the same time. 
- In the second update request (with the same token): it works because the token is renewed already on server-side.

**Comment by krisorr** [comment]
Hi Henry, I will have to look into this.  The first error is not because of the checkout expiring, but possible issues with the shipping rate being expired.

Which shipping options do you have on your shop?  and when are you setting the shipping rate?

**Comment by henrytao-me** [comment]
Hi Kris,

Intersting. You are right. In checkout flow, I have 4 steps: address, shipping, payment and summary. I selected shipping rate, updated checkout, stopped there and came back to continue after X minutes. IMO, this is a common use case. User may not finish checkout immediately. If the app doesnt handle it correctly, it may show weird behavior to the user. 

Why do we have expire time for shipping rate?

**Comment by henrytao-me** [comment]
I setup 3 shipping options. All are in `Rest of the world` category. These options are based on weight.

**Comment by spidy18** [comment]
how to import project into android studio .?
im facing problem while building gradle .
