### ISSUE TITLE
Could not find method connectedDebugAndroidTest() for arguments

### ISSUE THREAD

**Issue by mbpatelandroid** [Shopify/mobile-buy-sdk-android#313]
FAILURE: Build failed with an exception.
- Where:
  Build file '/home/techiestown/MEHUL/mobile-buy-sdk-android-master/MobileBuy/buy/build.gradle' line: 197
- What went wrong:
  Could not find method connectedDebugAndroidTest() for arguments [build_5h1pno6stt1akneh44u3jpual$_run_closure3$_closure11$_closure21$_closure27@755b2b20] on object of type com.android.build.gradle.internal.api.LibraryVariantImpl.

**Comment by krisorr** [comment]
This appears to be an issue with instant-run.  To work around it for now, please try it without instant run turned on.
