### ISSUE TITLE
Missing imageUrl in LineItem model

### ISSUE THREAD

**Issue by henrytao-me** [Shopify/mobile-buy-sdk-android#314]
Hi team, 

I have a summary screen before purchasing. It lists out all information related to checkout. From `Checkout` object, I can retrieve `LineItem` using `checkout.getLineItems()`. However, for each LineItem, I can't get `imageUrl` of the product to show it on the screen. This would be an easy fix. Please take a look. Thanks. 

Below is the constructor of LineItem Model. 

``` java
    public LineItem(ProductVariant variant) {
        variantId = variant.getId();
        price = variant.getPrice();
        title = variant.getTitle();
        requiresShipping = variant.isRequiresShipping();
        quantity = 1;
    }
```

**Comment by davidmuzi** [comment]
The models defined in the SDK represent the properties and relationships as defined in the Shopify API.

To get this sort of behaviour, your application would need to maintain a mapping from the lineitem, and its image
