### ISSUE TITLE
Android Pay Payment Failure

### ISSUE THREAD

**Issue by MeNiks** [Shopify/mobile-buy-sdk-android#315]
Hi,

I am integrating android pay in app. i am using
WalletConstants.ENVIRONMENT_PRODUCTION enviornment 
App is whitelisted by Google for Access to the Production environment
and there is no issue with fingureprint all matches and working fine if total of my cart is zero.

but if my cart total is greater than zero then i am getting error in

completeCheckout(FullWallet fullWallet)
failure(BuyClientError error)
With message - "Your payment could not be processed at this time, please try again in a few minutes".

Please help me.

Thanks.

**Comment by krisorr** [comment]
Please check that you are setting ENVIRONMENT_PRODUCTION when you are creating the Google api client for getting the FullWallet.

```
 googleApiClient = new GoogleApiClient.Builder(getActivity())
            .addApi(
                Wallet.API,
                new Wallet.WalletOptions.Builder()
                    .setEnvironment(WalletConstants.ENVIRONMENT_PRODUCTION)
                    .build()
            )
            .enableAutoManage(getActivity(), this)
            .build();
```

**Comment by MeNiks** [comment]
Yes i am pointing to WalletConstants.ENVIRONMENT_PRODUCTION.

googleApiClient = new GoogleApiClient.Builder(this)
                    .addApi(Wallet.API, new Wallet.WalletOptions.Builder().setEnvironment(Constants.WALLET_ENVIRONMENT).build())
                    .enableAutoManage(this, this)
                    .build();

 if total of my cart is zero i am able to place my order successfully but if my cart total is greater than zero then i am getting error while final checkout using FullWallet  object.

completeCheckout(FullWallet fullWallet)
failure(BuyClientError error)
With message - "Your payment could not be processed at this time, please try again in a few minutes".

**Comment by krisorr** [comment]
Hi, I will need a few more details to help you out.  
What is your shop url?  and an id for a checkout that you were attempting to complete, and the approximate time you made that checkout attempt.
This information will help me track down the issue in the logs.

**Comment by MeNiks** [comment]
Hi,
Yes sure i will help you out for this.

Shop URL : https://test-shopify-soumyaa.myshopify.com
Customer Name :  	Nik P 
Order ID  : #1584
Transaction At : 14/10/2016 10:51 
Email : nikhilesh@plobal.com

Checkout ID : I am getting null

And you can make transaction i have attached apk that will help you more. [https://d3myyafggcycom.cloudfront.net/shared/ecommerce.apk](url)

Discount Coupon : FREE 
You can use to make transaction free.

Click on Search type **Nice Watch** S/RED do **Buy Now** and proceed for payment.

**Comment by krisorr** [comment]
Thanks.
Please post the following snippets, and I will take a look to see if I can spot any issues.

1) create the checkout
2) create the PaymentToken
3) complete the checkout

**Comment by krisorr** [comment]
@MeNiks - I took a look at the logs and your shop settings.
You will need to enable Shopify Payments and set it up to use Android Pay, it will not work with the Bogus gateway.

**Comment by krisorr** [comment]
@MeNiks I am going to close this, please re-open if you are still having issues after setting up the payment gateway.
