### ISSUE TITLE
Multiple dex files define Lcom/google/android/gms/internal/zzrx;

### ISSUE THREAD

**Issue by jrvansuita** [Shopify/mobile-buy-sdk-android#319]
I'm getting this error when I try to use this android sdk:

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:transformClassesWithDexForDebug'.
  > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzrx;

In my dependencies, I have:
compile 'com.google.android.gms:play-services-auth:9.6.1'
compile 'com.shopify.mobilebuysdk:buy:2.0.2'

If I comment the auth dependency line, the code works, but I need Google auth in my app.

**Comment by MeNiks** [comment]
@jrvansuita  I have also faced this issue actually [Module](https://github.com/Shopify/mobile-buy-sdk-android/blob/master/MobileBuy/buy/build.gradle) is building with play services version 8.4.0 and if in your project if play services version is different then this issue is occuring.

As an alternative i have excluded wallet library.
    configurations {
        all*.exclude group: 'com.google.android.gms', module: 'play-services-wallet'
    }

And this worked for me

**Comment by jrvansuita** [comment]
I dot not have success using Shopify Android SDK with Firebase as a dependency in the same project. I'm using Retrofit and making calls to Shopify REST API.

**Comment by krisorr** [comment]
@MeNiks thanks for helping out, that is the right way to exclude the play services to prevent conflicts. 
We will be releasing a new version with an update Play Library, but it may go out of sync again in the future between releases.  We are also working on reducing the dependencies in the library.

@jrvansuita - please post details of what issues you are seeing with Firebase, with any applicable error messages.

**Comment by jrvansuita** [comment]
@krisorr  and @MeNiks, My mistake, It's working. As you @MeNiks suggest here is my dependency:

    compile 'com.shopify.mobilebuysdk:buy:2.0.2'
    configurations {
        all*.exclude group: 'com.google.android.gms', module: 'play-services-wallet'
    }


I think this configuration instruction should be advised on this page:
https://help.shopify.com/api/sdks/mobile-buy-sdk/android/integration-guide/setup

Or here, on the repository readme file.

**Comment by krisorr** [comment]
update in Setup guide, will be merged and live when we release the 2.1 sdk.
