### ISSUE TITLE
Not able to build the shopify mobile buy sdk for android "Failed to crunch file"

### ISSUE THREAD

**Issue by sruthykcs** [Shopify/mobile-buy-sdk-android#333]
I get an error "Failed to crunch file" with the location Error:com.android.builder.internal.aapt.AaptException: Failed to crunch file E:\website\mobile-buy-sdk-android-master\mobile-buy-sdk-android-master\MobileBuy\sample\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.8.0\res\drawable-xxhdpi-v4\common_google_signin_btn_text_dark_disabled.9.png into E:\website\mobile-buy-sdk-android-master\mobile-buy-sdk-android-master\MobileBuy\sample\build\intermediates\res\merged\debug\drawable-xxhdpi-v4\common_google_signin_btn_text_dark_disabled.9.png

**Comment by krisorr** [comment]
Hi,

Thanks for this issues, I will take a look.

To help me out, could you provide:
1) the branch you are building
2) your Android Studio Version


Please also try to do a clean of the project and re-index if you have not already.

**Comment by krisorr** [comment]
closing until more details are provided
