### ISSUE TITLE
add cache for okhttpclient

### ISSUE THREAD

**Issue by ggggxiaolong** [Shopify/mobile-buy-sdk-android#334]
there are cache tag set in response API, but cache is not set in okhttpclient

**Comment by krisorr** [comment]
Looks like etags are being set, but the Cache-Control directives are not so there is no built in http cache timeout.
We should allow the use of cache as per https://github.com/square/okhttp/wiki/Recipes#response-caching.

This Cache should be added as an option to the BuyClientBuilder, ie. if one is provided we will turn the cache on.
The okhttp client will still make a round trip call to see if it can use the cached value, but the server will return a 304 Not Modified if the data has not changed, and will not return a body.
OkHttp will handle this, and return the cached response.
This will not prevent the round trip but will reduce chatter on the wire.

**Comment by sav007** [comment]
2.x is no longer maintained. New version 3.0 has been released. Closing.
