### ISSUE TITLE
Not Able to add new customer

### ISSUE THREAD

**Issue by ramyku** [Shopify/mobile-buy-sdk-android#335]
The create Customer call results in failure, and the failure object is null. Please note we are able to login successfully but not add new customers. Are their any restrictions on customer creation?

Best, Ramesh

Code
=====
final AccountCredentials accountCredentials = new AccountCredentials(email, password, firstName, lastName);
11:39
final Subscription subscription = buyClient
               .createCustomer(accountCredentials)
               .subscribe(new WeakObserver<>(
                       this,
                       new Action2<CustomerRegistrationSelfActivity, Customer>() {
                           @Override
                           public void call(final CustomerRegistrationSelfActivity target, final Customer customer) {
                              Log.d("","customer creation success napo");
                               target.onFetchCustomerSuccess(customer);
                           }
                       },
                       new Action2<CustomerRegistrationSelfActivity, Throwable>() {
                           @Override
                           public void call(final CustomerRegistrationSelfActivity target, final Throwable t) {
                               Log.d("","customer creation failer napo "+t.getMessage());
                              // target.onRequestError(t);
                           }
                       }
               ));

**Comment by krisorr** [comment]
hi @ramyku 

Can you provide the shop domain, and if possible the email that was used in the failed creation, and the approximate day/time of the transaction? that will help me look up any errors in the logs.

**Comment by krisorr** [comment]
closing until more details are provided
