### ISSUE TITLE
How do people handle storing the api credentials

### ISSUE THREAD

**Issue by herghost** [Shopify/mobile-buy-sdk-android#336]
What are you doing to keep these details secure?

I am looking to implement our store into an android app and am struggling with the possibility of storing a 'free access' credential on the app itself.

I have though about hashing it using a key stored using the ndk but this could still be reversed engineered. I have thought about storing the hashed key remotely and using some kind of decryption to unhash it on the device, but again anyone peeking at the app would be able to follow the same logic to get the details.

How are others getting around this problem?

**Comment by krisorr** [comment]
The SDK only returns public information, so the api key is only used for identification.
You should not need to obfuscate the key.
