### ISSUE TITLE
Android Pay Payment gateway documentation

### ISSUE THREAD

**Issue by AkashDoshi19** [Shopify/mobile-buy-sdk-android#339]
Hi,

Since Android Pay release we didn't find any document for Android Pay. There are some documents but it says Android Pay is not yet Live but we have implemented Android Pay in My Mobile Buy SDK App. 

We have query regarding Android Pay.

Which payment gateways are supported by Android Pay? Is there any document?

For Apple Pay Shopify given clear documentation 

https://help.shopify.com/manual/payments/apple-pay

**Comment by krisorr** [comment]
Please see the forum post at https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/android-pay-payment-gateways-396041#comment-396066
