### ISSUE TITLE
How to integrate Plugin (Product Options by Bold) in shopify sdk

### ISSUE THREAD

**Issue by MeNiks** [Shopify/mobile-buy-sdk-android#340]
We have scheduled to integrate **Product Options by Bold**(Shopify App) in our ecommerce app so we are fetching product options by bold and displaying options and validating rules. But how to add such product with more variants to **com.shopify.buy.model.Cart**  object using method  **cart.addVariant(productVariant);**

As we have installed **Product Options by Bold**(Shopify App) in our website and every thing is working fine so how we can make the same thing workable for mobile app using shopify sdk.

Please help thanks.

**Comment by MeNiks** [comment]
Changed title from **Product Options by Bold integration in shopify sdk** to **How to integrate Plugin (Product Options by Bold) in shopify sdk**

**Comment by krisorr** [comment]
We only support adding variants that are retrieved as part of the Product using the SDK.
