### ISSUE TITLE
Callback when Web Checkout is complete

### ISSUE THREAD

**Issue by vlonjatg** [Shopify/mobile-buy-sdk-android#341]
Is there a way to have a callback when web checkout is complete. I know about `setWebReturnToUrl`, but this works only when user taps the button at the end of the checkout. But what about when the user just navigates back?

**Comment by vlonjatg** [comment]
Apparently `buyClient.getCheckoutCompletionStatus(checkout.getToken)...` in `onResume` does the work.

**Comment by krisorr** [comment]
@vlonjatg - that is right.  You will need to check the status on return to the app using `buyClient.getCheckoutCompletionStatus(..) if the web return to url is not used.
