### ISSUE TITLE
unable to fetch multiple product from productIds

### ISSUE THREAD

**Issue by Amit-Nandwana** [Shopify/mobile-buy-sdk-android#354]
I have 80 product ids to fetch product using **getProduct(Long productId, Callback<Product> callback)** this function but it returns only 50 products. 
Can you tell me how to fetch all 80 products.

**Comment by krisorr** [comment]
Hi @Amit-Nandwana 

This would be a great question to post on https://ecommerce.shopify.com/c/shopify-apis-and-technology, and I would encourage you to ask similar questions there in the future.    

If you are using `CancellableTask getProducts(List<Long> productIds, Callback<List<Product>> callback);` you will be limited to the page size set on the BuyClient.

I would suggest that you break your list of ids into groups smaller than the page size, and make multiple calls.
