### ISSUE TITLE
Unable to update country and state for users address.

### ISSUE THREAD

**Issue by MeNiks** [Shopify/mobile-buy-sdk-android#358]
For updating users address we use following method :
`buyClient.updateAddress();`
all the fields of address are getting updated except  for province & country.

But for ios sdk we are using this method which is working fine for updating address:
`- (NSOperation *)updateAddress:(BUYAddress *)address callback:(BUYDataAddressBlock)block;`

Can you please tell us whats wrong.

**Comment by MeNiks** [comment]
Changed title

**Comment by sav007** [comment]
2.x is no longer maintained. New version 3.0 has been released. Closing.
