### ISSUE TITLE
Cannot add notes after checkout creation

### ISSUE THREAD

**Issue by mruffa** [Shopify/mobile-buy-sdk-android#359]
Hi everyone.

So I create Shopify checkout and after I'm trying to update checkout with Notes. ("checkout.setNote()").

`ShopifyCheckout shopifyCheckout = new ShopifyCheckout();
        shopifyCheckout.getCheckout(client, new ShopifyCheckout.CheckoutListener() {
            @Override
            public void success(Checkout checkout) {
                checkout.setNote("asdasdad 1211111  555555");
//HERE CHECKOUT IS WITH NOTE
                Log.i("Nameplate desc", "checkout note " + checkout.getNote());

                client.updateCheckout(checkout, new Callback<Checkout>() {
                    @Override
                    public void success(Checkout newCheckout) {
                        //HERE CHECKOUT IS WITHOUT NOTE
                        Log.i("Nameplate desc", "lines updated: " + newCheckout.getNote());
                    }

                    @Override
                    public void failure(BuyClientError error) {
                        Log.i("Nameplate desc", "lines not updated: ");
                    }
                });

            }

            @Override
            public void fail(BuyClientError error) {
                Log.i("ChooseNameplate", "cart not updated: ");
            }
        });`

However setNote() doesn't influence notes. Is it because SDK doesn't allow it or I'm doing something wrong? :)

**Comment by sav007** [comment]
2.x is no longer maintained. New version 3.0 has been released. Closing.
