### ISSUE TITLE
Android Pay Helper assumes all items have shipping

### ISSUE THREAD

**Issue by krisorr** [Shopify/mobile-buy-sdk-android#365]
The isCheckoutUpdateRequired() in the AndroidPayHelper assumes that you will always get a shipping address back from the Android Pay Wallet.  This is not always true, if shipping is not required on any items in the checkout, the shipping address will not be returned.

**Comment by fananta** [comment]
@krisorr can you plz confirm?

**Comment by sav007** [comment]
Android Pay is deprecated.
