### ISSUE TITLE
completeCheckout for free payment not working 

### ISSUE THREAD

**Issue by gauravdroid** [Shopify/mobile-buy-sdk-android#368]
completeCheckout for free payment not working
getting this error
{
  "errors": {
    "checkout": {
      "payment_gateway": [
        {
          "code": "invalid",
          "message": "is invalid",
          "options": {}
        }
      ]
    }
  }
}

POST body is empty in sending request

**Comment by sav007** [comment]
2.x is no longer maintained. New version 3.0 has been released. Closing.
