### ISSUE TITLE
CustomTabsHelper is broken if Chrome is NOT the default browser

### ISSUE THREAD

**Issue by vit001** [Shopify/mobile-buy-sdk-android#376]
com.shopify.buy.customTabs.CustomTabsHelper intends to look for all apps that can handle VIEW intents:
```
// Get all apps that can handle VIEW intents
List<ResolveInfo> resolvedActivityList = pm.queryIntentActivities( activityIntent, 0 );
```
However, passing 0 will NOT return Chrome if the user has selected a different browser as the default (ie Firefox). Since Firefox doesn't handle Custom Tabs, this means Custom Tabs  won't work for such users, even if they have Chrome installed. Fix:
```
// Get all apps that can handle VIEW intents
List<ResolveInfo> resolvedActivityList = pm.queryIntentActivities( activityIntent, PackageManager.MATCH_ALL );
```

**Comment by sav007** [comment]
2.x is no longer maintained. New version 3.0 has been released. Closing.
