### ISSUE TITLE
Google Wallet or AndroidPay

### ISSUE THREAD

**Issue by pconno** [Shopify/mobile-buy-sdk-android#38]
I've updated my app to adhere to the requirements for viewing using Google Wallet. I'm not seeing Google wallet as a checkout option. Additionally, I don't see any support in the codebase for Android Pay. Is that in the roadmap? I also searched the codebase for references to Google Wallet and Android Pay and didn't see either. Is Google Wallet no longer supported by you?

**Comment by bgulanowski** [comment]
My understanding is that Google Wallet is at end-of-life. Android Pay is coming! No date yet, but it should be in scope for Android Buy SDK 2.0.

@krisorr if you have more details.

**Comment by krisorr** [comment]
@bgulanowski is correct.  
Google Wallet has been discontinued by Google, and is no longer supported.
We have Android Pay support coming soon.
