### ISSUE TITLE
Issue in setting discount coupon to checkout

### ISSUE THREAD

**Issue by MeNiks** [Shopify/mobile-buy-sdk-android#383]
We have a app in which we are not able to set discount coupon.
The way in which we are proceeding for checkout is as below:
1. createAddresses()
2. setShippingRate()
3. setDiscountCode()

When we call setDiscountCode() we are getting this response:

> {
>   "errors": {
>     "checkout": {
>       "shipping_rate_id": [{
>         "code": "invalid",
>         "message": "is invalid",
>         "options": {}
>       }],
>       "shipping_rate": {
>         "id": [{
>           "code": "invalid",
>           "message": "is invalid",
>           "options": {}
>         }]
>       },
>       "line_items": []
>     }
>   }
> }

But using the same bunch of sequence our 2 and more apps are running with no issue. Only for this store we are getting this response.
Store Url : [baileys-blossoms.myshopify.com](baileys-blossoms.myshopify.com)

We have already gone through this [issue already reported on shopify forums ](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/android-sdk-issue-setbillingaddress-after-applydiscount-311466)and tried this solution .But the issue is even i am setting shipping address null to checkout by using below call :

`checkout.setShippingRate(null);`

 from callback received from the api call  shipping rate is getting added to checkout.

**Comment by sav007** [comment]
2.x is no longer maintained. New version 3.0 has been released. Closing.
