### ISSUE TITLE
Any way to sync local cart with server cart for a specific customer ?

### ISSUE THREAD

**Issue by zayfal** [Shopify/mobile-buy-sdk-android#402]
I find no simple api to retrieve or save the cart. In the current version of the api, what is the best approach to achieve this  ?

**Comment by sav007** [comment]
@zayfal BuySDK doesn't provide API for dealing with cart for the moment. The way how you can do it is to use `Checkout`. So treat checkout object as your cart, and these mutation queries can help you to update it:

- `checkoutLineItemsAdd`
- `checkoutLineItemsRemove`
- `checkoutLineItemsUpdate`
- `checkoutAttributesUpdate`

The only downside of using `Checkout` object for the cart is you must store its `ID` to fetch it and make any changes.

**Comment by zayfal** [comment]
It doesn't provide a way to "sync" with a cart on website, a customer can't load his cart on the mobile version app, and finish the checkout mobile way.
I think retrieving and manipulation for a cart is basic functionality, why provide a customer register and login api, if the customer can't get his data (cart) from the data store ?

**Comment by sav007** [comment]
@zayfal thank you for your feedback, the issue has been created for our API team, I'll keep you posted about the status.

https://github.com/Shopify/shopify/issues/120186

**Comment by zayfal** [comment]
[The link ](https://github.com/Shopify/shopify/issues/120186) is not accessible.

**Comment by rebeccajfriedman** [comment]
Unfortunately, the cart you create using the Online Store is different from the cart you create using the SDK. It is not possible to sync them at this time.
