### ISSUE TITLE
Use with Android Studio 3.0 Canary 4

### ISSUE THREAD

**Issue by bhavinwebdesk** [Shopify/mobile-buy-sdk-android#403]
Hello Guys,

Can you guide me how to use it with new way of dependencies?

I tried with:
 api "com.shopify.mobilebuysdk:buy3:3.0.0"
 api "com.shopify.mobilebuysdk:buy3-pay-support:1.0.0" 

but it fails when [this](https://github.com/Shopify/mobile-buy-sdk-android/blob/6b614e04fd4e230f46e4f040df467fb40954b795/MobileBuy/sample/src/main/java/com/shopify/sample/view/cart/CartActivity.java#L81) is called.

Here by I attach by crashlog if it is useful.

[crashlog](http://crashes.to/s/321c6212a0a)

Thanks,
Bhavin

**Comment by sav007** [comment]
Thanks for the reporting the issue, we investigating it now.
But for now as workaround try to use AS 2.3.
