### ISSUE TITLE
checkoutCustomerAssociate is not working!

### ISSUE THREAD

**Issue by Siducati2** [Shopify/mobile-buy-sdk-android#404]
I created a checkout through 
> checkoutCreate(CheckoutCreateInput input, CheckoutCreatePayloadQueryDefinition queryDef)

and got the checkout Id  and weburl and pass this checkout id  with customeraccesstoken to 

> checkoutCustomerAssociate(ID checkoutId, String customerAccessToken, CheckoutCustomerAssociatePayloadQueryDefinition queryDef) 

but its asking for login on weburl again even after i have associated the checkout with customer
explain me the process if i am wrong.

**Comment by sav007** [comment]
There was an issue with `checkoutCustomerAssociate` mutation query that has been fixed by now, could you please give it a try.

**Comment by SudhanshShah** [comment]
Its still not working can you re-check for this

**Comment by SudhanshShah** [comment]
NO update on this from past 3 months ?

**Comment by Midhilaj** [comment]
@SudhanshShah  can you please share the code?

**Comment by Midhilaj** [comment]
Its still working

**Comment by spidy18** [comment]
Can anybody mail me the project . I have downloaded sdk but it wasn’t working because some file has been corrupted.

**Comment by wrg-mujeeb** [comment]
I am also having the same issue.

**Comment by rubenpa** [comment]
Is there a fix for this?

**Comment by grungkers** [comment]
not working in my project also, it always redirect to login page. if logged in user is needed I believe related to cookie _secure_session_id.

**Comment by yaxhpal** [comment]
@Midhilaj @grungkers - Did you guys resolved this? I am trying to do this in following way 

```java
public static void associateCustomer(ID checkoutId, String customerAccessToken, final Context context) {       
    Storefront.MutationQuery mutationQuery = Storefront.mutation(mutation -> mutation
                .checkoutCustomerAssociate(checkoutId, customerAccessToken, query -> query
                        .checkout(Storefront.CheckoutQuery::webUrl)
                        .userErrors(userError -> userError
                                .field()
                                .message()
                        )
                )
        );
        SampleApplication.graphClient().mutateGraph(mutationQuery).enqueue(new GraphCall.Callback<Storefront.Mutation>() {
            @Override
            public void onResponse(@NonNull GraphResponse<Storefront.Mutation> response) {
                if (!response.hasErrors() && response.data() != null) {
                    Storefront.Checkout checkout = response.data().getCheckoutCustomerAssociate().getCheckout();
                    Log.d(TAG, "Web checkout Url: " + checkout.getWebUrl());
                    Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(checkout.getWebUrl()));
                    context.startActivity(intent);
                } else {
                    Log.d(TAG, response.formatErrorMessage());
                }
            }

            @Override
            public void onFailure(@NonNull GraphError error) {
                Log.e(TAG, "There was an error while launching web checkout.", error);
            }
        });
    }
```
But this doesn't maintain customer session on launching of web checkout page.
