### ISSUE TITLE
While Running Buy Sdk Sample

### ISSUE THREAD

**Issue by kashifiqbal112** [Shopify/mobile-buy-sdk-android#414]
when running buy sdk sample project i got many error's like one below please if some one help i am stuck there

not resolve import com.shopify.graphql.support.AbstractResponse;

**Comment by markj** [comment]
You haven't got the grapql submodule checked out.

Once you've cloned from git you also need to do a recursive submodule update.
e.g.

`git submodule update --init --recursive`

**Comment by kashifiqbal112** [comment]
i do git submodule update --init --recursive butt got below error

--recursive
Cloning into 'MobileBuy/libs/graphql_java_gen'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Shopify/graphql_java_gen.git' into submodule path 'MobileBuy/libs/graphql_java_gen' failed

**Comment by markj** [comment]
It'll not be a permanent fix for the submodule permission problem you've got.. but if you just want to build the sample app and test things out.  You can download the source for the graphql module directly from https://github.com/Shopify/graphql_java_gen/tree/119255a619fef374bec80b0cf675718a1fadf423

Download the zip and extract it into:
`MobileBuy/libs/graphql_java_gen`

**Comment by kashifiqbal112** [comment]
okay now all things setup butt i got another error on Build.config file got Error on <ENVIRONMENT_TEST OR ENVIRONMENT_Production> not resolve

**Comment by markj** [comment]
I _think_ you might have taken Shopify's readme a bit to literally.

In your shop.properties file you want to have either:
`ANDROID_PAY_ENVIRONMENT=com.google.android.gms.wallet.WalletConstants.ENVIRONMENT_TEST`
or
`ANDROID_PAY_ENVIRONMENT=com.google.android.gms.wallet.WalletConstants. ENVIRONMENT_PRODUCTION `

Most likely the first one if you're just playing with the sample app - so you don't actually take any money from the card.

**Comment by sav007** [comment]
@kashifiqbal112 the comment pointed by @markj is absolutely correct, you have to provide one of 2 options: 
`com.google.android.gms.wallet.WalletConstants.ENVIRONMENT_TEST`
OR 
`com.google.android.gms.wallet.WalletConstants. ENVIRONMENT_PRODUCTION`

**Comment by sav007** [comment]
@markj do you see the same issue with `git submodule update --init --recursive` ?

**Comment by loveydhillon** [comment]
@markj 
![gradle](https://user-images.githubusercontent.com/21167147/29505660-387a169e-8665-11e7-9ab8-51143ad92429.png)

I am trying to run mobile-buy-sdk-android Sample, But i am getting following issue.
Please help.

Error:(3, 0) Could not get unknown property 'dep' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by sav007** [comment]
the last comment was addressed in #430
