### ISSUE TITLE
New to this "Where do I start?"

### ISSUE THREAD

**Issue by lux2be** [Shopify/mobile-buy-sdk-android#415]
I want to open up a Sales Channel using the Mobile App on Shopify. Shopify states add a few lines of code and your store is connected to your app. They make it sound easy but I don't know where to start. I have downloaded Android Studio now what?

**Comment by sav007** [comment]
The generic steps are:
1. create shop
2. add mobile app channel
3. use sdk to create a native shop application

For more details how to set-up shop and set-up mobile channel ask in https://ecommerce.shopify.com/forums
