### ISSUE TITLE
Translate strings which are a part of the Mobile Buy SDK

### ISSUE THREAD

**Issue by AkashDoshi19** [Shopify/mobile-buy-sdk-android#419]
Hi,

We have integrated with the Shopify Mobile Buy SDK(2.1.0) to enable native check out for our customers. We have some customers who want the app in different languages such as Spanish, Italian etc. 
However, there are some strings which are a part of the Shopify Mobile Buy SDK which show up on the app 
eg 1. We have sent an email to <Email>, please click the link included to verify your email address
     2. Email has already been taken

Can you please tell us how we can translate this to a different language?

**Comment by sav007** [comment]
Unfortunately SDK 2.x is not supported any more.
You should migrate to new version 3.0
