### ISSUE TITLE
Get All collections 

### ISSUE THREAD

**Issue by kashifiqbal112** [Shopify/mobile-buy-sdk-android#424]
dear 
i have a question is there is a way to get all collections from shop without specify the number of collection . for example i need all collection and product in one call and save in storeFront list  Thanks 
Regards 
Kashif

**Comment by sav007** [comment]
SDK doesn't provide such API due to the couple reasons, one of them is timeout for the request. The max page size that we support is 250. If this is not enough you have use pagination and collect items on the client side.
