### ISSUE TITLE
Unable to generate sample APK, Missing com.apollographql.apollo.api

### ISSUE THREAD

**Issue by tittuonnet** [Shopify/mobile-buy-sdk-android#426]
Unable to generate sample apk file, package com.apollographql.apollo.api is missing.
apply plugin: 'com.apollographql.android' is already present in the gradl file.

<img width="1131" alt="screen shot 2017-08-16 at 5 58 45 am" src="https://user-images.githubusercontent.com/2311294/29342382-1932f9ac-8248-11e7-8cbd-f3a953832eec.png">

**Comment by tittuonnet** [comment]
Another error found.
Error:Execution failed for task ':sample:transformClassesWithDexForShopifyDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/shopify/graphql/support/AbstractResponse;

**Comment by henrytao-me** [comment]
@tittuonnet can you try to do `Clean project` and rebuild sample app? I believe it should work.

**Comment by tittuonnet** [comment]
@henrytao-me I tried it. But getting the same error.

Error:Execution failed for task ':sample:transformClassesWithDexForShopifyDebug'.
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/shopify/graphql/support/AbstractResponse;

<img width="1231" alt="screen shot 2017-08-16 at 6 29 48 pm" src="https://user-images.githubusercontent.com/2311294/29364433-045434f6-82b1-11e7-81d0-bf9d6366209c.png">
<img width="1109" alt="screen shot 2017-08-16 at 6 28 31 pm" src="https://user-images.githubusercontent.com/2311294/29364434-04568b02-82b1-11e7-87e1-da2d319deca0.png">

**Comment by henrytao-me** [comment]
Would you please post all steps that you did here?
