### ISSUE TITLE
Unknown Property dep

### ISSUE THREAD

**Issue by loveydhillon** [Shopify/mobile-buy-sdk-android#430]
@henrytao-me 
@edward @tobi  @methodmissing @mulder @kevinfinlayson 
 I am trying to run mobile-buy-sdk-android Sample, But i am getting following issue.
Please help.

Error:(3, 0) Could not get unknown property 'dep' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
![gradle](https://user-images.githubusercontent.com/21167147/29451504-920c3d96-8420-11e7-959d-9c610fd4bb8f.png)

**Comment by sav007** [comment]
Sample Application is a part of SDK,  it's a gradle submodule.
If you open the `build.gradle` for sample application, you will find these:
```
compile project(':buy3-pay-support')
shopifyCompile project(':buy3')
```
That tells this module depends on other modules (`:buy3` and ':buy3-pay-support').

You should import the whole SDK into AS not just sample module.
