### ISSUE TITLE
Failed to clone 'MobileBuy/libs/graphql_java_gen'.

### ISSUE THREAD

**Issue by vishnumm93** [Shopify/mobile-buy-sdk-android#431]
![screenshot 58](https://user-images.githubusercontent.com/7579176/29457643-e5d0e130-8438-11e7-9664-63d361311b64.png)

I am not able to clone the sample application provided. I have already added ssh keys to my profile.

**Comment by sav007** [comment]
Seems the issue with `Host key verification`:
https://askubuntu.com/questions/45679/ssh-connection-problem-with-host-key-verification-failed-error

You should reset your ssh key.
