### ISSUE TITLE
Fetch Shop Name Issue

### ISSUE THREAD

**Issue by loveydhillon** [Shopify/mobile-buy-sdk-android#432]
@henrytao-me
@HendrikBreuer @tobi @methodmissing @kevinfinlayson 
Here is My Sample Code

![screenshot from 2017-08-15 10 56 10](https://user-images.githubusercontent.com/21167147/29505796-f79781ec-8665-11e7-95ed-f75823ca83ed.png)

I am getting Crash while runnig this piece of code i.e

![crash](https://user-images.githubusercontent.com/21167147/29505846-4362b538-8666-11e7-8a9c-541dbdeb7593.png)

**Comment by sav007** [comment]
It's a duplication of #430 

You should import the whole SDK into AS not just sample module.

**Comment by Joyliu290** [comment]
I've experienced the same issue while trying to code and run my own app. Could you please elaborate on how to solve this issue?
