### ISSUE TITLE
Urgent Help: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to Variable class(@SerializeName) using Retorfit

### ISSUE THREAD

**Issue by masheransari** [Shopify/mobile-buy-sdk-android#435]
Call<ResponseVar> call = api.getAuthRequest(requestAuth);  
                          Log.e("URL", call.request().url().toString());
                            call.enqueue(new Callback<ResponseVar>() {
                                @Override
                                public void onResponse(Call<ResponseVar> call, Response<ResponseVar> response) {
                                    ResponseVar responseVar = response.body();
                                    User user1 = (User) responseVar.data;
                                    Toast.makeText(getActivity(), "" + user1.email, Toast.LENGTH_SHORT).show();
                                    if (response.isSuccessful()) {
                                        mProgressBar.setVisibility(View.GONE);
                                    } else {
                                        mProgressBar.setVisibility(View.GONE);
                                        Toast.makeText(getActivity(), "Network Connection Failed..!!", Toast.LENGTH_SHORT).show();
                                    }
                                }
                                @Override
                                public void onFailure(Call<ResponseVar> call, Throwable t) {
                                    call.cancel();
                                }

How can i fix this issue ASAP.

**Comment by sav007** [comment]
Is this issue related to the SDK 3.0 ?
