### ISSUE TITLE
How to set tags for customer at the time of registration?

### ISSUE THREAD

**Issue by urvish91** [Shopify/mobile-buy-sdk-android#438]
Hello team, I am new to Android mobile buy sdk and following your readme. For development can you please let me know how to set tags for customer as wholesaler or retailer at the time of registration?

**Comment by sav007** [comment]
Currently we don't expose  any tags or notes associated with the customer due to the security reason. Not sure if this will help there is  a `company` field in `MailingAddressInput` for `customerAddressCreate` mutation.

Could you please provide a use case where you need these fields?

**Comment by urvish91** [comment]
Actually in our website, we are using this field for registration, and now we are creating an android app for the same website. so at the time of registration we want to use that field. that's why we need it.
