### ISSUE TITLE
Erro compile sample apk

### ISSUE THREAD

**Issue by fernandodeveloper** [Shopify/mobile-buy-sdk-android#441]
I got this error on compile to shopify debug 

C:\Users\Thiago\Downloads\2\mobile-buy-sdk-android\MobileBuy\sample\build\generated\source\apollo\com\shopify\sample\domain\CheckoutByIdQuery.java
Error:(3, 36) error: **package com.apollographql.apollo.api does not exist**

**Comment by henrytao-me** [comment]
Please do clean build. It should work.

**Comment by tmachinya** [comment]
Error:(3, 36) error: package com.apollographql.apollo.api does not exist. I am getting the same error. Clean and build did not work for me
