### ISSUE TITLE
search query for product returning 0 edges

### ISSUE THREAD

**Issue by droidAadi** [Shopify/mobile-buy-sdk-android#447]
I am trying to search a product using the following query, but it is always returning 0 edges, even though the product with mentioned args(args.query("tabs") is present.

Generated Query:

{
  shop{
    products(first: 1, query: "tabs"){
      edges{
        node{
          id,
          title,
          description
        }
      }
    }
  }
}

Sample code for query:
        Storefront.QueryRootQuery searchQuery = Storefront.query(new Storefront.QueryRootQueryDefinition() {
            @Override
            public void define(final Storefront.QueryRootQuery rootQueryBuilder) {
                rootQueryBuilder.shop(new Storefront.ShopQueryDefinition() {
                    @Override
                    public void define(final Storefront.ShopQuery shopQueryBuilder) {
                        shopQueryBuilder.products(1, new Storefront.ShopQuery.ProductsArgumentsDefinition() {
                            @Override
                            public void define(Storefront.ShopQuery.ProductsArguments args) {
                                args.query("tabs");
                            }
                        }, new Storefront.ProductConnectionQueryDefinition() {
                            @Override
                            public void define(Storefront.ProductConnectionQuery productConnectionQuery) {
                                productConnectionQuery.edges(new Storefront.ProductEdgeQueryDefinition() {
                                    @Override
                                    public void define(Storefront.ProductEdgeQuery productEdgeQuery) {
                                        productEdgeQuery.node(new Storefront.ProductQueryDefinition() {
                                            @Override
                                            public void define(Storefront.ProductQuery productQuery) {
                                                productQuery.title().description();
                                            }
                                        });
                                    }
                                });
                            }
                        });

                    }
                });
            }
        });

**Comment by droidAadi** [comment]
Can anyone please suggest some pointers regarding the above issue? It is blocking my development for search functionality.

**Comment by sav007** [comment]
Could you please provide what shop are you trying on?

**Comment by droidAadi** [comment]
Shop is www.kaer.in
Also, I observed 1 more thing,  when I am entering the exact name of the product, then I am getting the result. But, if I am entering just a part of it, I am not getting any result. For eg., I queried 1000 PARA TAB'S 12'S, i got the result. But when I queried "PARA", I am not getting any results.

**Comment by sav007** [comment]
> It seems, the products were not enabled for Mobile App Channel.It is working now.

great.

> What value should I enter that returns all the relevant products with the matching String query?

Any list is paginated, there is no such value that gives you all products, the maximum that we support is 250. But is there any valid use case where you need so many products? If you think from UI perspective not sure that user will look over all 250 products.

**Comment by droidAadi** [comment]
Yes the list is paginated, but then is there a way to specify the limit? Let say, i initially opted for 10 products at a time, then if user wants to see more result, then how can I make the API call to fetch next 10 items? Is there any provision to support it, like providing the range for next 10 items in search result?
