### ISSUE TITLE
Error:Cannot get property 'destinationDir' on null object

### ISSUE THREAD

**Issue by KavithaAnandan** [Shopify/mobile-buy-sdk-android#452]
when i try to add retro lambda this error is coming ..Can some one help on this..

**Comment by henrytao-me** [comment]
Can you send your stacktrace here? Having More information about your build is appreciate.

**Comment by sav007** [comment]
As well could you please provide the build.gradle that you have

**Comment by sav007** [comment]
Closing due inactivity.
