### ISSUE TITLE
mobile buy sdk how can I place order after payment done via payumoney 

### ISSUE THREAD

**Issue by obabujiApp** [Shopify/mobile-buy-sdk-android#467]
hello,
I have successful done create checkout . I want to receive payments directly through payUMoney and after successful payment how can I convert this checkout to an order.

**Comment by obabujiApp** [comment]
please reply

**Comment by sav007** [comment]
Probably you are looking for `com.shopify.buy3.Storefront.MutationQuery#checkoutCompleteFree` mutation.

**Comment by obabujiApp** [comment]
Yes I am looking for com.shopify.buy3.Storefront.MutationQuery#checkoutCompleteFree mutation. but it  give me error payment required for this checkout. how I can associate this checkout to payment done via  payment gateway payUmoney.

**Comment by sav007** [comment]
In order to run mutation `checkoutCompleteFree` all line items added to checkout must have $0 price. Otherwise you can't just complete any checkout with outstanding payment.

**Comment by obabujiApp** [comment]
Leave 'checkoutCompleteFre' .
Can you tell me step by step one thing How to make payment of particular checkout via external provider payU India and complete checkout.
Currently i am using below code for payment via PayUMoney 
public void makePayment(double amount) {
     String phone = "8817766123";;
    String productName = "prodecut name";
     String firstName = "satish";
    String txnId = "0nf7" + System.currentTimeMillis();
     String email="satish@gmail.com";
    String sUrl = "https://test.payumoney.com/mobileapp/payumoney/success.php";
    String fUrl = "https://test.payumoney.com/mobileapp/payumoney/failure.php";
    String udf1 = "";
    String udf2 = "";
    String udf3 = "";
    String udf4 = "";
    String udf5 = "";
    boolean isDebug = false;
    String key = "BxMVyv"; 
    String merchantId = "4938302";
    PayUmoneySdkInitilizer.PaymentParam.Builder builder = new PayUmoneySdkInitilizer.PaymentParam.Builder();

    builder.setAmount(amount)
            .setTnxId(txnId)
            .setPhone(phone)
            .setProductName(productName)
            .setFirstName(firstName)
            .setEmail(email)
            .setsUrl(sUrl)
            .setfUrl(fUrl)
            .setUdf1(udf1)
            .setUdf2(udf2)
            .setUdf3(udf3)
            .setUdf4(udf4)
            .setUdf5(udf5)
            .setIsDebug(isDebug)
            .setKey(key)
            .setMerchantId(merchantId);

    PayUmoneySdkInitilizer.PaymentParam paymentParam = builder.build();

    String salt = "BZpFsWdu";

    String serverCalculatedHash = hashCal(key+"|"+txnId+"|"+amount+"|"+productName+"|"
            +firstName+"|"+email+"|"+udf1+"|"+udf2+"|"+udf3+"|"+udf4+"|"+udf5+"|"+salt);

    paymentParam.setMerchantHash(serverCalculatedHash);

    Log.e("shopify","shopify serverCalculatedHash=> "+serverCalculatedHash);

    PayUmoneySdkInitilizer.startPaymentActivityForResult(CartActivity.this, paymentParam);

  }

  public static String hashCal(String str) {

    byte[] hashseq = str.getBytes();

    StringBuilder hexString = new StringBuilder();

    try {

      MessageDigest algorithm = MessageDigest.getInstance("SHA-512");
      algorithm.reset();
      algorithm.update(hashseq);
      byte messageDigest[] = algorithm.digest();

      for (byte aMessageDigest : messageDigest) {

        String hex = Integer.toHexString(0xFF & aMessageDigest);

        if (hex.length() == 1) {
          hexString.append("0");
        }

        hexString.append(hex);
      }

    } catch (NoSuchAlgorithmException ignored) {

    }

    return hexString.toString();
  }

**Comment by sav007** [comment]
No you can't complete checkout with some external payment gateway that not supported by Shopify.
