### ISSUE TITLE
Gradle DSL method not found: 'compile()'

### ISSUE THREAD

**Issue by Midhilaj** [Shopify/mobile-buy-sdk-android#469]
How to solve this issue?
Error:(100, 0) Gradle DSL method not found: 'compile()'
Possible causes:<ul><li>The project 'sample' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Upgrade plugin to version 2.3.3 and sync project</a></li><li>The project 'sample' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

**Comment by sav007** [comment]
what Android Studio version you have?

**Comment by Midhilaj** [comment]
2.3.3

**Comment by sav007** [comment]
Something is wrong how you setup the project, if you run in the terminal `./gradlew :sample:assembleShopifyDebug` do you see the same errors?
