### ISSUE TITLE
error: package com.shopify.graphql.support does not exist

### ISSUE THREAD

**Issue by Midhilaj** [Shopify/mobile-buy-sdk-android#470]
Information:Gradle tasks [:sample:assembleShopifyDebug]
Information:0 errors
Information:0 warnings
Information:See complete output in console
/project/mobile-buy-sdk-android-master (2)/MobileBuy/buy3/src/main/java/com/shopify/buy3/GraphResponse.java
Error:(30, 35) error: package com.shopify.graphql.support does not exist
Error:(31, 35) error: package com.shopify.graphql.support does not exist
Error:(44, 44) error: cannot find symbol class AbstractResponse
/project/mobile-buy-sdk-android-master (2)/MobileBuy/buy3/src/main/java/com/shopify/buy3/GraphCall.java
Error:(31, 35) error: package com.shopify.graphql.support does not exist
Error:(42, 38) error: cannot find symbol class AbstractResponse
Error:(117, 32) error: cannot find symbol class AbstractResponse
where T is a type-variable:
T declared in interface GraphCall
/project/mobile-buy-sdk-android-master (2)/MobileBuy/buy3/src/main/java/com/shopify/buy3/RetryHandler.java
Error:(29, 35) error: package com.shopify.graphql.support does not exist
/project/mobile-buy-sdk-android-master (2)/MobileBuy/buy3/src/main/java/com/shopify/buy3/Storefront.java
Error:(9, 35) error: package com.shopify.graphql.support does not exist
Error:(10, 35) error: package com.shopify.graphql.support does not exist
Error:(11, 35) error: package com.shopify.graphql.support does not exist
Error:(12, 35) error: package com.shopify.graphql.support does not exist
Error:(13, 35) error: package com.shopify.graphql.support does not exist
Error:(14, 35) error: package com.shopify.graphql.support does not exist
Error:(15, 35) error: package com.shopify.graphql.support does not exist
Error:(17, 35) error: package com.shopify.graphql.support does not exist
Error:(18006, 42) error: cannot find symbol class AbstractResponse
Error:(23408, 48) error: cannot find symbol class Query
Error:(17403, 47) error: cannot find symbol class Query
Error:(18010, 51) error: cannot find symbol class SchemaViolationError
Error:(3401, 65) error: cannot find symbol class AbstractResponse
Error:(3515, 61) error: cannot find symbol class AbstractResponse
Error:(3647, 71) error: cannot find symbol class AbstractResponse
Error:(3800, 77) error: cannot find symbol class AbstractResponse
Error:(4169, 55) error: cannot find symbol class AbstractResponse
Error:(4288, 66) error: cannot find symbol class AbstractResponse
Error:(4402, 69) error: cannot find symbol class AbstractResponse
Error:(4516, 66) error: cannot find symbol class AbstractResponse
Error:(4630, 60) error: cannot find symbol class AbstractResponse
Error:(4744, 62) error: cannot find symbol class AbstractResponse
Error:(4858, 63) error: cannot find symbol class AbstractResponse
Error:(5641, 61) error: cannot find symbol class AbstractResponse
Error:(5757, 64) error: cannot find symbol class AbstractResponse
Error:(5872, 64) error: cannot find symbol class AbstractResponse
Error:(5991, 70) error: cannot find symbol class AbstractResponse
Error:(6105, 67) error: cannot find symbol class AbstractResponse
Error:(13691, 66) error: cannot find symbol class AbstractResponse
Error:(13815, 66) error: cannot find symbol class AbstractResponse
Error:(13960, 65) error: cannot find symbol class AbstractResponse
Error:(14126, 57) error: cannot find symbol class AbstractResponse
Error:(14245, 62) error: cannot find symbol class AbstractResponse
Error:(14360, 62) error: cannot find symbol class AbstractResponse
Error:(14479, 62) error: cannot find symbol class AbstractResponse
Error:(14781, 55) error: cannot find symbol class AbstractResponse
Error:(14900, 69) error: cannot find symbol class AbstractResponse
Error:(15006, 56) error: cannot find symbol class AbstractResponse
Error:(15146, 54) error: cannot find symbol class AbstractResponse
Error:(15478, 55) error: cannot find symbol class AbstractResponse
Error:(23428, 36) error: cannot find symbol class ID
Error:(23443, 42) error: cannot find symbol class ID
Error:(17411, 55) error: cannot find symbol class ID
Error:(17429, 51) error: cannot find symbol class ID
Error:(17447, 61) error: cannot find symbol class ID
Error:(17468, 67) error: cannot find symbol class ID
Error:(17507, 56) error: cannot find symbol class ID
Error:(17528, 59) error: cannot find symbol class ID
Error:(17546, 77) error: cannot find symbol class ID
Error:(17567, 50) error: cannot find symbol class ID
Error:(17588, 73) error: cannot find symbol class ID
Error:(17609, 53) error: cannot find symbol class ID
Error:(17609, 75) error: cannot find symbol class ID
Error:(17630, 90) error: cannot find symbol class ID
Error:(17659, 54) error: cannot find symbol class ID
Error:(17659, 74) error: cannot find symbol class ID
Error:(17688, 54) error: cannot find symbol class ID
Error:(17717, 97) error: cannot find symbol class ID
Error:(17738, 57) error: cannot find symbol class ID
Error:(17814, 47) error: cannot find symbol class ID
Error:(17856, 52) error: cannot find symbol class ID
Error:(17877, 80) error: cannot find symbol class ID
Error:(17919, 87) error: cannot find symbol class ID
Error:(17958, 44) error: cannot find symbol class ID
Error:(3405, 74) error: cannot find symbol class SchemaViolationError
Error:(2638, 42) error: cannot find symbol class AbstractResponse
Error:(18884, 62) error: package com.shopify.graphql.support does not exist
Error:(25816, 43) error: cannot find symbol class AbstractResponse
Error:(3519, 70) error: cannot find symbol class SchemaViolationError
Error:(3651, 80) error: cannot find symbol class SchemaViolationError
Error:(20525, 41) error: cannot find symbol class AbstractResponse
Error:(3804, 86) error: cannot find symbol class SchemaViolationError
Error:(4173, 64) error: cannot find symbol class SchemaViolationError
Error:(4292, 75) error: cannot find symbol class SchemaViolationError
Error:(4406, 78) error: cannot find symbol class SchemaViolationError
Error:(4520, 75) error: cannot find symbol class SchemaViolationError
Error:(4634, 69) error: cannot find symbol class SchemaViolationError
Error:(4748, 71) error: cannot find symbol class SchemaViolationError
Error:(4862, 72) error: cannot find symbol class SchemaViolationError
Error:(5645, 70) error: cannot find symbol class SchemaViolationError
Error:(5761, 73) error: cannot find symbol class SchemaViolationError
Error:(5876, 73) error: cannot find symbol class SchemaViolationError
Error:(5995, 79) error: cannot find symbol class SchemaViolationError
Error:(6109, 76) error: cannot find symbol class SchemaViolationError
Error:(13695, 75) error: cannot find symbol class SchemaViolationError
Error:(13535, 53) error: cannot find symbol class AbstractResponse
Error:(13819, 75) error: cannot find symbol class SchemaViolationError
Error:(13964, 74) error: cannot find symbol class SchemaViolationError
Error:(14130, 66) error: cannot find symbol class SchemaViolationError
Error:(13191, 42) error: cannot find symbol class AbstractResponse
Error:(14249, 71) error: cannot find symbol class SchemaViolationError
Error:(16334, 48) error: cannot find symbol class AbstractResponse
Error:(14364, 71) error: cannot find symbol class SchemaViolationError
Error:Execution failed for task ':buy3:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 9.031 secs

**Comment by sav007** [comment]
Did you run `git submodule update --init --recursive`?

**Comment by Midhilaj** [comment]
git submodule update --init --recursivefatal: destination path 'MobileBuy/libs/graphql_java_gen' already exists and is not an empty directory.
Clone of 'git@github.com:Shopify/graphql_java_gen.git' into submodule path 'MobileBuy/libs/graphql_java_gen' failed

**Comment by sav007** [comment]
Try to remove existing project and then start over with git clone and git submodule init

**Comment by Ketuzzz** [comment]
@sav007 by removing an existing project and etc not working.
