### ISSUE TITLE
Could not get unknown property 'dep' for object of type 

### ISSUE THREAD

**Issue by Midhilaj** [Shopify/mobile-buy-sdk-android#471]
Error:(3, 0) Could not get unknown property 'dep' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
<a href="openFile:/project/mobile-buy-sdk-android-master/MobileBuy/sample/build.gradle">Open File</a>

**Comment by sav007** [comment]
This error probably related how you set-up the project in your env.
