### ISSUE TITLE
Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by Midhilaj** [Shopify/mobile-buy-sdk-android#472]
According to the document i tried to run <br>
 git submodule update --init --recursive <br>
in /MobileBuy/sample folder <br>
and it return "fatal: Not a git repository (or any of the parent directories): .git"

**Comment by sav007** [comment]
Did you clone the repo via git command?

**Comment by Midhilaj** [comment]
no

**Comment by sav007** [comment]
You have to use a git to clone the repository, and then run this command `git submodule update --init --recursive ` to download git submodule required to run sample app.
