### ISSUE TITLE
RetryHandler is not working 

### ISSUE THREAD

**Issue by yerramnaveen** [Shopify/mobile-buy-sdk-android#482]
RetryHandler.delay(5, TimeUnit.SECONDS)
                        .maxCount(5)
                        .<Storefront.QueryRoot>whenResponse(response -> ((Storefront.Checkout) response.data().getNode()).getOrder() == null)
                        .build())

It is not not recalling the execution

**Comment by yerramnaveen** [comment]
No .getOrder retuning null, If it is not null it will print orderid.

Could you check once what is wrong in the following code


Storefront.QueryRootQuery query = Storefront.query(rootQuery -> rootQuery
                .node(checkoutId, nodeQuery -> nodeQuery
                        .onCheckout(checkoutQuery -> checkoutQuery
                                .order(orderQuery -> orderQuery
                                        .orderNumber()
                                        .totalPrice()
                                )
                        )
                )
        );


        AtomicReference<GraphResponse<Storefront.QueryRoot>> graphResponse = new AtomicReference<>();
        AtomicReference<GraphError> graphError = new AtomicReference<>();


        GraphCall<Storefront.QueryRoot> call = graphClient.queryGraph(query);

        call.enqueue(
                new GraphCall.Callback<Storefront.QueryRoot>() {
                    @Override
                    public void onResponse(@NonNull GraphResponse<Storefront.QueryRoot> response) {
                        graphResponse.set(response);
                        Storefront.Checkout checkout = (Storefront.Checkout) response.data().getNode();
                        String orderId = checkout.getOrder().getId().toString();
                        Log.v("TAG", "OrderId: " + orderId);
                    }

                    @Override
                    public void onFailure(@NonNull GraphError error) {
                        graphError.set(error);
                        Log.v("TAG", "error: " + error.getMessage());
                    }
                },
                null,
                RetryHandler.delay(10, TimeUnit.SECONDS)
                        .maxCount(5)
                        .<Storefront.QueryRoot>whenResponse(response -> ((Storefront.Checkout) response.data().getNode()).getOrder() == null)
                        .build());

**Comment by sav007** [comment]
Just to clarify what do you mean by `It is not not recalling the execution`, did you enable and check the http logs?

**Comment by yerramnaveen** [comment]
Issue resolved
The issue was the following
While creating GraphClient.builder I removed the following code then it worked
.httpCache(new File(getApplicationContext().getCacheDir(), "/http"), 10 * 1024 * 1024) // 10mb for http cache
                // .defaultHttpCachePolicy(HttpCachePolicy.CACHE_FIRST.expireAfter(5, TimeUnit.MINUTES)) // cached response valid by default for 5 minutes

**Comment by sav007** [comment]
Oh, well you can disable the cache for specific query: https://github.com/Shopify/mobile-buy-sdk-android#caching-

**Comment by amanzan** [comment]
I have a similar issue but it is not solved removing cache lines...checkForCompletionQuery only runs once

```
        graphClient.queryGraph(checkForCompletionQuery).enqueue(
                new GraphCall.Callback<Storefront.QueryRoot>() {
                    @Override public void onResponse(@NonNull GraphResponse<Storefront.QueryRoot> response) {
                        if (response.data() != null && response.data().getNode() != null) {
                            Storefront.Checkout checkout = (Storefront.Checkout) response.data().getNode();
                            if (checkout.getOrder() != null) {
                                Log.d("shopify", "orderid = " +checkout.getOrder().getId());

                                finalizeCart(context);
                            } else {
                                Log.e("shopify", "checkForCompletionQuery Not ready yet....");
                            }
                        } else {
                            Log.e("shopify", "something went wrong....");

                            hideProgressBar(context);
                        }
                    }

                    @Override public void onFailure(@NonNull GraphError error) {
                        Log.e("shopify", "something went wrong...graphError : " + error);

                        hideProgressBar(context);
                    }
                },
                null,
                RetryHandler.exponentialBackoff(1, TimeUnit.MILLISECONDS, 1.2f)
                        .whenResponse(
                                response -> ((Storefront.Checkout) ((GraphResponse<Storefront.QueryRoot>) response).data().getNode()).getOrder() == null
                        )
                        .maxCount(20)
                        .build()
        );
```

**Comment by Meeks91** [comment]
This should be made much more clear as the caching mechanism can almost completely break the entire polling functionality.
