### ISSUE TITLE
Shopify sample app  error on release

### ISSUE THREAD

**Issue by Midhilaj** [Shopify/mobile-buy-sdk-android#486]
How to solve this problem
Error:Execution failed for task ':sample:transformClassesWithJarMergingForShopifyRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/arch/core/internal/SafeIterableMap$ListIterator.class
Warning:Supported source version 'RELEASE_7' from annotation processor 'android.arch.lifecycle.LifecycleProcessor' less than -source '1.8'

buildscript {
dependencies {
classpath dep.androidPlugin
classpath dep.retrolambda
classpath dep.butterknifePlugin
classpath dep.apolloPlugin
// google-services plugin
}
}

apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'com.apollographql.android'

android {
compileSdkVersion 26
buildToolsVersion "26.0.1"

defaultConfig {
applicationId "com.**"
minSdkVersion 19
targetSdkVersion 26
versionCode 1
versionName "1.0"
multiDexEnabled true
}

compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}

buildTypes {
all {
  buildConfigField 'okhttp3.logging.HttpLoggingInterceptor.Level', 'OKHTTP_LOG_LEVEL', 'okhttp3.logging.HttpLoggingInterceptor.Level.BODY'

  // We pull the shop settings either from the Environment or a file called shop.properties at the root of the project.
  // Environment variables will take precedence, we will attempt to read those first.
  def shopDomain
  def apiKey
  def androidPayPublicKey
  def androidPayEnvironment

  // get the shop setting from the environment if there any
  shopDomain = System.getenv("SHOP_DOMAIN")
  apiKey = System.getenv("API_KEY")
  androidPayPublicKey = System.getenv("ANDROID_PAY_PUBLIC_KEY")
  androidPayEnvironment = System.getenv("ANDROID_PAY_ENVIRONMENT")

  // pull the store properties from the local file if it exists.  Environment variables take precedence
  def shopProperties = new Properties();
  File shopPropertiesFile = project.file('shop.properties')

  if (shopPropertiesFile.exists()) {
    shopProperties.load(new FileInputStream(shopPropertiesFile))
    shopDomain = shopDomain ?: shopProperties["SHOP_DOMAIN"]
    apiKey = apiKey ?: shopProperties["API_KEY"]
    androidPayPublicKey = androidPayPublicKey ?: shopProperties["ANDROID_PAY_PUBLIC_KEY"]
    androidPayEnvironment = androidPayEnvironment ?: shopProperties["ANDROID_PAY_ENVIRONMENT"]
  }

  if (!shopDomain) {
    shopDomain = ""
  }
  if (!apiKey) {
    apiKey = ""
  }
  if (!androidPayPublicKey) {
    androidPayPublicKey = ""
  }
  if (!androidPayEnvironment) {
    androidPayEnvironment = "com.google.android.gms.wallet.WalletConstants.ENVIRONMENT_SANDBOX"
  }

  buildConfigField "String", "SHOP_DOMAIN", "\"" + shopDomain.toString() + "\""
  buildConfigField "String", "API_KEY", "\"" + apiKey.toString() + "\""
  buildConfigField "String", "ANDROID_PAY_PUBLIC_KEY", "\"" + androidPayPublicKey.toString() + "\""
  buildConfigField "int", "ANDROID_PAY_ENVIRONMENT", androidPayEnvironment

  debuggable = true
  minifyEnabled = false
}
}

productFlavors {
shopify {
}

xApollo {
}
}

lintOptions {
 abortOnError false
}
}
dependencies {
compile dep.androidSupportDesign
compile dep.androidSupportV4
compile dep.androidSupportV7
compile dep.androidSupportAnnotations
compile dep.rxAndroid
compile dep.rxJava
compile dep.timber
compile dep.butterKnife
annotationProcessor dep.butterKnifeCompiler
compile(dep.fresco) {
exclude group: 'com.android.support'
}
compile dep.constraintLayout
compile dep.rxrelay
compile dep.archRuntime
compile dep.archExt
annotationProcessor dep.arcCompiler
compile 'com.nineoldandroids:library:2.4.0'
compile 'com.android.support:appcompat-v7:26.+'
compile 'com.android.support:cardview-v7:26.+'
compile 'com.android.support:design:26.+'
compile 'de.hdodenhof:circleimageview:2.2.0'
compile 'com.daimajia.slider:library:1.1.5@aar'
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.android.support:multidex:1.0.1'
compile 'com.android.support:percent:26.+'
compile 'com.shopify.mobilebuysdk:buy3:3.1.1'
// optional library to help with Android Pay purchase flow
compile 'com.shopify.mobilebuysdk:buy3-pay-support:1.0.2'

xApolloCompile dep.apolloRuntime
xApolloCompile dep.okhttpLogging
xApolloCompile dep.apolloHttpCache
}

task downloadApolloSchema(type: DefaultTask, group: "GraphQL", description: "Download GraphQL store front API schema") {
doLast {
println("Downloading GraphQL schema...")
def schemaFile = new File(project.projectDir.absolutePath + '/src/xApollo/graphql/com/shopify/sample/domain/schema.json')
if (schemaFile.exists()) {
  schemaFile.delete()
}
new URL('https://app.shopify.com/services/ping/storefront_graphql_schema').withInputStream { i ->
  schemaFile.withOutputStream {
    it << i
  }
}
println("GraphQL schema has been downloaded!")
}
}

apollo {
customTypeMapping['URL'] = "String"
customTypeMapping['HTML'] = "String"
customTypeMapping['Money'] = "java.math.BigDecimal"
nullableValueType = "apolloOptional"
generateAccessors = false
useSemanticNaming = false
}

**Comment by henrytao-me** [comment]
Have you tried clean build?

**Comment by Midhilaj** [comment]
yes

**Comment by sav007** [comment]
Did you change smth in the build.gradle provided in sample app?

**Comment by henrytao-me** [comment]
He did. I think I will close this ticket for now.
