### ISSUE TITLE
Unable to update customer address 

### ISSUE THREAD

**Issue by yerramnaveen** [Shopify/mobile-buy-sdk-android#487]
When we try to update customer address 
using the following code:

```java
 Storefront.MutationQuery mutationQuery = Storefront.mutation(mutation -> mutation
                        .customerAddressUpdate(accessToken, customerId, inputMailiningAddress, query -> query
                                        .customerAddress(customerAddress -> customerAddress
                                                        .address1()
                                                        .address2()

// Response is Invalid Id

// Could you give more details on passing the ID 
// I am passing ID which is retrieved from the following query:

Storefront.QueryRootQuery query = Storefront.query(root -> root
                .customer(accessToken, customer -> customer
                        .firstName()
                        .lastName()
                        .email()
                        .id()
                )
        );
```

Could you tell the possible chances of Invalid Id scenarios

**Comment by sav007** [comment]
Are you sure that you passing the right `customerId`, and could you please show me the `customerId` value and the exact response message.

**Comment by yerramnaveen** [comment]
Customer Id:  Z2lkOi8vc2hvcGlmeS9DdXN0b21lci8yNTY3MTE3MjExNQ==
Error: invalid id

Storefront.MutationQuery mutationQuery = Storefront.mutation(mutation -> mutation
                .customerAddressUpdate(accessToken, customerId, inputMailiningAddress, query -> query
                        .customerAddress(customerAddress -> customerAddress
                                .address1()
                                .address2()

                        )
                        .userErrors(userErrorQuery -> userErrorQuery
                                .field()
                                .message()
                        )
                )
        );
        MutationGraphCall call = graphClient.mutateGraph(mutationQuery);
        call.enqueue(new GraphCall.Callback<Storefront.Mutation>() {
            @Override
            public void onResponse(@NonNull final GraphResponse<Storefront.Mutation> response) {
                int size = response.errors().size();
                for (int i = 0; i < size; i++) {
                    Log.v("TAG", "Error: " + response.errors().get(i).message());
                }
               
            }

            @Override
            public void onFailure(@NonNull final GraphError error) {
                Log.e("TAG", "Failed to execute query customer login", error);
            }
        });

**Comment by Networld301** [comment]
hello,  i am facing same problem in Address update. in this pass id in this  GraphQL.ID formate : GraphQL.ID(customer_id)
but GraphQL not resolve in Shopify androidSDK.

**Comment by bhavinwebdesk** [comment]
@sav007 what information do you need to investigate this?

**Comment by rebeccajfriedman** [comment]
The ID should not be the customer's ID - it should be the Address ID, as you mentioned above.

**Comment by faizanhaidarkhan** [comment]
@rebeccajfriedman Then how can I get Address ID. Because when I get shipping detail like this, it does not have .id() option available.

Storefront.query(root -> root
                .customer(accessToken, customer -> customer
                        .addresses(arg -> arg.first(10), connection -> connection
                                .edges(edge -> edge
                                        .node(node -> node
                                                .firstName()
                                                .lastName()
                                                .address1()
                                                .address2()
