### ISSUE TITLE
Retry handler values are misleading in "Shipping rates polling" and "Checkout polling" subsection in documentation

### ISSUE THREAD

**Issue by LukaBabic1** [Shopify/mobile-buy-sdk-android#488]
Values used for initializing retry handler in section "Shipping rates" are misleading. 1 millisecond as start value, 1.2 multiplicator and 10 retry counts are way too low to receive the desired response from Shopify.

Default values should be something like 500ms, multiplicator 1.3 and 12 times retry count so accumulated polling time is a couple dozen of seconds.

**Comment by henrytao-me** [comment]
Thanks for your feedback. We will update the docs. There are a lot of strategy using `RetryHandler` depending on each application. You may need to figure out the right value that makes you happy. Document is just a hint for API usages.

**Comment by sav007** [comment]
We will update the docs. Thx
