### ISSUE TITLE
getting GraphQL error and android.arch.lifestyle error in Android , kindly guide to resolve these issues .

### ISSUE THREAD

**Issue by meashu2** [Shopify/mobile-buy-sdk-android#493]
1)Failed to resolve: android.arch.lifecycle:extensions:1.0.0-alpha4 Open File Show in Project Structure dialog
2) 
Failed to resolve: android.arch.persistence.room:runtime:1.0.0-alpha4 Open File Show in Project Structure dialog
3) Failed to resolve: annotationProcessor Open File

**Comment by henrytao-me** [comment]
Is it on new project or existing one? It must be gradle version mismatch in your project. I would prefer to start a new project, then add lifecycle, room and mobile-buy-sdk to see if it can be able to sync (I believe it will sync normally). Then, compare it with your existing project.

**Comment by sav007** [comment]
Closing due inactivity
