### ISSUE TITLE
graphql package not found

### ISSUE THREAD

**Issue by Navjeet** [Shopify/mobile-buy-sdk-android#494]
....../MobileBuy\buy3\src\main\java\com\shopify\buy3\GraphResponse.java
          Error:(30, 35) error: package com.shopify.graphql.support does not exist

**Comment by henrytao-me** [comment]
Hi @Navjeet, are you switching between Apollo and Shopify flavors? If yes, please try to clean build. It should work. Let me know if you still have problem. I will reopen ticket laster. Thanks.

**Comment by Navjeet** [comment]
Hey, thanks for your reply.I was clean the project several time but still same problem and I am not switching flavors.

Thanks

**Comment by henrytao-me** [comment]
Hi @Navjeet, what SDK version are you using? Is it sample app or your app?

**Comment by Navjeet** [comment]
SDK VERSION 3 AND IT'S A SAMPLE APP.

THANKS

**Comment by tahir90** [comment]
any updates on this? iam having same issue

**Comment by henrytao-me** [comment]
@tahir90 @Navjeet Can you try this?
```
git clone git@github.com:Shopify/mobile-buy-sdk-android.git
cd mobile-buy-sdk-android
git submodule init
git submodule update
```

If you see something like `fatal: destination path 'MobileBuy/libs/graphql_java_gen' already exists and is not an empty directory.`, please do 
```
rm -rf MobileBuy/libs/graphql_java_gen
git submodule update
```

Then load the project in Android Studio. Please make sure that you don't change any gradle config. 

It should work.
