### ISSUE TITLE
Can anuy one explain this code

### ISSUE THREAD

**Issue by vijay1094** [Shopify/mobile-buy-sdk-android#498]
Hello everyone,

I am new to this shopify development can any one explain me is this code is written using GraphQL or its ruby code.

ID id = new ID("NkZmFzZGZhc");
Storefront.query(rootQueryBuilder ->
  rootQueryBuilder
    .node(id, nodeQuery ->
      nodeQuery
        .onProduct(productQuery ->
          productQuery
            .title()
            ...
        )
    )
);

Please revert me as soon as possible 

Thanks in advance

**Comment by henrytao-me** [comment]
Hi @vijay1094, that code is written in GraphQL, Java and Storefront API.
