### ISSUE TITLE
Android SDK Shipping Rates

### ISSUE THREAD

**Issue by dwlynch05** [Shopify/mobile-buy-sdk-android#499]
From Merchant"

We have one roadblock using Shopify SDK. Maybe your tech guys can help us to solve this.

We are using Shopify android SDK, and we want to get shipping rates during the checkout, but the problem is that shipping rates are coming with result "null"

So, we put items in the bucket, proceed to checkout, shipping id is created (after we add all shipping information correctly) and then we suppose to get shipping rates and complete the checkout, but nothing happens 'cause we get response from shopify = "null"

we are using two apps to calculate international shipping - DHL and Parcelify. For some reason, Australia works fine. We had issues with UK, so we added shipping costs depending on weight, so it worked too. Now we tried Singapore, check out works through website but not through the Android app, so to test, I've added one shipping rate, based on weight to Singapore country, and it worked - but not an automated price calculation.

Are we doing something wrong in this situation?

**Comment by sav007** [comment]
Calculation of shipping rates is async operation, you need to poll to get the rates: https://github.com/Shopify/mobile-buy-sdk-android#polling-for-shipping-rates-

**Comment by DemD10** [comment]
I do everything that is written in SDK.  We already wrote above. We are using two apps to calculate international shipping - DHL and Parcelify. For some reason, Australia works fine. Not working DHL. I.e, If you add shpping rates all is well, but if calculate international shipping, null response. We are waiting. Could you tell us what to do?
My code 
`    fun getShippingRate(id:ID){
        Log.e("Shipping test", "checkout ID $id")
        val call = shopifyApiBuilder(this).queryGraph(getShippingRates(id))
        call.enqueue(object : GraphCall.Callback<Storefront.QueryRoot> {
            override fun onResponse(response: GraphResponse<Storefront.QueryRoot>) {
                progressDialogCheckOut.dismiss()
               val shippingRates = (response.data()!!.node as Storefront.Checkout).availableShippingRates.shippingRates
                Log.e("Shipping test", "availableShippingRates ${(response.data()!!.node as Storefront.Checkout).availableShippingRates.ready}")
            }
            override fun onFailure(error: GraphError) {
            }

        },null, RetryHandler.exponentialBackoff(1, TimeUnit.MICROSECONDS,1.2f)
                .whenResponse<Storefront.QueryRoot> { (it.data()!!.node as Storefront.Checkout).availableShippingRates.ready == false }
                .maxCount(15)
                .build())
    }`
For DHL now working

**Comment by sav007** [comment]
Sorry confused. Is it working for DHL now?

**Comment by DemD10** [comment]
No. Does not work. Also does not work US Shipwire. Shipping rates ready false.

**Comment by sav007** [comment]
Could you try to increase the maxCount and timeout for polling to try. Because `ready == false` tells that calculation is not finished yet, maybe API for getting shipping rates from DHL /  Singapore too slow.

**Comment by DemD10** [comment]
I changed it all. I tried several options but the error remained. On the web site shipping rates are calculated quickly, but not always. How much time can take to receive shipping rates? 1,2,10 min? This is unacceptable

**Comment by yaseen-homage** [comment]
Is there any update on this issue.  It took me more than 5 mins to get shipping rate from API.

**Comment by rebeccajfriedman** [comment]
I'm going to close out this thread. As mentioned above, fetching the shipping rates requires calling out to multiple shipping providers, so it is not always instantaneous. If you are still experiencing an performance issues around this, feel free to open a new ticket with as much information as possible and we can investigate.
