### ISSUE TITLE
Not working boolean operators

### ISSUE THREAD

**Issue by DemD10** [Shopify/mobile-buy-sdk-android#500]
We have product Shirt. Shirt have tags:T-Shirt, Mens; product type: T-shirts. And if i try to add query param in my android app, i don't get products.
A week ago
>  tag:Mens AND product_type:T-shirts worked well, But today does not work.
But, individually working fine, example
> tag:Mens ->working
> product_type:T-shirts ->working

**Comment by sav007** [comment]
Could you try with the quotes, like this:
`query:"product_type:\"Shoe\" AND tag:\"some\""`

**Comment by DemD10** [comment]
Does not work. My version worked for a while but stopped. I wonder why

**Comment by sav007** [comment]
Could you please provide a shop name, that we can try to replicate this issue?

**Comment by DemD10** [comment]
https://f45sweats-aus.myshopify.com

**Comment by sav007** [comment]
Not sure why it's not working for you, I ran this query:
```
{
  shop {
    name
    products(first:10, query:"product_type:\"T-shirts\" AND tag:\"Mens\"") {
      edges {
        node {
          id
          title
          tags
          productType
        }
      }
    }
  }
}
```

It returned 5 products

**Comment by DemD10** [comment]
yes) Now it working. But 5 days ago no.
