### ISSUE TITLE
Unable to create new customer

### ISSUE THREAD

**Issue by amanzan** [Shopify/mobile-buy-sdk-android#501]
I cannot create a new customer. I don't receive any error but debugging I see customer is always null. Am I missing something?

`final Storefront.CustomerCreateInput input = new Storefront.CustomerCreateInput("john.smith@gmail.com", "123456")
                    .setFirstName("John")
                    .setLastName("Smith")
                    .setAcceptsMarketing(true)
                    .setPhone("1-123-456-7890");

            Storefront.MutationQuery mutationQuery =
                    Storefront.mutation(new Storefront.MutationQueryDefinition() {
                         @Override
                         public void define(Storefront.MutationQuery _queryBuilder) {
                             _queryBuilder.customerCreate(input, new Storefront.CustomerCreatePayloadQueryDefinition() {
                                 @Override
                                 public void define(Storefront.CustomerCreatePayloadQuery _queryBuilder) {
                                     _queryBuilder.customer(new Storefront.CustomerQueryDefinition() {
                                         @Override
                                         public void define(Storefront.CustomerQuery _queryBuilder) {
                                             _queryBuilder.id().email().firstName().lastName();
                                         }
                                     });
                                 }
                             });
                         }
                     }
            );

            MutationGraphCall createUserCall = graphClient.mutateGraph(mutationQuery);
            createUserCall.enqueue(new GraphCall.Callback<Storefront.Mutation>() {
                @Override
                public void onResponse(@NonNull GraphResponse<Storefront.Mutation> response) {
                    Storefront.Customer customer = response.data().getCustomerCreate().getCustomer();
                }

                @Override
                public void onFailure(@NonNull GraphError error) {
                    Log.e("shopify", error.toString());
                }
            });`

**Comment by sav007** [comment]
You should check the user errors, I think you get something there: https://github.com/Shopify/mobile-buy-sdk-android#creating-a-customer-

**Comment by amanzan** [comment]
Used with lambdas and made it work
