### ISSUE TITLE
Create customer and get info not working

### ISSUE THREAD

**Issue by aShaforostov** [Shopify/mobile-buy-sdk-android#502]
Hello) I'm make request for customer create

```
Storefront.CustomerCreateInput input = new Storefront.CustomerCreateInput(login, password)
                    .setFirstNameInput(Input.value(firstName))
                    .setLastNameInput(Input.value(lastName))
                    .setAcceptsMarketingInput(Input.value(true))
                    .setPhoneInput(Input.value(phone));

            Storefront.MutationQuery mutationQuery = Storefront.mutation(mutation -> mutation
                    .customerCreate(input, query -> query
                            .customer(customer -> customer
                                    .firstName()
                                    .lastName()
                                    .id()

                            )
                            .userErrors(userError -> userError
                                    .field()
                                    .message()
                            )
                    )
            );
```

Customer is always null. I can send mutation with same data and is no userErrors or GrapQLError, customer is null.

If I make login customer, in response I get accessToken, but when I send request for getting customer info, in response I get userError "you must provide one of first or last"

**Comment by aShaforostov** [comment]
If I try to login with non-valid data, there are also no userErrors or GrapQLError. Access token is null.

**Comment by aShaforostov** [comment]
Is there any progress?

**Comment by sav007** [comment]
Just tried to run a mutation to create a new customer and return `firstName` and `lastName`, works  fine. Are you sure you are not doing something wrong. 

> If I make login customer, in response I get accessToken, but when I send request for getting customer info, in response I get userError "you must provide one of first or last"

Could you please show the query you have?

**Comment by aShaforostov** [comment]
I found the problem.
In the response from your server, there is an UserError field. But when there is parsing, errors are not written into an array of errors, from this customer is null and there are no errors.

I'm found temporary solution
I'm put this code in TopLevelResponse.java of graphql_java_gen library

```
JsonParser parser = new JsonParser();
        JsonElement element = parser.parse(fields.get(DATA_KEY).toString());
        JsonObject obj = element.getAsJsonObject();
        Set<Map.Entry<String, JsonElement>> entries = obj.entrySet();
        
        for (Map.Entry<String, JsonElement> entry: entries) {
            try {
                errorsElement = entry.getValue().getAsJsonObject().getAsJsonArray("userErrors");
            }
            catch (IllegalStateException e){
                continue;
            }

        }
```
https://github.com/aShaforostov/graphql_java_gen/blob/master/support/src/main/java/com/shopify/graphql/support/TopLevelResponse.java

With this code UserErrors are added to the array.

**Comment by aShaforostov** [comment]
Is there any progress?

**Comment by kvrajukonduru** [comment]
@sav007 : I tried to create a customer. I'm getting onResponse ..but always customer object is null.below is the code. .Request to help us.

**Error:**java.lang.NullPointerException: Attempt to invoke virtual method 'com.shopify.graphql.support.ID com.shopify.buy3.Storefront$Customer.getId()' on a null object reference.

Code:
 private void createCustomerAccount(String email,String pwd){

        //input
        Storefront.CustomerCreateInput input = new Storefront.CustomerCreateInput(email, pwd)
                .setFirstName("RAJU123")
                .setLastName("VENKAT123")
                .setAcceptsMarketing(true)
                .setPhone("1-123-456-7890");

        //query
        Storefront.MutationQuery mutationQueryCreateCustomer = Storefront.mutation(mutation -> mutation
                .customerCreate(input, query -> query
                        .customer(customer -> customer
                                .id()
                                .email()
                                .firstName()
                                .lastName()
                        )
                        .userErrors(userError -> userError
                                .field()
                                .message()
                        )
                )
        );


    //API CALL for create customer Account

        graphClient.mutateGraph(mutationQueryCreateCustomer).enqueue(new GraphCall.Callback<Storefront.Mutation>() {
            @Override
            public void onResponse(@NonNull GraphResponse<Storefront.Mutation> response) {
                Log.d("RAJU","Create customer Account API SUCESS:");

                if (response.data() != null) {

                    String id = response.data().getCustomerCreate().getCustomer().getId().toString();
                    String email = response.data().getCustomerCreate().getCustomer().getEmail();
                    Log.d("RAJU","Create Customer Info:"+email+":"+id);
                }

            }


            @Override
            public void onFailure(@NonNull GraphError error) {
                Log.d("RAJU","Create customer Account API FAIL:"+error.getMessage());

            }


        });



    }

**Comment by sav007** [comment]
@aShaforostov sorry for the delay it's quite busy out here. But I don't sure I understand the issue, how come you get parsing errors?

@kvrajukonduru try to request user errors they can indicate what went wrong with your request

**Comment by GujaratiMonali** [comment]
Please try this code.
First of all create access token using Customer Access Token Create method.
```
Storefront.CustomerAccessTokenCreateInput input = new Storefront.CustomerAccessTokenCreateInput(email, password);

        Storefront.MutationQuery mutationQuery = Storefront.mutation(mutation -> mutation
                .customerAccessTokenCreate(input, query -> query
                        .customerAccessToken(customerAccessToken -> customerAccessToken
                                .accessToken()
                                .expiresAt()

                        )
                        .userErrors(userError -> userError
                                .field()
                                .message()
                        )
                )
        );

        graphClient.mutateGraph(mutationQuery).enqueue(new GraphCall.Callback<Storefront.Mutation>() {
            @Override
            public void onResponse(@NonNull GraphResponse<Storefront.Mutation> response) {

                if (!response.data().getCustomerAccessTokenCreate().getUserErrors().isEmpty()) {
                    for (Storefront.UserError error : response.data().getCustomerAccessTokenCreate().getUserErrors()) {
                        Log.e("TAG", "error" + error.getMessage());    
                    }
                } else {
                    Log.e("TAG", "login" + response.data().getCustomerAccessTokenCreate().getCustomerAccessToken().getAccessToken());
                }
            }

            @Override
            public void onFailure(@NonNull GraphError error) {
               Log.d("TAG","Create customer Account API FAIL:"+error.getMessage());
            }
        });
```
than use this access token to get customer information.. 

 ```
Storefront.QueryRootQuery query = Storefront.query(root -> root
                .customer(accessToken, customer -> customer
                        .firstName()
                        .lastName()
                        .email()
                        .phone()
                        .displayName()
                        .id()
                )
        );

        QueryGraphCall call = graphClient.queryGraph(query);
        call.enqueue(new GraphCall.Callback<Storefront.QueryRoot>() {
            @Override
            public void onResponse(@NonNull GraphResponse<Storefront.QueryRoot> response) {
                    Log.e("data", "user..." + response.data().getCustomer().getFirstName());
                    Log.e("data", "user..." + response.data().getCustomer().getLastName());
                    Log.e("data", "user..." + response.data().getCustomer().getEmail());
                    Log.e("data", "user..." + response.data().getCustomer().getPhone());
                    Log.e("data", "user..." + response.data().getCustomer().getDisplayName());
                    Log.e("data", "user..." + response.data().getCustomer().getId());
            }

            @Override
            public void onFailure(@NonNull GraphError error) {
                Log.e("TAG", "Failed to execute query", error);
            }
        });

```
