### ISSUE TITLE
Updating shipping address sample: Incompatible types (expected Mutation, found MutationQuery) 

### ISSUE THREAD

**Issue by amanzan** [Shopify/mobile-buy-sdk-android#504]
I'm trying to test the updating shipping address sample call but Android Studio complains about incompatible types (expected Mutation, found MutationQuery)

I'm using exactly the same code as appears in the sample, I cannot figure out what the issue is. Any help would be much appreciated.

This is the exact code I am using: https://github.com/Shopify/mobile-buy-sdk-android#updating-shipping-address-

Android Studio error: "error: incompatible types: MutationQuery cannot be converted to Mutation" in the Storefront.Mutation call

**Comment by amanzan** [comment]
After banging my head against the wall for a while, I noticed there's an error in the sample code. Storefront.Mutation should be Storefront.MutationQuery! Can't believe I didn't see it before

**Comment by sav007** [comment]
Sorry for that, you are right there is a mistake in the documentation. We will fix it.
