### ISSUE TITLE
How to set selected shipping rate?

### ISSUE THREAD

**Issue by amanzan** [Shopify/mobile-buy-sdk-android#505]
I'm a little bit confused about how to set the selected shipping rate, it's a little unclear in the README file.

In here: https://github.com/Shopify/mobile-buy-sdk-android#credit-card-checkout- I see this code:  
```GraphClient client = ...;
ID checkoutId = ...;
BigDecimal amount = ...;
String idempotencyKey = UUID.randomUUID().toString();
Storefront.MailingAddressInput billingAddress = ...;
String creditCardVaultToken = ...;

Storefront.CreditCardPaymentInput input = new Storefront.CreditCardPaymentInput(amount, idempotencyKey, billingAddress,
      creditCardVaultToken);
```
Is that "BigDecimal amount" the selected shipping rate amount? Or is there any selected shipping rate id that needs to be set somewhere?

Any help would be really appreciated :)

**Comment by sav007** [comment]
Please check the sample app: https://github.com/Shopify/mobile-buy-sdk-android/blob/master/MobileBuy/sample/src/shopify/java/com/shopify/sample/domain/repository/CheckoutRepository.java#L124

**Comment by amanzan** [comment]
@sav007 thanks. Honestly it is quite complicated to follow the sample app code after reading code in the readme file, especially if you're not used to ViewModels, RxJava and all that you guys use. Both codes are quite different. Following the same logic as in the readme, I assume I need to make another Storefront.MutationQuery with the selected shipping rate, is that right?

**Comment by amanzan** [comment]
I managed to make it work. In case it's useful for anyone else, here is the code:
```
Storefront.MutationQuery updateShippingQuery = Storefront.mutation(mutationQuery -> mutationQuery
                .checkoutShippingLineUpdate(new ID(getCheckoutId()), shippingRate.getHandle(), shippingLineUpdatePayloadQuery -> shippingLineUpdatePayloadQuery
                        .checkout(checkoutQuery -> checkoutQuery
                                .webUrl()
                                .totalPrice()
                                .paymentDue()
                        )
                        .userErrors(userErrorQuery -> userErrorQuery
                                .field()
                                .message()
                        )
                )
        );
```
