### ISSUE TITLE
Credit Card checkout: CheckoutCompleteWithCreditCard access denied

### ISSUE THREAD

**Issue by amanzan** [Shopify/mobile-buy-sdk-android#507]
I'm trying to complete a checkout using credit card and I get this error: **CheckoutCompleteWithCreditCard access denied**

I'm at this point: https://github.com/Shopify/mobile-buy-sdk-android#credit-card-checkout-

Everything is created correctly, but I get the error inside onResponse callback. Any idea about how to fix it?

**Comment by sav007** [comment]
Could you please provide the dump of the http response you getting back for this error?

**Comment by amanzan** [comment]
I found some other people with the same problem in Shopify ecommerce: [https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/bug-access-denied-calling-checkoutcompletewithcreditcard-from-ios-app-478115?utm_campaign=ecomu&utm_medium=email&utm_source=subscription#comment-488843](url)

So it is fixed for our shop now. 

Apparently is a bug and they are working on fixing it.
