### ISSUE TITLE
Query search for articles stopped working

### ISSUE THREAD

**Issue by andrevdk** [Shopify/mobile-buy-sdk-android#508]
Hello,
The following code stopped working on our ios and android app on 12-12-2017. It returns an empty list of articles. We use the same query format on both platforms. In the code snippet, querySearch is equal with "blog_title:{Blog name}" We can't figure out what's  the problem. The sdk version I use is v3.1.2

` 
Storefront.QueryRootQuery query = Storefront.query(
                rootQuery -> rootQuery.shop(
                        shopQuery -> shopQuery
                                .articles(args ->
                                        args.query(querySearch)
                                                .first(limit)
                                                .after(fromEdge != null
                                                        ?
                                                        fromEdge.getCursor()
                                                        : null), articleConQuery ->
                                        articleConQuery.edges(queryEdges ->
                                                queryEdges.cursor().node(queryDef ->
                                                        queryDef.tags()
                                                                .title()
                                                                .content()
                                                                .contentHtml()
                                                                .excerpt()
                                                                .excerptHtml()
                                                                .image(imgQueryDef ->
                                                                        imgQueryDef.src()
                                                                                .id()
                                                                                .altText())
                                                                .blog(blogQueryDef ->
                                                                        blogQueryDef.title()
                                                                                .url())
                                                )
                                        ))
                )
        );
`

**Comment by sav007** [comment]
Could you please the shop name and example of the query, particularly  the example of `{Blog name}` value, we will try to reproduce it.

**Comment by andrev18** [comment]
We going to speak with the client about this problem and I will send you an email in max 24 hours.

**Comment by andrevdk** [comment]
I sent you the details by email because we want to keep these details confidential.

**Comment by andrevdk** [comment]
Any update on this issue?

**Comment by sav007** [comment]
Sorry for the delay, but is it still valid issue?

**Comment by andrevdk** [comment]
Yea. I just tested the query and it doesn't work. We replaced it with another query implementation but it's not as optimal as this one. I sent you an email update.

**Comment by sav007** [comment]
Could you try smth for me, try to remove the `.image(imgQueryDef -> imgQueryDef.src() .id() .altText()) ` from the query, I guess I know what the issue but I need to confirm smth

**Comment by andrev18** [comment]
Still not working. This is the query that doesn't work:
{  
   shop   {  
      articles(query:"blog_title:Recipes",
      first:20      )      {  
         edges         {  
            cursor,
            node            {  
               id,
               tags,
               title,
               content,
               contentHtml,
               excerpt,
               excerptHtml,
               blog               {  
                  id,
                  title,
                  url
               }
            }
         }
      }
   }
}

This query works:
{  
   shop   {  
      articles(query:"Recipes",
      first:20      )      {  
         edges         {  
            cursor,
            node            {  
               id,
               tags,
               title,
               content,
               contentHtml,
               excerpt,
               excerptHtml,
               image               {  
                  src,
                  id,
                  altText
               },
               blog               {  
                  id,
                  title,
                  url
               }
            }
         }
      }
   }
}

I wanted to test a query with a different parameter:value and it  works. :
{  
   shop   {  
      articles(query:"tag:Bake",
      first:20      )      {  
         edges         {  
            cursor,
            node            {  
               id,
               tags,
               title,
               content,
               contentHtml,
               excerpt,
               excerptHtml,
               image               {  
                  src,
                  id,
                  altText
               },
               blog               {  
                  id,
                  title,
                  url
               }
            }
         }
      }
   }
}

**Comment by sav007** [comment]
I've opened a ticket for our API team to investigate this issue.

**Comment by rlake80s** [comment]
A fix went out for this on Friday, and it should be working now. 
Please try the query again, and let us know if you're still having an issue.

**Comment by sav007** [comment]
Fixed
