### ISSUE TITLE
Error:(31, 35) error: package com.shopify.graphql.support does not exist

### ISSUE THREAD

**Issue by Navjeet** [Shopify/mobile-buy-sdk-android#510]
Error:(31, 35) error: package com.shopify.graphql.support does not exist

**Comment by muneerkk66** [comment]
Any update on this ?

**Comment by henrytao-me** [comment]
Does it happen on sample project? There was similar issue here and the problem came from wrong configuration in gradle file https://github.com/Shopify/mobile-buy-sdk-android/issues/485

**Comment by sav007** [comment]
you have to update git submodules if you cloned the sample project:
https://github.com/Shopify/mobile-buy-sdk-android/tree/master/MobileBuy/sample

**Comment by RishabhTayal** [comment]
@sav007 Maybe the instructions file needs to be updated. There are lot of people asking the same question. 🤷‍♂️
