### ISSUE TITLE
Is there any app with custom checkout implemented?

### ISSUE THREAD

**Issue by amanzan** [Shopify/mobile-buy-sdk-android#521]
I'd like to know if anybody in the market implemented the entire SDK, checkout included. Since the example does not include checkout. It would be great to see a real app with this working to determine if it is worth it in terms of UX. Do you guys know of any app using your SDK as of right now?

Thanks a lot!

**Comment by sav007** [comment]
Sorry for the delay, but what exactly you need for the checkout? You always can open `url` link to finish checkout. You can finish checkout with credit card or Android Pay

**Comment by amanzan** [comment]
Well, I would like to implement the checkout to have the full process customised, I'm not a big fan of using WebViews. I have an open issue (#525) with a bug I found that makes the custom checkout unusable. Is the custom checkout being actively maintained, or are you guys focusing on different things and checkout is not one of them? My team is very interested in using it, actually we spent several days integrating it and made it work, but suddenly it just stopped working. Not quite sure if this would be production-ready.

**Comment by dri94** [comment]
This sample is still needed for people trying to use shopify. There is little support on the forums or in this github repo. A sample would help a lot

**Comment by vijayakumarram** [comment]
HI 


Credit Card Vault Token Reuseability  is geeting 405 error

**Comment by vijayakumarram** [comment]
any body  help

**Comment by ranamrameez** [comment]
Seems like no one has implemented whole checkout process in the android app. And we must have to use webview to complete checkout process.

**Comment by rebeccajfriedman** [comment]
Hi everyone. I'm going to close out this thread, but I suggest posting on the [forum](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology) for questions around implementation. 

You can learn more about the different ways of completing checkouts by reading the:
- [SDK README section on completing a checkout](https://github.com/Shopify/mobile-buy-sdk-android#completing-a-checkout-)
- [API Guide on working with checkouts](https://help.shopify.com/en/api/storefront-api/guides/checkout-guide#completing-the-checkout)
