### ISSUE TITLE
How to get collectionId?

### ISSUE THREAD

**Issue by Midhilaj** [Shopify/mobile-buy-sdk-android#522]
https://github.com/Shopify/mobile-buy-sdk-android#pagination-
check  this [https://ibb.co/dWxbrm](url)

**Comment by Midhilaj** [comment]
Your ibb url is invalid.
     copy url and past in new tab it will work.

Storefront.QueryRootQuery query = Storefront.query(rootQuery -> rootQuery
  .node(new ID(<h1>What is this id and where to find this ?</h1>), nodeQuery -> nodeQuery
    .onCollection(collectionQuery -> collectionQuery
      .products(
        args -> args
          .first(10)
          .after(productPageCursor),
        productConnectionQuery -> productConnectionQuery
          .pageInfo(pageInfoQuery -> pageInfoQuery
            .hasNextPage()
          )
          .edges(productEdgeQuery -> productEdgeQuery
            .cursor()
            .node(productQuery -> productQuery
              .title()
              .productType()
              .description()
            )
          )
      )
    )
  )
);

**Comment by henrytao-me** [comment]
Hi @Midhilaj 

Firstly, this `IjoxNDg4MTc3MzEsImxhc3R` is collectionId. That query basically means that gives me pagination products within collection `IjoxNDg4MTc3MzEsImxhc3R`. 

Secondly, If you want to get collectionId, please use this query https://github.com/Shopify/mobile-buy-sdk-android#fetch-collections-and-products-. It will return nested list: list of collections and list of products within each collection. 

Finally, every `edges` has `cursor`. After fetching the first page, you need to get `cursor` and passes to `.after(cursor)` for fetching next page.
