### ISSUE TITLE
Does SDK support Android Pay or Google Pay?

### ISSUE THREAD

**Issue by plzen** [Shopify/mobile-buy-sdk-android#526]
I set up Android Pay according docs and I encountered with next problem:
- SDK returns response for complete checkout but order isn't created. This checkout shown as Abandoned Checkout. So looks like payment hasn't been processed. For some checkouts I see 500 error in Additional details section on Checkout details page in Admin panel.

Also, could you help me with next questions?
- Does Android Pay supported by Shopify (on some articles I have read that Google blocks new setups and moves all to Google Pay). Looks like Android Pay is deprecated now.
- Do you have plans to add Google Pay support?
- Does Shopify support sandbox mode for payments? Shop always blocked when I have a lot of test payments (I used test cards in test mode)
- Does Android Pay support cards issued not in US?

Thank you in advance.

**Comment by sav007** [comment]
> Does Android Pay supported by Shopify (on some articles I have read that Google blocks new setups and moves all to Google Pay). Looks like Android Pay is deprecated now.

That's right, Android Pay is deprecated in favour of Google Pay. We will updates docs to make it explicit.

> Do you have plans to add Google Pay support?

We do, and we are currently working on server side integration part. For now unfortunately there is no way to test it in the sandbox until we finish with integration of Google Pay.

**Comment by plzen** [comment]
> We do, and we are currently working on server side integration part. For now unfortunately there is no way to test it in the sandbox until we finish with integration of Google Pay.

So does it mean that I can't use Android Pay now and will be able to use Google Pay after server side fixes?

**Comment by sav007** [comment]
You can't use Android Pay, as Google closed package white listing, that means you won't be able to register your app to enable Android Pay and make it to work out of the test env. 

Google Pay is the only way (and btw the API is much much simpler) but we need to finish our server side integration.

**Comment by plzen** [comment]
@sav007 Thank you for help!
