### ISSUE TITLE
Unable to get Customer details

### ISSUE THREAD

**Issue by markj** [Shopify/mobile-buy-sdk-android#528]
Our apps have just stopped being able to get the Customer Details. Has something changed on your backend?

As of today our users have been unable to login despite having a valid authentication Token.

We perform
`mutation {
  customerAccessTokenCreate(input: {email: "mark@---------.com", password: "-------"}) {
    customerAccessToken {
      expiresAt
      accessToken
    }
    userErrors {
      message
      field
    }
  }
}
`

which succeeds and then call to get the customer with that token

`query GetCustomer {
  customer(customerAccessToken: "-------") {
    acceptsMarketing
    createdAt
    displayName
    email
    firstName
    id
    lastName
  }
}
`

but every request has a null customer returned.

**Comment by sav007** [comment]
Could you please provide shop name or DM me your API client ID.

**Comment by markj** [comment]
Thanks, I've sent you an email

**Comment by sav007** [comment]
We have rolled out a fix during this weekend, this issue should be fixed by now.
