### ISSUE TITLE
return null problem

### ISSUE THREAD

**Issue by muratdoglu** [Shopify/mobile-buy-sdk-android#532]
Hello this is my query. 
-------
```
Storefront.QueryRootQuery query = Storefront.query(
                rootQuery -> rootQuery
                        .node(new ID(productId),nodeQuery -> nodeQuery
                                .onProduct(productQuery -> productQuery
                                        .title()
                                        .description()
                                        .descriptionHtml()
                                        .images(arg -> arg.first(10), imageConnectionQuery -> imageConnectionQuery
                                                .edges(imageEdgeQuery -> imageEdgeQuery
                                                        .node(imageQuery -> imageQuery
                                                                .src()
                                                        )
                                                )
                                        )
                                        .variants(arg -> arg.first(10), variantConnectionQuery -> variantConnectionQuery
                                                .edges(variantEdgeQuery -> variantEdgeQuery
                                                        .node(productVariantQuery -> productVariantQuery
                                                                .price()
                                                                .title()
                                                                .available()
                                                        )
                                                )
                                        )
                                )
                        )
        );
```
 -------
but 
in response;
Storefront.Product product = (Storefront.Product) response.data().getNode();
but most data return null.

product.getDescriptionHtml() //null!!
.....

why? thank you

**Comment by muratdoglu** [comment]
@henrytao-me  do you know this?

**Comment by henrytao-me** [comment]
Hi @muratdoglu, I am checking...

**Comment by henrytao-me** [comment]
It sounds weird but I just check in same app, it return data. 🤔

**Comment by muratdoglu** [comment]
@henrytao-me i try admin api, it's not null. I can not understand. thank you bro.

**Comment by Hafros** [comment]
Check is your product available in sale channel of private app

**Comment by henrytao-me** [comment]
Thanks @Hafros for the reply. @muratdoglu here is a screenshot in private app.

![image](https://user-images.githubusercontent.com/5274722/37596001-1dffd394-2b51-11e8-840b-0da0e40ce419.png)

**Comment by Hafros** [comment]
@muratdoglu Also check is product available in sales channel
![2018-03-19 14 59 28](https://user-images.githubusercontent.com/20553725/37596933-7720cd2c-2b86-11e8-9154-7b33198777c1.png)

**Comment by muratdoglu** [comment]
@Hafros @henrytao-me yes I did what you said but there was no solution. :/
I am sending the "shopDomain" and "accessToken" parameters. Could it be missing in your opinion?
` GraphClient graphClient = GraphClient.builder(this)
            .shopDomain(this.getApplicationContext().getResources().getString(R.string.shop_domain))
           .accessToken(this.getApplicationContext().getResources().getString(R.string.StorefrontApiKey))
                //   .httpClient(httpClient) // optional
                .httpCache(new File(this.getCacheDir(), "/http"), 10 * 1024 * 1024) // 10mb for http cache
                .defaultHttpCachePolicy(HttpCachePolicy.CACHE_FIRST.expireAfter(5, TimeUnit.MINUTES)) 
                .build();` 

<img width="666" alt="ekran resmi 2018-03-19 16 23 35" src="https://user-images.githubusercontent.com/19818531/37598007-127dff1e-2b92-11e8-9048-fa99379c7cf4.png">
<img width="624" alt="ekran resmi 2018-03-19 16 24 01" src="https://user-images.githubusercontent.com/19818531/37598008-12a117b0-2b92-11e8-9f32-8121418169a1.png">

**Comment by Hafros** [comment]
What is productId your send?
Can you show?

**Comment by muratdoglu** [comment]
Storefront.Collection collection = (Storefront.Collection) response.data().getNode(); productArrayList.add(productEdge.getNode());
 for (Storefront.ProductEdge productEdge :  collection.getProducts().getEdges()) {
                        productArrayList.add(productEdge.getNode());
                    }
i send  **productArrayList.get(position).getId()**

**Comment by Hafros** [comment]
Send productArrayList.get(position).getId().toString()

Or make Log.d("",""+productArrayList.get(position).getId().toString())
And show us

**Comment by muratdoglu** [comment]
i send productArrayList.get(position).getId()
sample Log: Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lzg4NTY5MjYyMjQ=
@Hafros

**Comment by Hafros** [comment]
**8856926224** This is id in Shopify admin what your request?

**Comment by Hafros** [comment]
Add this OKHttp client to your Graph Client 

```
HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient client = new OkHttpClient.Builder()
                .addInterceptor(logging)
                .build();
```

```
return GraphClient.builder(context)
                .shopDomain(BuildConfig.SHOP_DOMAIN)
                .accessToken(BuildConfig.API_KEY)
                .httpClient(client) // optional
                .httpCache(new File(context.getCacheDir(), "/http"), 10 * 1024 * 1024) // 10mb for http cache
                .defaultHttpCachePolicy(HttpCachePolicy.CACHE_FIRST.expireAfter(5, TimeUnit.MINUTES)) // cached response valid by default for 5 minutes
                .build();
```

And you will see request and response raw data in LogCat

**Comment by muratdoglu** [comment]
okey. i need product detail and variants. this is my code;
productId=  " Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lzg4NTY5MjYyMjQ";

```
GraphClient graphClient = GraphClient.builder(this)
                .shopDomain(this.getApplicationContext().getResources().getString(R.string.shop_domain))
           .accessToken(this.getApplicationContext().getResources().getString(R.string.StorefrontApiKey))
               .httpCache(new File(this.getCacheDir(), "/http"), 10 * 1024 * 1024) // 10mb for http cache
                .defaultHttpCachePolicy(HttpCachePolicy.CACHE_FIRST.expireAfter(5, TimeUnit.MINUTES)) // cached response valid by default for 5 minutes
                .build();
        Storefront.QueryRootQuery query = Storefront.query(
                rootQuery -> rootQuery
                        .node(new ID(productId),nodeQuery -> nodeQuery
                                .onProduct(productQuery -> productQuery
                                        .title()
                                        .description()
                                        .descriptionHtml()
                                        .images(arg -> arg.first(10), imageConnectionQuery -> imageConnectionQuery
                                                .edges(imageEdgeQuery -> imageEdgeQuery
                                                        .node(imageQuery -> imageQuery
                                                                .src()
                                                        )
                                                )
                                        )
                                        .variants(arg -> arg.first(10), variantConnectionQuery -> variantConnectionQuery
                                                .edges(variantEdgeQuery -> variantEdgeQuery
                                                        .node(productVariantQuery -> productVariantQuery
                                                                .price()
                                                                .title()
                                                                .available()
                                                        )
                                                )
                                        )
                                )
                        )
        );

 graphClient.queryGraph(query).enqueue(new GraphCall.Callback<Storefront.QueryRoot>() {
            @Override public void onResponse(@NonNull GraphResponse<Storefront.QueryRoot> response) {
               Storefront.Product product = (Storefront.Product) response.data().getNode();

                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        staticData();
                     
                    }
                });
            }

            @Override
            public void onFailure(@NonNull GraphError error) {

            }
        });
```

**Comment by Hafros** [comment]
product.getDescription() also null?
Is description is exist in product?

**Comment by muratdoglu** [comment]
this is okhttp log https://codebeautify.org/online-json-editor/cb47a532
but :D 
 Storefront.Product product = (Storefront.Product) response.data().getNode();
 Log.i("problem",product.getTitle());   **is null**
Am I doing something wrong? :D

**Comment by Hafros** [comment]
Hey @henrytao-me what is the magic?
In okhttp log we see that product return, but object of product don't parse data

**Comment by muratdoglu** [comment]
i am an idiot! I found the problem. 
product is local variable. but my Log is in the other function. 
 Storefront.Product **product** = (Storefront.Product) response.data().getNode(); 


I am very sorry. Thanks for everything @Hafros
