### ISSUE TITLE
Unable to get Applied Discount Coupon information

### ISSUE THREAD

**Issue by AkashDoshi19** [Shopify/mobile-buy-sdk-android#534]
Hi,

We have integrated Mobile Buy SDK 3.0 for Android and iOS but while doing checkout we are getting following issues

1. Unable to get applied discount coupon details - We need this to show applied discount coupon details
2. Unable to add multiple Giftcards - If we applied new Gift card then old one is getting replaced. On website we can add multiple gift cards. 

Above both issues were working properly on Mobile Buy SDK 2.0. 

Can you help us to solve these issue?

**Comment by mihai-moldovan** [comment]
Same problem here. I browsed the [GraphQL explorer here. ](https://help.shopify.com/api/custom-storefronts/storefront-api/graphql-explorer)but couldn't find a way to get discount value

**Comment by jamiemtdwyer** [comment]
1. You can view the discount applications on the checkout object by fetching the [`discountApplications`](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/object/checkout#discountapplications) field.

2. You can add multiple gift cards to a checkout using the [checkoutGiftCardAppend mutation](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/mutation/checkoutgiftcardsappend)

Cheers!
