### ISSUE TITLE
Failed to apply plugin [id 'org.gradle.checkstyle']   

### ISSUE THREAD

**Issue by Midhilaj** [Shopify/mobile-buy-sdk-android#538]
Error:(24, 1) A problem occurred evaluating root project 'my_project_name'.
> Failed to apply plugin [id 'org.gradle.checkstyle']
   > Could not create service of type CachingFileHasher using TaskExecutionServices.createFileSnapshotter().

**Comment by sav007** [comment]
Sorry issue is not related to MBSDK, or please provide more info on this
