### ISSUE TITLE
Checkout Attributes

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-android#55]
Add support for checkout attributes. See iOS for details: https://github.com/Shopify/mobile-buy-sdk-ios/pull/93

**Comment by bgulanowski** [comment]
@krisorr

**Comment by JoshuaChing** [comment]
Closing issue because this has already been implemented.

**Comment by RishabhTayal** [comment]
Can someone give an example of how can we apply attributes?
