### ISSUE TITLE
Application get crash

### ISSUE THREAD

**Issue by lokeshdesai403** [Shopify/mobile-buy-sdk-android#550]
![f8a68e28-36a6-44ba-8a7b-b3666a68f9db](https://user-images.githubusercontent.com/13298524/41027383-866b0576-6994-11e8-9dd3-16eeafaa0889.jpeg)
![d6bf8089-c267-4aea-8b71-c6af54f26bbc](https://user-images.githubusercontent.com/13298524/41027385-86d0791a-6994-11e8-9059-f09ecf41dc51.jpeg)
![a90e5b8c-17a2-4233-ba1c-5bdb3b7170e7](https://user-images.githubusercontent.com/13298524/41027388-8722332c-6994-11e8-84d9-d7efbfc87cf6.jpeg)

Whenever i am notifying adapter after getting api response application get crash on any screen. Issue happens when i scroll recyclerview.

Error:
“java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder”

**Comment by sav007** [comment]
Sorry but this is not related to MBSDK issue, it's probably you are notifying about changes from the wrong thread
