### ISSUE TITLE
Checkout using credit card not working.

### ISSUE THREAD

**Issue by networld301ios** [Shopify/mobile-buy-sdk-android#552]
checkout using credit card option in testing mode gives a error as below

MobileBuySDK.Graph.QueryError.invalidQuery([MobileBuySDK.Graph.QueryError.Reason(message: "CheckoutCompleteWithCreditCard access denied", line: nil, column: nil)])

i am using code from refrence
https://github.com/Shopify/mobile-buy-sdk-ios#credit-card-checkout-

**Comment by rebeccajfriedman** [comment]
This functionality is guarded by a scope.
You can read more about it here: https://help.shopify.com/en/api/storefront-api/guides/checkout-guide#completing-the-checkout in the `Using the checkoutCompleteWithCreditCardV2 mutation with the vault ID` section.
