### ISSUE TITLE
Checkout complete with credit card isn't working

### ISSUE THREAD

**Issue by yaseen-homage** [Shopify/mobile-buy-sdk-android#554]
@sav007  I've enabled the test mode for Shopify Payments and trying to test the payments
When I try to simulate the successful transactions the SDK throws error.

When I do poll for **checkoutCompleteWithCreditCard** Eventhough the payment status is ready and It shows `No Match` or `This transaction cannot be processed`

` RetryHandler.exponentialBackoff(500, TimeUnit.MILLISECONDS, 1.2f)
                                                        .whenResponse(
                                                                result -> ((Storefront.Payment) ((GraphResponse<Storefront.QueryRoot>) result).data().getNode()).getReady() == false
                                                        )
                                                        .maxCount(12)
                                                        .build()`

 **Test card details** 
![screen shot 2018-07-12 at 12 27 25 pm](https://user-images.githubusercontent.com/28296471/42613231-63ea26da-85d2-11e8-8fb5-9ae8a0c17408.png)

The Error message isn't consistent. sometimes it throws **No Match** error and sometimes it throws **This transaction cannot be processed**

![screen shot 2018-07-12 at 12 17 46 pm](https://user-images.githubusercontent.com/28296471/42613326-fce6cef6-85d2-11e8-9338-c13080e3a9e6.png)

![screen shot 2018-07-12 at 12 21 42 pm](https://user-images.githubusercontent.com/28296471/42613323-fa1ee9ba-85d2-11e8-8ed1-d3ea681ab8c4.png)

**Comment by rebeccajfriedman** [comment]
Closing this as stale. Please open a new ticket if the issue persists.
