### ISSUE TITLE
Customer Orders returing null values 

### ISSUE THREAD

**Issue by Bhargavasrinivas** [Shopify/mobile-buy-sdk-android#555]
Hi,
 I am new to Shopify  and I am developing an android app using Shopify storefront APIs,
I integrated the customer order api  but the response is always null.
Below is my code
```java
        Storefront.QueryRootQuery query = Storefront.query(root -> root
                .customer(Util.accessToken, customer -> customer
                        .orders(arg -> arg.first(10), connection -> connection
                                .edges(edge -> edge
                                        .node(node -> node
                                                .orderNumber()
                                                .totalPrice()
                                                .subtotalPrice()
                                                .statusUrl()

                                        )
                                )
                        )
                )
        );

        QueryGraphCall call = graphClient.queryGraph(query);

        call.enqueue(new GraphCall.Callback<Storefront.QueryRoot>() {
            @Override
            public void onResponse(@NonNull GraphResponse<Storefront.QueryRoot> response) {
                progressDialog.dismiss();
                Storefront.OrderConnection res = response.data().getCustomer().getOrders();
            }
            @Override
            public void onFailure(@NonNull GraphError error) {
                progressDialog.dismiss();
                Toast.makeText(getApplicationContext(), " Error" + error.getMessage(), Toast.LENGTH_SHORT).show();

            }
        });
```
   Thanks in Advance.

**Comment by GujaratiMonali** [comment]
please try it.
order all data available in response


Storefront.QueryRootQuery query = Storefront.query(root -> root
        .customer(accessToken, customer -> customer
                .acceptsMarketing()
                .updatedAt()
                .id()
                .orders(arg -> arg.first(10), connection -> connection
                        .pageInfo(page->page
                            .hasNextPage()
                            .hasPreviousPage()
                            )
                        .edges(edge -> edge
                                .node(node -> node
                                        .orderNumber()
                                        .totalPrice()
                                        .email()
                                        .phone()
                                        .totalShippingPrice()
                                        .totalTax()
                                        .totalRefunded()
                                        .currencyCode()
                                        .customerUrl()
                                        .statusUrl()
                                        .processedAt()
                                        .customerLocale()
                                        .subtotalPrice()
                                        .lineItems(arg -> arg.first(10), connection1 -> connection1
                                                .edges(edge1 -> edge1
                                                        .node(node1 -> node1
                                                                .quantity()
                                                                .title()
                                                                .variant(variant -> variant
                                                                        .title()
                                                                        .availableForSale()
                                                                        .price()
                                                                        .compareAtPrice()
                                                                        .weight()
                                                                        .sku()
                                                                        .weightUnit()
                                                                        .image(image -> image
                                                                                .originalSrc()
                                                                                .id()
                                                                                .altText()
                                                                        )
                                                                        .product(product -> product
                                                                                .description()
                                                                                .title()
                                                                                .handle()
                                                                                .createdAt()
                                                                                .updatedAt()
                                                                                .onlineStoreUrl()
                                                                                .publishedAt()
                                                                                .vendor()
                                                                                .tags()
                                                                                .images(arg -> arg.first(10), connection2 -> connection2
                                                                                        .edges(edge2 -> edge2
                                                                                                .node(node2 -> node2
                                                                                                        .id()
                                                                                                        .originalSrc()
                                                                                                )
                                                                                        )
                                                                                )
                                                                                .options(options -> options
                                                                                        .name()
                                                                                        .values()
                                                                                )
                                                                        )
                                                                )
                                                                .customAttributes(customer1 -> customer1
                                                                        .key()
                                                                        .value()
                                                                )
                                                        )
                                                )
                                        )
                                )
                        )
                )
        )
);
QueryGraphCall call = graphClient.queryGraph(query);
call.enqueue(new GraphCall.Callback<Storefront.QueryRoot>() {
    @Override
    public void onResponse(@NonNull GraphResponse<Storefront.QueryRoot> response) {
            for (int i = 0; i < response.data().getCustomer().getOrders().getEdges().size(); i++) {
orderNumber=response.data().getCustomer().getOrders().getEdges().get(i).getNode().getOrderNumber();
                Log.e("order", "order number.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getOrderNumber());
                Log.e("order", "order id.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getId());
                Log.e("order", "processedA.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getProcessedAt());
                Log.e("order", "statusUrl.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getStatusUrl());
                Log.e("order", "currencycode.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getCurrencyCode());
                Log.e("order", "customerUrl.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getCustomerUrl());
                Log.e("order", "totalTax.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getTotalTax());
                Log.e("order", "totalShippingPrice.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getTotalShippingPrice());
                Log.e("order", "customerLocale.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getCustomerLocale());
                Log.e("order", "subtotalPrice.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getSubtotalPrice());

                for (int j = 0; j < response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().size(); j++) {
                    Log.e("order", "title..." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getTitle());
                    Log.e("order", "qty..." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getQuantity());
                    Log.e("order", "variantTitle.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getVariant().getTitle());
                    Log.e("order", "variantId.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getVariant().getId());
                    Log.e("order", "variantPrice.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getVariant().getPrice());
                    Log.e("order", "variantImageSrc.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getVariant().getImage().getOriginalSrc());
                    Log.e("order", "variantImageId.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getVariant().getImage().getId());
                    Log.e("order", "productDesc..." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getVariant().getProduct().getDescription());
                    Log.e("order", "productId...." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getVariant().getProduct().getId());
                    Log.e("order", "productTitle..." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getVariant().getProduct().getTitle());
                    for (int k = 0; k < response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getVariant().getProduct().getImages().getEdges().size(); k++) {
                        Log.e("order", "productImageId.." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getVariant().getProduct().getImages().getEdges().get(k).getNode().getId());
                        Log.e("order", "productImageSrc..." + response.data().getCustomer().getOrders().getEdges().get(i).getNode().getLineItems().getEdges().get(j).getNode().getVariant().getProduct().getImages().getEdges().get(k).getNode().getOriginalSrc());
                    }
                }
            }
        }
    }

    @Override
    public void onFailure(@NonNull GraphError error) {
        Log.e("TAG", "Failed to execute query", error);
    }
});
any query than please ask me
