### ISSUE TITLE
Order not showing in customer order history.

### ISSUE THREAD

**Issue by Pradeepkumar2091** [Shopify/mobile-buy-sdk-android#568]
Hello
With this SDK I am able to place the test order. when I saw all orders in admin there is showing all orders, but with a particular customer, the order is not showing in their history.

Currently, I am using Payment method as Shopify Payment.

![admin order history](https://user-images.githubusercontent.com/17064383/45364139-fc0b9580-b5f6-11e8-9b6c-5eac816d3840.PNG)

![Customer order history](https://user-images.githubusercontent.com/17064383/45364140-fca42c00-b5f6-11e8-8026-73bd2dab3897.PNG)

**Comment by rebeccajfriedman** [comment]
Are you still experiencing this issue?
