### ISSUE TITLE
checkout with credit card

### ISSUE THREAD

**Issue by AmanWegile** [Shopify/mobile-buy-sdk-android#573]
checkout using credit card option in testing mode gives a error as below

MobileBuySDK.Graph.QueryError.invalidQuery([MobileBuySDK.Graph.QueryError.Reason(message: "CheckoutCompleteWithCreditCard access denied", line: nil, column: nil)])

**Comment by dri94** [comment]
Can you post your code?

**Comment by rebeccajfriedman** [comment]
Closing this as stale.

As mentioned in the [API checkout guide](https://help.shopify.com/en/api/storefront-api/guides/checkout-guide): to complete the checkout using the checkoutcompletewithtokenizedpaymentv2 mutation you need to have the write_checkouts_payments scope enabled for your app. The scope is enabled by requesting payment processing.
