### ISSUE TITLE
How to fetch the Pages from Api

### ISSUE THREAD

**Issue by Bhargavasrinivas** [Shopify/mobile-buy-sdk-android#577]
Hi All,

I am developing an android Application  Using the Mobile _buy _sdk (Store front apis )facing issue while fetching the  Pages like About Us ,Contact Us and Privacy policy.
I need an api demo or bit of code that how to fetch those things from api , i searched a lot
i couldn't find any solution yet .

**Comment by rebeccajfriedman** [comment]
This functionality is currently not supported in the Storefront API. We have added this issue to our project board.

**Comment by rebeccajfriedman** [comment]
Accessing Pages is now supported through our API! See the [pages connection on the queryroot](https://help.shopify.com/en/api/storefront-api/reference/queryroot) for more information.
