### ISSUE TITLE
Is there any way to get reviews of prooduct?

### ISSUE THREAD

**Issue by BrickCar** [Shopify/mobile-buy-sdk-android#578]
I want to know if there is any way to get product reviews. thanks.

**Comment by mvayak** [comment]
Hello @BrickCar 
no way to get reviews of products using storefront API. if you want to get the review of products you have to install review app on the store and you can get review using installed APP RestAPI if the app provides RestAPI.

Thank you :)

**Comment by rebeccajfriedman** [comment]
As mentioned above, this functionality is not supported by the underlying Storefront API. I suggest installing a product reviews app, or posting on the [community forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology) for more suggestions.
