### ISSUE TITLE
Web Checkout not displaying all payment options

### ISSUE THREAD

**Issue by moesalih** [Shopify/mobile-buy-sdk-android#580]
I'm currently the web checkout flow using `checkout.getWebUrl()` and displaying that in a `WebView`.

On iOS, we get all available payment options during web checkout as expected. But on Android it seems like we're getting a different flow where we only get a credit card option and paypal. No Google Pay or Amazon Pay, and even the credit card payment section seems to be different than normal where it forwards you to a payment gateway.

Why would that be the case? How can I fix this?

**Comment by rebeccajfriedman** [comment]
Hi @moesalih - this doesn't sounds like an issue with the SDK, but rather one with your checkout in general. I just tested loading your shop on an Android web browser and the "Google Pay" option popped in for me. I recommend reaching out to [Shopify support](https://help.shopify.com/en/questions#/questions) if you continue to experience issues with it.

**Comment by moesalih** [comment]
@rebeccajfriedman I'm aware that the checkout works fine in the regular browser. As I said, the issue is when the checkout is being embedded in a `WebView` like the SDK instructs.

And how did you know what store I'm referring to? This is for a large ShopifyPlus client, and I did contact support, they said I should open an issue here.

**Comment by rebeccajfriedman** [comment]
Sorry for the confusion, I was looking at moesalih.myshopify.com.
Google Pay is only supported if you use a Chrome tab or open a native web browser Chrome. If you use an embedded webview, it does not support Google Pay.
