### ISSUE TITLE
Checkout complete free isn't working (for Cash on delivery)

### ISSUE THREAD

**Issue by MuhammadMuzammilSharif** [Shopify/mobile-buy-sdk-android#581]
I am trying to buy products using Cash On Delivery payment method but when I try to implement code below it always throw an error that "Payment is required" while the Cash On Delivery Payment Method is enabled from admin side.

```
val mutationQuery = Storefront.mutation { mutationQuery ->
    mutationQuery.checkoutCompleteFree(checkoutId) { checkoutCompleteQuery ->
        checkoutCompleteQuery
                .userErrors { userErrorQuery ->
                    userErrorQuery
                            .message()
                            .field()
                }.checkout { checkoutQuery ->
                    checkoutQuery
                            .ready()
                            .note()
                }
    }
}
val graphClient = ...
graphClient.mutateGraph(mutationQuery).enqueue(object : GraphCall.Callback<Storefront.Mutation> {
    override fun onFailure(error: GraphError) {
        Log.e("ERROR", error.toString())
    }

    override fun onResponse(response: GraphResponse<Storefront.Mutation>) {
        Log.d("Response", response.toString())
    }
})
```

**Comment by rebeccajfriedman** [comment]
We currently don't support manual payments (such as cash on delivery) in the Storefront API. The .checkoutCompleteFree mutation is used only for completing a checkout that doesn't cost anything - it must be free.

We are tracking this issue in our backlog. Sorry for the inconvenience.

**Comment by venkataseshaiahudatha** [comment]
We are also in same situation. We have this feature available in desktop and Mobile web and not able to achieve it in Mobile app. It would be great If you get this feature nearby. 

Do you have any plan to expose this feature in mobile SDK. When can we expect the same.

**Comment by rebeccajfriedman** [comment]
We definitely have plans to expose this functionality, although I don't have a timeline for you yet.

**Comment by RatulSaha** [comment]
@rebeccajfriedman any followup on this?

**Comment by rebeccajfriedman** [comment]
Unfortunately, we haven't been able to add this functionality yet. Sorry for the delay!

**Comment by RatulSaha** [comment]
@rebeccajfriedman Thank you for the response. Just to confirm, there is no way for programmatically create an order with manual payment method?

**Comment by rebeccajfriedman** [comment]
Not at this time using the Storefront API. You could use the Admin API to create a [draft order](https://help.shopify.com/en/manual/orders/create-orders). Draft orders can be paid with COD.

See mutations list for Admin API: https://help.shopify.com/en/api/graphql-admin-api/reference/mutation/draftordercreate

**Comment by RatulSaha** [comment]
Many thanks for the direction, appreciate it! Just the last followup question: when you say "Draft orders can be paid with COD", can you point to the mutation that works with that? I shuffled through `draftOrderComplete` and a few others, but none mentions manual payments as an option.

**Comment by rebeccajfriedman** [comment]
I ahven't tried this programmatically, but I would suggest sending `paymentPending: false`

**Comment by Weakky** [comment]
Hey 👋, it seems like using the Admin API from a user-land app is terribly unsafe. Even if we restrict the API key to only mess with orders, if someone ever gets that API key, he'll be free to create/delete/update any order.

Aren't there any solutions/safer workarounds?

**Comment by RatulSaha** [comment]
Yes, you should never use admin API in the frontend. And yes there is a way.

You create your own backend that connects to Shopify. From your frontend,
you talk to your backend for orders.

Terrible, I know. I just implemented this and it will take a lot of your
time. :-)

**Comment by AhmedAwaisS** [comment]
Does it fixed now? I am also having same issue in this mutation.
checkoutCompleteFree error "Payment is required"

**Comment by ntelkedzhiev** [comment]
Any update on this? It is a much needed feature...

**Comment by fabioportieri** [comment]
bump, also in italy COD is very popular and from what i'm understanding there is no way to create a legit order / checkout with cod payment ?

**Comment by fabioportieri** [comment]
> Not at this time using the Storefront API. You could use the Admin API to create a [draft order](https://help.shopify.com/en/manual/orders/create-orders). Draft orders can be paid with COD.
> You could use the Admin API to create a [draft order](https://help.shopify.com/en/manual/orders/create-orders). Draft orders can be paid with COD.

Actually, i tried this, and it is not feasible because we don't have a way to retrieve the payment gateway id from the shopify api! Works only for manual payments.
