### ISSUE TITLE
Phone number is not valid

### ISSUE THREAD

**Issue by dri94** [Shopify/mobile-buy-sdk-android#582]
When trying to create a user i continuously get phone number is not valid. My code is
```

       val input = Storefront.CustomerCreateInput("test@gmail.com", "password")
                .setFirstNameInput(Input.value("John"))
                .setLastNameInput(Input.value("Doe"))
                .setAcceptsMarketingInput(Input.value(true))
                .setPhoneInput(Input.value("1-123-456-7890"))
```
I tried replacing the info on the input to my personal info but the same error comes back

**Comment by rebeccajfriedman** [comment]
A phone number formatted like that should work, provided that you are passing in a valid country code and area code.

**Comment by dri94** [comment]
The documentation needs to be updated to state phone must be E164 format. The error returned simply says "Phone is invalid" when it should say that the phone is already registered with another customer, or that the phone format is wrong.

**Comment by rebeccajfriedman** [comment]
Thank you for your patience. We have added this suggestion to our backlog, and we will be addressing it in the new year.

**Comment by rebeccajfriedman** [comment]
We have updated the API documentation: https://help.shopify.com/en/api/storefront-api/reference/mutation/customercreate
The description for `phone` input now explicitly mentions formatting using E.164 standard.

The next time the SDK is updated, all comments in [Storefront.java](https://raw.githubusercontent.com/Shopify/mobile-buy-sdk-android/master/MobileBuy/buy3/src/main/java/com/shopify/buy3/Storefront.java) will also be updated to mention the format as well.
