### ISSUE TITLE
please I need help on how to set up the graphql_java_gen because my collections are not displaying after a successfull build of the android buy sdk

### ISSUE THREAD

**Issue by Orton16** [Shopify/mobile-buy-sdk-android#584]

**Comment by rebeccajfriedman** [comment]
Here is a link to the graphql_java_gen repo: https://github.com/Shopify/graphql_java_gen

It looks like it's a ruby gem, so it will need to be run from a ruby environment. I suggest you create an issue on that repo if you have any follow up questions.
