### ISSUE TITLE
import com.shopify.graphql.support.Input; Does not exist this class

### ISSUE THREAD

**Issue by Ketuzzz** [Shopify/mobile-buy-sdk-android#591]
`import com.shopify.graphql.support.Input; `

This Class Does not exist.

**Comment by tusharpandey1993** [comment]
Hi,
I was facing the same issue. Thus I added the dependency available here [shopify graphql support](https://github.com/Shopify/graphql_java_gen) , But android didn't support the latest version.
Then I later added all the required files in my source code ( For example: I added [Input.java](https://github.com/Shopify/graphql_java_gen/blob/master/support/src/main/java/com/shopify/graphql/support/Input.java).
This resolved my issue.
