### ISSUE TITLE
Open the  Sample couldn't find 'com.shopify.graphql.support‘  

### ISSUE THREAD

**Issue by tubingzzz** [Shopify/mobile-buy-sdk-android#592]
When i download the 'mobile-buy-sdk-android' project , and  run  the  sample  demo on AS , couldn't find 'com.shopify.graphql' in Module 'buy3 ,  it seems missing  lib 'graphql_java_gen' ,  How can I add 'graphql-java-support' module? please! please! hlep  me!

**Comment by laceylansaw** [comment]
I have also ran into this issue. If I find any fixes I will update here.

**Comment by rebeccajfriedman** [comment]
It sounds like a problem with your set up. Have you followed these steps? https://github.com/Shopify/mobile-buy-sdk-android/blob/913062d4d1e1e71091440df257dd9ac6db9c9957/MobileBuy/sample/README.md#setup

**Comment by laceylansaw** [comment]
I did, but I found the git command wasn't working correctly for me. I wasn't signed into git on the computer I was using so it's all good now. Thanks!
