### ISSUE TITLE
Get credit card details after credit card vaulting

### ISSUE THREAD

**Issue by abohomol** [Shopify/mobile-buy-sdk-android#594]
In order to do the check out with a credit card, I have to vault it first and get a payment token back to store it for further checkouts. I want to show a user while doing a checkout an option to choose among last credit cards he used. How can I get back credit card details (like last 4 digits or if it's VISA or Mastercard) by this token?

**Comment by jamiemtdwyer** [comment]
This isn't supported, and we have no plans to support this at this time. You may want to consider integrating with a service like [Spreedly](https://docs.spreedly.com/guides/payment-method-distribution/).
