### ISSUE TITLE
checkout with credit card

### ISSUE THREAD

**Issue by jnahar2005** [Shopify/mobile-buy-sdk-android#595]
cartVaultUrl found nil
//-------Code Is given Below------------

       //var settings: Storefront.PaymentSettings!
        //var cardClient: Card.Client!
        //cardClient = Card.Client.init()
        // settings = Storefront.PaymentSettings(fields: <#[String : Any]#>)
        
let task = appDelegate.cardClient.vault(creditCard, to: appDelegate.settings.cardVaultUrl) { token, error in
        if let token = token {
            // proceed to complete checkout with `token`
            self.createCCInput(Token: token)
        } else {
            // handle error
        }
    }
    task.resume()
}

**Comment by jamiemtdwyer** [comment]
Hi @jnahar2005,

Currently, vaulting of credit cards and completing a checkout via credit card payment is not supported.

You can redirect the customer to the `webUrl` attribute of the checkout in order to have the customer complete the checkout flow on Shopify.

Cheers,

Jamie
