### ISSUE TITLE
access denied when retrieving product details

### ISSUE THREAD

**Issue by tahir90** [Shopify/mobile-buy-sdk-android#603]
Iam able to see collections list and products list but when i click a product, it gives me the following response

```
{
 "data": {},
 "errors": [
   {
     "message": "access denied",
     "locations": [
       {
         "line": 1,
         "column": 112
       }
     ],
     "path": [
       "node",
       "tags"
     ]
   }
 ]
}
```

**My request:** 

`{node(id:"Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzEwMTEwMzc1MDM1MzE="){__typename,... on Product{id,title,descriptionHtml,tags,images(first:250){edges{node{src}}},options{id,name,values},variants(first:250){edges{node{id,title,availableForSale,selectedOptions{name,value},price}}}}}}`

I am using the **sample sdk branch release 3.3.2**

**Comment by tahir90** [comment]
waiting for someone to reply to me on this.

**Comment by rebeccajfriedman** [comment]
@tahir90 you need to ensure that your private app settings allow you to show your product tags. Under apps > Manage private apps (at the bottom) > open your app and update the configurable settings as follows:

![image](https://user-images.githubusercontent.com/33286085/55732068-4c11d580-59e9-11e9-8218-33ecc35b0254.png)

Hope that helps! please reopen if this is not the issue.
