### ISSUE TITLE
Android SDK outdated

### ISSUE THREAD

**Issue by RubensHardt** [Shopify/mobile-buy-sdk-android#605]
Hi,

The company I'm working on has iOS and Android apps using the Mobile Buy SDK. For Android, we are using the version 3.3.2. We are having a lot of issues with the Android SDK because it's really outdated if compared to the iOS SDK. Does Shopify have any plans to update the Android SDK to match the iOS current version?

Thank you in advance,
Rubens

**Comment by rebeccajfriedman** [comment]
> We are having a lot of issues with the Android SDK because it's really outdated if compared to the iOS SDK.

Hi @RubensHardt - What functionality is outdated in the Android SDK that is present in the iOS SDK?

**Comment by RubensHardt** [comment]
Hi @rebeccajfriedman. The method to update all the line items at once, instead of having to remove/add/update the quantity of each item individually, having the discountApplications variable available (as mentioned in https://github.com/Shopify/mobile-buy-sdk-android/issues/604), among others.

**Comment by rebeccajfriedman** [comment]
This functionality does exist!

I suggest you clone the repo and generate javadoc locally for the `buy3` module. You'll be able to find the class `Storefront.CheckoutLineItemsReplacePayloadQuery` (which updates all line items at once), and `Storefront.CheckoutQuery.DiscountApplicationsArgumentsDefinition` (which exposes discount applications on the checkout object).

I'm going to close out this ticket, but feel free to reopen it if you have any more concerns!

**Comment by RubensHardt** [comment]
Hi @rebeccajfriedman, I'm including the 3:3.2.3 version using gradle and I still don't have access to those methods. Have you uploaded the SDK in the distribution centers?

**Comment by rebeccajfriedman** [comment]
Are you using `3.2.3` or `3.3.2`? The code is added as of `3.3.0`.
