### ISSUE TITLE
How can I get customer tags?

### ISSUE THREAD

**Issue by Paul-Petrash** [Shopify/mobile-buy-sdk-android#612]
Hi.
How can I get the customer tags on this SDK, for applying discount?
I found that there is an ability to get the customer tag via API, but it does not possible via SDK, is there way to do that ?

**Comment by rebeccajfriedman** [comment]
Customer tags is available on the Customer object - see [Storefront.java](https://github.com/Shopify/mobile-buy-sdk-android/blob/master/MobileBuy/buy3/src/main/java/com/shopify/buy3/Storefront.java) for more details.

```
/**
* A list of tags assigned to the customer.
* Additional access scope required: unauthenticated_read_customer_tags.
*/
public CustomerQuery tags() {
    startField("tags");

    return this;
}
```
