### ISSUE TITLE
Issue retrieving product_type

### ISSUE THREAD

**Issue by Mikadorimune** [Shopify/mobile-buy-sdk-android#614]
I'm using version 3.1.2 but all of the sudden I can't retrieve any product_type, I tried to up the version to 3.2.3 but the same thing happens.

`
Storefront.QueryRootQuery query = Storefront.query(new Storefront.QueryRootQueryDefinition() {
            @Override
            public void define(Storefront.QueryRootQuery rootQuery) {
                rootQuery.shop(new Storefront.ShopQueryDefinition() {
                    @Override
                    public void define(Storefront.ShopQuery shopQuery) {
                        shopQuery.productTypes(20, new Storefront.StringConnectionQueryDefinition() {
                            @Override
                            public void define(Storefront.StringConnectionQuery productTypeQuery) {
                                productTypeQuery.edges(new Storefront.StringEdgeQueryDefinition() {
                                    @Override
                                    public void define(Storefront.StringEdgeQuery productTypeQueryEdge) {
                                        productTypeQueryEdge.node();
                                    }
                                });
                            }
                        });
                    }
                });
            }
        });
`

Is my code wrong or something else since I used this code for months and it works until now

**Comment by Mikadorimune** [comment]
I'm getting this error as well 

`com.shopify.buy3.GraphNetworkError: Failed to execute GraphQL http request`

**Comment by rebeccajfriedman** [comment]
We believe that this issue has been resolved. Please reopen a ticket if the problem persists.

**Comment by ashwaniRoshan** [comment]
I'm getting this error as well

com.shopify.buy3.GraphNetworkError: Failed to execute GraphQL http request

**Comment by ashwaniRoshan** [comment]
> We believe that this issue has been resolved. Please reopen a ticket if the problem persists.

I'm getting this error as well

com.shopify.buy3.GraphNetworkError: Failed to execute GraphQL http request

**Comment by arsalyou** [comment]
Did you solve this issue?
