### ISSUE TITLE
How to send Monogram and Gift wrap option while  checkout in Android mobile app.

### ISSUE THREAD

**Issue by Bhargavasrinivas** [Shopify/mobile-buy-sdk-android#618]
Hii Everyone.

I  am developing an  android app using Android buy sdk , where we are selling perfumes , but here i had given them an option of Gift wrapping  and monogram , is there any api support to send this gift wrapping and monogram (like letters to print on the bottle )as parameter while checkout. i am using web-checkout to full fill the orders.

**Comment by vixdug** [comment]
Hi @Bhargavasrinivas You will want to utilize custom attributes. Here is an example: 
```
/**
        * A list of extra information that is added to the checkout.
        */

        public List<Attribute> getCustomAttributes() {
            return (List<Attribute>) get("customAttributes");
        }

        public Checkout setCustomAttributes(List<Attribute> arg) {
            optimisticData.put(getKey("customAttributes"), arg);
            return this;
        }
```
You can find more information in [storefront.java](https://raw.githubusercontent.com/Shopify/mobile-buy-sdk-android/master/MobileBuy/buy3/src/main/java/com/shopify/buy3/Storefront.java). You can also read through the storefront API documentation [here](https://help.shopify.com/en/api/storefront-api/reference/object/checkoutlineitem)

**Comment by Bhargavasrinivas** [comment]
Hii Vixdug,
  Thanks for your help , but i bit confused that how to send custom attributes as as parameter fo check out api , below i pasted my code snippet can u know how to send monogram and gift wrap option for this code

  
            var quantity :Int! = 0
            
            for index  in 0..<CartClsArray.count {
                
                
                quantity = Int(CartClsArray[index].Quantity)
                
                var productId = CartClsArray[index].ProductVarinatId
                
                
                
                
                
                dataList.append(Storefront.CheckoutLineItemInput(quantity: Int32(CartClsArray[index].Quantity)!,variantId: GraphQL.ID(rawValue: productId)))
                
                
                
            }
            
            
    
            let checkoutInput = Storefront.CheckoutCreateInput.create(
                lineItems: .value(dataList)
                
            )
            
            let mutation = Storefront.buildMutation { $0
                .checkoutCreate(input:checkoutInput) { $0
                    .checkout { $0
                        .id()
                        .webUrl()
                    
                        
                        
                    }
                    .userErrors { $0
                        .field()
                        .message()
                    }
                }
            }
