### ISSUE TITLE
Adding Art work to checkout api call 

### ISSUE THREAD

**Issue by Bhargavasrinivas** [Shopify/mobile-buy-sdk-android#629]
Hi Guys ,

I'm developing an android application , where i had given option for customer to upload PDF file , image or doc files to make an order for Embroidery or screen prints works, so customer will upload  one of the file  and i'm getting path of  respective image, PDF file and now the problem  how to send this path  to checkout API call using custom attributes ,  here i'm using web checkout

Thanks in advance

**Comment by rebeccajfriedman** [comment]
Hello @Bhargavasrinivas , [please use our forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology) for questions around implementing features.
