### ISSUE TITLE
Unable to upload file or image from Android app.

### ISSUE THREAD

**Issue by Bhargavasrinivas** [Shopify/mobile-buy-sdk-android#631]
Hi ,

I am developing android app ,  where i have i need to upload the image or file  which is chosen from  user  to shopify back end  . i copied the URL path from shopify files which we normally do , i'm getting this URL path from, when i select in shopify  setting and then upload files section, and when i try to upload file  from mobile application i'm getting 403 error code (accesses denied).

**Comment by rebeccajfriedman** [comment]
I'm going to close this issue, as it sounds like your problem is unrelated to the Mobile Buy Android SDK (which is an SDK that makes it easy to create custom storefronts in a mobile app).
