### ISSUE TITLE
API Version 2020-01 Release

### ISSUE THREAD

**Issue by rebeccajfriedman** [Shopify/mobile-buy-sdk-android#632]
Release to update to the latest API Version (2020-01)

Loop @ershkia in so he can ramp up on the release process for Android

**Comment by jmignac** [comment]
PR: https://github.com/Shopify/mobile-buy-sdk-android/pull/634

People using Kotlin to build their apps against our SDKs can benefit from the option locale param. However, for people using Java that will be a breaking change. I'd like to spend the afternoon building a constructor for the graph client, so it supports the feature with backwards compatibility.
