### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by ashwaniRoshan** [Shopify/mobile-buy-sdk-android#635]
**Please complete the checklist before filing an issue:**

- [ ] Is this a "how to" question? For questions on how to use the SDK, implement features or other related questions, [please use our forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology).
- [ ] Is this something you can **debug and fix**? Create a pull request and contribute! Bug fixes and documentation fixes are welcome. You can read our [contribution](https://github.com/Shopify/mobile-buy-sdk-android/blob/master/CONTRIBUTING.md) guidelines for more details.

None of the above? Create an issue. Be sure to include all the necessary information for us to understand and reproduce the problem:

- Screenshot (if applicable)
- Stack trace, if the problem is related to a crash in the SDK
- Version of the SDK are you using
- What is the expected behaviour?
- What is happening instead?

If there's not enough information to address the problem, we'll tag your issue with `information required` and close it until further information is provided.

**Comment by ashwaniRoshan** [comment]
Domain- redforms.myshopify.com
API Key- f135ac6980c09fc4bd928442212722a7

**Comment by RoohBear** [comment]
I just realized today you need to use the Storefront access token, not the API key.  That solved the 403 errors I was getting.

**Comment by jzwermut** [comment]
You are my hero RoohBear. I was stuck on this for hours. What a poor UX experience from shopify admin to stick is all the way at the bottom.
