### ISSUE TITLE
Getting issue in Web Checkout's Polling result method

### ISSUE THREAD

**Issue by rushabh13** [Shopify/mobile-buy-sdk-android#658]
I am doing [WebCheckout](https://github.com/Shopify/mobile-buy-sdk-android#web-checkout-). After that, I am getting a callback of that Checkout callback. 

I have followed the way which has been written [here](https://github.com/Shopify/mobile-buy-sdk-android#polling-for-checkout-completion-).

```
GraphClient client = ...;
ID paymentId = ...;

Storefront.QueryRootQuery query = Storefront.query(rootQuery -> rootQuery
    .node(paymentId, nodeQuery -> nodeQuery
	    .onPayment(paymentQuery -> paymentQuery
		.checkout(checkoutQuery -> checkoutQuery
                    .ready()
		    .order(orderQuery -> orderQuery
			.processedAt()
			.orderNumber()
			.totalPrice()))
		.errorMessage()
		.ready()
		)
    )
);
```

I have faced the following issues:
### **1.** `ID paymentId = ...;`
It shouldn't be paymentId, It is checkoutId while will be received in response of [this request](https://github.com/Shopify/mobile-buy-sdk-android#checkout-). 

### **2.** Not getting _null_ value in the response of below code:
```
Storefront.QueryRootQuery query = Storefront.query(rootQuery -> rootQuery
    .node(paymentId, nodeQuery -> nodeQuery
	    .onPayment(paymentQuery -> paymentQuery
		.checkout(checkoutQuery -> checkoutQuery
		    .order(orderQuery -> orderQuery
			.processedAt()
			.orderNumber()
			.totalPrice()))
		.errorMessage()
		.ready()
		)
    )
);
```

### - 2.1 If I removed the below line than I can able to get some data:
`.onPayment(paymentQuery -> paymentQuery`

So, code will be look like this :
```
.node(paymentId) { nodeQuery: NodeQuery ->
    nodeQuery.onCheckout { checkoutQuery: CheckoutQuery ->
        checkoutQuery
            .createdAt()
            .updatedAt()
            .completedAt()
            .email()
            .ready()
            .order {
                it.orderNumber()
            }
    }
}
```
In above code, I am always getting **ready=true** (Whether I have purchased the product or not). The ready field is using inside the retryHandler function. 
```
RetryHandler.exponentialBackoff(500, TimeUnit.MILLISECONDS, 1.2f)
.whenResponse(
      response -> ((Storefront.Payment) ((GraphResponse<Storefront.QueryRoot>) response).data().getNode()).getReady() == false
    )
    .maxCount(12)
    .build()
```

### - 2.2, I am getting _order=null_. I need orderNumber to display, so how can I get that? 

==================================================================
### Expected behavior:

- **In Point 1**, It might be some typing mistake, instead of `paymentId`, it must display `checkoutId`. As it is confusing to the developer.
- **In Point 2**, It must return the needed data.
- **In Point 2.1**, The `ready` field must be changed when the order is successfully placed.
- **In Point 2.2**, The `order` field must not be null.

**Comment by rushabh13** [comment]
Hello All, Found the solution,

**Point 1,** 
- It is checkoutId not paymentId

**Point 2,**
**NOTE**: Please make a note that, for getting updated result, you have to remove the defaultCachePolicy from the GraphClient object where we are setting up our shop to Shopify.

Now, [while Polling for checkout completion](https://github.com/Shopify/mobile-buy-sdk-android#polling-for-checkout-completion-), pass HTTPCachePolicy as HttpCachePolicy.Default.NETWORK_ONLY. It will solve your problem.

And the query will be as follows,
```
rootQuery.node(paymentId) { nodeQuery: NodeQuery ->
    nodeQuery.onCheckout { checkoutQuery: CheckoutQuery ->
        checkoutQuery
            .createdAt()
            .updatedAt()
            .completedAt()
            .email()
            .ready()
            .order {
                it.orderNumber()
            }
    }
}
```

**Comment by Okiring** [comment]
i was getting the same errors,. tried using your method..but i cant get my retry handler to work,,it only works if i use it  like ->   RetryHandler.exponentialBackoff(500, TimeUnit.MILLISECONDS, 1.2f)
                        .whenResponse(

                                response ->  ((Storefront.CheckOut) ((GraphResponse<Storefront.QueryRoot>) response).data().getNode()).getReady() == false)

                        .maxCount(50)
                        .build()



But when use it like ->   RetryHandler.exponentialBackoff(500, TimeUnit.MILLISECONDS, 1.2f)
                        .whenResponse(

                                response ->  ((Storefront.Payment) ((GraphResponse<Storefront.QueryRoot>) response).data().getNode()).getReady() == false)

                        .maxCount(50)
                        .build()

it just fails to reschedule e request. How did u get past this issue...i removed the default cache policy from the client and during request i set it to Network Only. The polling only works on the shipping methods. but is failing upon polling for checkout completion.

**Comment by monali2610** [comment]
I was getting the same errors.

**Comment by Okiring** [comment]
i managed to solve the issue .....in the retry handler,check if order == null..keep polling untill order is not equal to null. i did that and tested with a web checkout..after making payment for a product.. i got response with the order-id...shopifyz documentation is not updated at all.....

**Comment by asadwaheed1** [comment]
> 
> 
> i managed to solve the issue .....in the retry handler,check if order == null..keep polling untill order is not equal to null. i did that and tested with a web checkout..after making payment for a product.. i got response with the order-id...shopifyz documentation is not updated at all.....

Thank you I am able to fix same issue using your answer
