### ISSUE TITLE
Can we call the Admin Graph API using this sdk??

### ISSUE THREAD

**Issue by abhishekdubeyp** [Shopify/mobile-buy-sdk-android#663]

**Comment by osamie** [comment]
Hi @abhishekdubeyp 
This sdk uses the [Storefront GraphQL API](https://shopify.dev/docs/storefront-api). Please **[use our forums for sdk questions](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology)**
