### ISSUE TITLE
Product and ProductVariant metafields return null

### ISSUE THREAD

**Issue by taranTR** [Shopify/mobile-buy-sdk-android#672]
I try to get product and product variant's all metafields but returns null.I also try to get metafield by specific namespace and key but response is null again.
I work on StoreFront api, android sdk version 6.0.0.
Any Idea about this?

**Comment by vixdug** [comment]
@taranTR You may need to expose the metafields to the Storefront API. Here is a guide: https://shopify.dev/tutorials/retrieve-metafields-with-storefront-api

In the future these type of troubleshooting questions are best suited for the [forums](https://community.shopify.com/c/Storefront-API-SDKs/bd-p/custom-storefronts)
