### ISSUE TITLE
Better Mock Data detection

### ISSUE THREAD

**Issue by krisorr** [Shopify/mobile-buy-sdk-android#80]
Currently we try to use Mock Data if any of the API_KEY, APP_ID, CHANNEL_ID are not defined by a shop.properties file or environment variables.
We should instead use an explicit flag USE_MOCK_DATA which would be false by default, and can be set to true in the shop.properties or environment.
If any of the required values are missing (ie. API_KEY) it should halt the build with an error for the case where USE_MOCK_DATA=false

**Comment by sav007** [comment]
2.x is no longer maintained. New version 3.0 has been released. Closing.
