### ISSUE TITLE
Create a migration document

### ISSUE THREAD

**Issue by krisorr** [Shopify/mobile-buy-sdk-android#90]
The migration document should document all the changes between 1.x and 2.x.
It should details the steps needed to migrate.
- [ ] new/change gradle dependecies
- [ ] changes to BuyClient creation
- [ ] classes that were removed, moved, renamed etc.

**Comment by krisorr** [comment]
Library migration:

com.squareup.retrofit:retrofit:1.9.0 -> com.squareup.retrofit2:retrofit:2.0.1
com.squareup.okhttp:okhttp-urlconnection:2.5.0 -> com.squareup.okhttp3:okhttp-urlconnection:3.2.0

API CHANGES:

The signature of Callback for BuyClient API calls has been changed

retrofit.Callback {

    void success(Object obj, retrofit.client.Response response)

    void failure(retrofit.RetrofitError error)
}
-->
com.shopify.buy.dataprovider.Callback {
   
   void success(Object obj)
   
   void failure(com.shopify.buy.dataprovider.BuyClientError error) 
}

retrofit.client.Response and retrofit.RetrofitError right now no longer available in callback. For error handling use com.shopify.buy.dataprovider.BuyClientError instead.

Rx support was introduced, all BuyClient API calls have duplicate version that returns rx.Observable.

API calls that takes Callback as a parameter return com.shopify.buy.dataprovider.CancellableTask that allows to cancel request.

Customer API introduced.
Order API introduced.
AndroidPay introduced.

Get products by handle introduced.

For Checkout API some methods required checkout token instead of full Checkout

com.shopify.buy.model.Collection#getCollectionId() returns Long instead String
com.shopify.buy.model.Product#getProductId() returns Long instead String

The way how BuyClient instantiated changed: com.shopify.buy.dataprovider.BuyClientFactory has been removed and com.shopify.buy.dataprovider.BuyClientBuilder introduced.

All util methods from BuyClientFactory moved to com.shopify.buy.dataprovider.BuyClientUtils, error util functions moved to com.shopify.buy.dataprovider.BuyClientError

**Comment by niwinnm** [comment]
Hi, when can we expect V2.X to be released?

**Comment by krisorr** [comment]
@niwinnm getProductByHandle() will get you a single product by product handle.

If you can add a feature request for get products by collection handle, it would be appreciated.

We are putting some finishing touches on the SDK, and will be releasing soon.  You can see the work in progress at https://github.com/Shopify/mobile-buy-sdk-android/tree/version-2.

We also have a forum that is great for support and getting answers about the existing APIs - https://ecommerce.shopify.com/c/shopify-apis-and-technology.

**Comment by niwinnm** [comment]
@krisorr Thanks for the info. Looking forward to get the stable release of the v2 SDK. Let me know if there is something I could contribute to the open SDK. 

Also, I have created a new feature request in here: #198

**Comment by krisorr** [comment]
Great, thank you.
