### ISSUE TITLE
Set up nightly BuildKite builds

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-android#98]
Install a cron job on an accessible computer to trigger a build every night.

**Comment by krisorr** [comment]
No new buildkite job is needed, it already exists.
We do need to update the cron job that is running to point to the public repo

**Comment by bgulanowski** [comment]
cc @jules2689 if you can help with this

**Comment by jules2689** [comment]
Buildkite has no built in nightly support so I'm not sure what you're doing here to accomplish this. I am away this week at a conference, so can't help.
